"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import json
import os
import socket
import tempfile
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

def _load_local_env_file():
    """Populate os.environ with values from BASE_DIR/.env if present."""
    env_path = BASE_DIR / '.env'
    if not env_path.exists():
        return
    try:
        with env_path.open() as handle:
            for raw_line in handle:
                line = raw_line.strip()
                if not line or line.startswith('#') or '=' not in line:
                    continue
                key, value = line.split('=', 1)
                key = key.strip()
                if not key or key in os.environ:
                    continue
                value = value.strip()
                if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"', '’', '‘', '“', '”'}:
                    value = value[1:-1]
                os.environ[key] = value
    except OSError:
        pass

_load_local_env_file()

# Production Firebase credentials from environment variable (for Render.com)
firebase_creds_json = os.environ.get('GOOGLE_APPLICATION_CREDENTIALS_JSON', '')
if firebase_creds_json and not os.environ.get('FIREBASE_CREDENTIALS'):
    try:
        creds_data = json.loads(firebase_creds_json)
        # Properly handle newlines in the private key
        # Render may store \n as literal two characters or actual newlines
        if 'private_key' in creds_data and isinstance(creds_data['private_key'], str):
            private_key = creds_data['private_key']
            # First replace literal backslash-n with actual newline
            private_key = private_key.replace('\\n', '\n')
            # Also handle case where it might be double-escaped
            private_key = private_key.replace('\\\\n', '\n')
            creds_data['private_key'] = private_key
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
            json.dump(creds_data, f)
            temp_file_path = f.name
            os.environ['FIREBASE_CREDENTIALS'] = temp_file_path
            os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = temp_file_path
            
        import logging
        logger = logging.getLogger(__name__)
        logger.info(f"Firebase credentials loaded from GOOGLE_APPLICATION_CREDENTIALS_JSON, temp file: {temp_file_path}")
    except json.JSONDecodeError as e:
        import logging
        logger = logging.getLogger(__name__)
        logger.error(f"Failed to parse GOOGLE_APPLICATION_CREDENTIALS_JSON: {e}")
    except Exception as e:
        import logging
        logger = logging.getLogger(__name__)
        logger.error(f"Failed to initialize Firebase credentials: {e}")

# If FIREBASE_CREDENTIALS is a relative path, make it absolute
firebase_cred_path = os.environ.get('FIREBASE_CREDENTIALS', '')
if firebase_cred_path and not os.path.isabs(firebase_cred_path):
    abs_path = BASE_DIR / firebase_cred_path
    if abs_path.exists():
        os.environ['FIREBASE_CREDENTIALS'] = str(abs_path)
        os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = str(abs_path)

# Read secret key and debug flag from environment with sensible defaults
# ⚠️  UC-117: All external API calls must use core.api_monitoring.track_api_call()
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'replace-me-in-production')

DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Allow hosts from environment (space-separated) or fallback to localhost
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost 127.0.0.1').split()

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'corsheaders',
    # Cloudinary for file storage
    'cloudinary_storage',
    'cloudinary',
    # Project apps
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.FirebaseAuthenticationMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database configuration: use PostgreSQL with values from env vars
def _should_use_sqlite() -> bool:
    """Only use SQLite for explicit test scenarios, never as a fallback in production."""
    if os.environ.get('USE_SQLITE_FOR_TESTS') in {'1', 'true', 'True'}:
        return True
    if os.environ.get('PYTEST_CURRENT_TEST') or os.environ.get('DJANGO_TEST') == '1':
        return True
    # In production (DEBUG=False), always use PostgreSQL
    if os.environ.get('DJANGO_DEBUG', 'True') == 'False':
        return False
    # For local development without explicit POSTGRES_HOST, use SQLite
    if not os.environ.get('POSTGRES_HOST'):
        return True
    return False


_USE_SQLITE = _should_use_sqlite()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3' if _USE_SQLITE else 'django.db.backends.postgresql',
        'NAME': BASE_DIR / 'db.sqlite3' if _USE_SQLITE else os.environ.get('POSTGRES_DB', 'yourdb'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.environ.get('POSTGRES_HOST', 'db'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}

if _USE_SQLITE:
    DATABASES['default'].pop('USER')
    DATABASES['default'].pop('PASSWORD')
    DATABASES['default'].pop('HOST')
    DATABASES['default'].pop('PORT')

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Use bcrypt for password hashing to satisfy UC-010 security requirement
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    # Fallbacks to allow verifying existing hashes if present
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/New_York'  # Eastern Time
USE_I18N = True
USE_TZ = True  # Keep timezone-aware datetimes (stored as UTC, displayed in TIME_ZONE)

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cloudinary configuration for production file storage
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}

# Use Cloudinary for media files in production
if not DEBUG:
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Profile picture settings
MAX_UPLOAD_SIZE = 5 * 1024 * 1024  # 5MB

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
# When using credentials, do NOT use wildcard origins; explicitly list dev origins
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False

# Optional: allow Authorization header for Firebase token
CORS_ALLOW_HEADERS = list(set([
    'accept', 'accept-encoding', 'authorization', 'content-type', 'dnt', 'origin', 'user-agent', 'x-csrftoken', 'x-requested-with'
]))

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:3001',  # add whichever port you’re using
]
# Add production CORS origins from environment variable
_env_cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS', '').split()
CORS_ALLOWED_ORIGINS.extend([o for o in _env_cors_origins if o and o not in CORS_ALLOWED_ORIGINS])

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:3001',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]
# Add production CSRF origins from environment variable
_env_csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split()
CSRF_TRUSTED_ORIGINS.extend([o for o in _env_csrf_origins if o and o not in CSRF_TRUSTED_ORIGINS])


# Production security settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True


# Relax cookie settings in development for Django admin and OAuth
if DEBUG:
    SESSION_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = False

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # For Django admin session
        'core.authentication.FirebaseAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    # Disable DRF's automatic `?format=` override to avoid DRF raising Http404
    # for unrecognized format query parameters; views will validate formats explicitly.
    'URL_FORMAT_OVERRIDE': None,
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Firebase settings
FIREBASE_CREDENTIALS_PATH = os.environ.get('FIREBASE_CREDENTIALS', '')
FIREBASE_PROJECT_ID = os.environ.get('FIREBASE_PROJECT_ID', '')

# Logging configuration: log auth events and core app debug info to console
LOG_LEVEL = os.environ.get('DJANGO_LOG_LEVEL', 'INFO')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} | {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.auth': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'core': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

# Generative AI (Gemini) configuration for resume content (UC-047)
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')
GEMINI_MODEL = os.environ.get('GEMINI_MODEL', 'gemini-2.5-flash')
TECTONIC_BINARY = os.environ.get('TECTONIC_BINARY', 'tectonic')

# Email configuration
# Priority: Explicit DJANGO_EMAIL_BACKEND overrides DEBUG logic.
EMAIL_BACKEND = os.environ.get('DJANGO_EMAIL_BACKEND')
if EMAIL_BACKEND:
    # Use provided backend regardless of DEBUG and load SMTP-related settings from env
    EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587')) if os.environ.get('EMAIL_PORT') else None
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False') == 'True'
else:
    # In development by default, print emails to console to simplify testing
    if DEBUG:
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    else:
        # Production default: SMTP backend with env configuration
        EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
        EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
        EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587')) if os.environ.get('EMAIL_PORT') else None
        EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
        EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
        EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
        EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False') == 'True'

# Default sender email address for outgoing emails
# Uses environment variable if provided; otherwise falls back to the desired sender address
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'resumerocket123@gmail.com')

# Frontend base URL for links in emails (used by reminder emails)
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

# Google OAuth for Contacts import (UC-086)
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', 'dummy-google-client-id')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', 'dummy-google-client-secret')

# LinkedIn OAuth for Profile Integration (UC-089)
LINKEDIN_CLIENT_ID = os.environ.get('LINKEDIN_CLIENT_ID', '')
LINKEDIN_CLIENT_SECRET = os.environ.get('LINKEDIN_CLIENT_SECRET', '')

# Celery (background tasks) broker URL; default to Redis in docker-compose if present
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', os.environ.get('REDIS_URL', 'redis://redis:6379/0'))
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)

# Django Cache - use Redis for caching (including OAuth state tokens)
# Note: Upstash Redis requires TLS (rediss://) - convert redis:// to rediss:// if needed
_redis_url = os.environ.get('REDIS_URL', 'redis://redis:6379/0')
# Upstash URLs need rediss:// for TLS - auto-convert if it's an upstash URL with redis://
if 'upstash.io' in _redis_url and _redis_url.startswith('redis://'):
    _redis_url = _redis_url.replace('redis://', 'rediss://', 1)

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': _redis_url,
    }
}

# Sentry error tracking for production (UC-133)
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN and not DEBUG:
    try:
        import sentry_sdk
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            traces_sample_rate=0.1,
            profiles_sample_rate=0.1,
            send_default_pii=False,
        )
    except ImportError:
        pass

# WhiteNoise static file compression
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Deployment API Key for CI/CD pipeline authentication (UC-099)
DEPLOYMENT_API_KEY = os.environ.get('DEPLOYMENT_API_KEY', '')

# Environment identifier for deployment tracking
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'development')
