# Generated by Django 5.2.7 on 2025-11-06 21:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def create_default_cover_letter_templates(apps, schema_editor):
    """Create default cover letter templates for different industries and styles."""
    CoverLetterTemplate = apps.get_model('core', 'CoverLetterTemplate')
    
    templates = [
        {
            'name': 'Formal Business Template',
            'description': 'Professional template suitable for corporate and traditional business environments.',
            'template_type': 'formal',
            'industry': 'Business',
            'content': '''Dear [Hiring Manager's Name],

I am writing to express my strong interest in the [Position Title] position at [Company Name]. With my background in [Relevant Experience], I am confident that I would be a valuable addition to your team.

In my previous role at [Previous Company], I [Key Achievement 1] and [Key Achievement 2]. These experiences have equipped me with the skills necessary to excel in this position, particularly in [Relevant Skill Area].

I am particularly drawn to [Company Name] because of [Company-Specific Reason]. Your commitment to [Company Value/Mission] aligns perfectly with my professional values and career goals.

I would welcome the opportunity to discuss how my experience and enthusiasm can contribute to your team's success. Thank you for your time and consideration.

Sincerely,
[Your Name]''',
            'sample_content': '''Dear Ms. Johnson,

I am writing to express my strong interest in the Marketing Manager position at ABC Corporation. With my background in digital marketing and brand management, I am confident that I would be a valuable addition to your team.

In my previous role at XYZ Company, I increased social media engagement by 150% and launched three successful product campaigns. These experiences have equipped me with the skills necessary to excel in this position, particularly in strategic marketing planning.

I am particularly drawn to ABC Corporation because of your innovative approach to sustainable business practices. Your commitment to environmental responsibility aligns perfectly with my professional values and career goals.

I would welcome the opportunity to discuss how my experience and enthusiasm can contribute to your team's success. Thank you for your time and consideration.

Sincerely,
Jane Doe''',
            'is_shared': True,
            'customization_options': {
                'placeholders': ['[Hiring Manager\'s Name]', '[Position Title]', '[Company Name]', '[Relevant Experience]', '[Previous Company]', '[Key Achievement 1]', '[Key Achievement 2]', '[Relevant Skill Area]', '[Company-Specific Reason]', '[Company Value/Mission]', '[Your Name]'],
                'sections': ['greeting', 'introduction', 'experience', 'company_interest', 'closing']
            }
        },
        {
            'name': 'Creative Industry Template',
            'description': 'Dynamic template for creative fields like design, marketing, and media.',
            'template_type': 'creative',
            'industry': 'Creative',
            'content': '''Hello [Hiring Manager's Name],

I'm excited to apply for the [Position Title] role at [Company Name]. As a passionate [Your Professional Identity], I believe my creative vision and [Relevant Skills] make me an ideal fit for your team.

What sets me apart is my ability to [Unique Strength 1] while maintaining [Unique Strength 2]. At [Previous Company], I [Creative Achievement] that resulted in [Measurable Impact]. This project showcased my expertise in [Technical Skills] and my understanding of [Industry Knowledge].

[Company Name]'s [Recent Project/Campaign] caught my attention because [Personal Connection/Opinion]. I'm particularly interested in how you [Company Innovation], and I'd love to contribute my [Relevant Skill] to help push these boundaries even further.

I've attached my portfolio showcasing [Portfolio Highlights]. I'd be thrilled to discuss how my creative approach and technical skills can help [Company Name] continue to [Company Goal].

Looking forward to hearing from you!

Best regards,
[Your Name]''',
            'sample_content': '''Hello Alex,

I'm excited to apply for the UX Designer role at InnovateDesign. As a passionate user experience designer, I believe my creative vision and human-centered design approach make me an ideal fit for your team.

What sets me apart is my ability to balance aesthetics with functionality while maintaining accessibility standards. At DesignPro, I redesigned their mobile app interface that resulted in a 40% increase in user engagement. This project showcased my expertise in user research and my understanding of conversion optimization.

InnovateDesign's recent accessibility initiative caught my attention because I'm passionate about inclusive design. I'm particularly interested in how you're pioneering voice UI interfaces, and I'd love to contribute my prototyping skills to help push these boundaries even further.

I've attached my portfolio showcasing mobile app designs and user research studies. I'd be thrilled to discuss how my creative approach and technical skills can help InnovateDesign continue to lead in accessible technology.

Looking forward to hearing from you!

Best regards,
Sarah Chen''',
            'is_shared': True,
            'customization_options': {
                'placeholders': ['[Hiring Manager\'s Name]', '[Position Title]', '[Company Name]', '[Your Professional Identity]', '[Relevant Skills]', '[Unique Strength 1]', '[Unique Strength 2]', '[Previous Company]', '[Creative Achievement]', '[Measurable Impact]', '[Technical Skills]', '[Industry Knowledge]', '[Recent Project/Campaign]', '[Personal Connection/Opinion]', '[Company Innovation]', '[Relevant Skill]', '[Portfolio Highlights]', '[Company Goal]', '[Your Name]'],
                'sections': ['greeting', 'introduction', 'differentiator', 'company_connection', 'portfolio_mention', 'closing']
            }
        },
        {
            'name': 'Technical Engineering Template',
            'description': 'Structured template for software engineering and technical positions.',
            'template_type': 'technical',
            'industry': 'Technology',
            'content': '''Dear [Hiring Manager's Name],

I am writing to apply for the [Position Title] position at [Company Name]. With [Years of Experience] years of experience in [Technical Domain] and expertise in [Primary Technologies], I am excited about the opportunity to contribute to your engineering team.

My technical background includes:
• [Technical Skill 1] - [Brief Description/Achievement]
• [Technical Skill 2] - [Brief Description/Achievement]
• [Technical Skill 3] - [Brief Description/Achievement]

In my current role at [Current Company], I [Major Technical Achievement] using [Technologies Used]. This project [Impact/Result] and demonstrated my ability to [Key Technical Competency].

I am particularly interested in [Company Name] because of your work on [Technical Project/Product]. Your approach to [Technical Challenge] aligns with my experience in [Relevant Technical Area], and I would be excited to contribute to [Specific Technical Goal].

I have attached my resume detailing my technical experience and would welcome the opportunity to discuss how my skills in [Key Technologies] can benefit your team.

Thank you for your consideration.

Best regards,
[Your Name]''',
            'sample_content': '''Dear Engineering Team,

I am writing to apply for the Senior Software Engineer position at TechFlow Inc. With 5 years of experience in full-stack development and expertise in React, Node.js, and AWS, I am excited about the opportunity to contribute to your engineering team.

My technical background includes:
• React/TypeScript - Built scalable front-end applications serving 100k+ users
• Node.js/Express - Designed RESTful APIs handling 1M+ requests daily
• AWS/Docker - Implemented CI/CD pipelines reducing deployment time by 60%

In my current role at DataSoft, I architected a microservices platform using Node.js and Docker that improved system reliability by 35%. This project handled real-time data processing and demonstrated my ability to design fault-tolerant systems.

I am particularly interested in TechFlow Inc. because of your work on real-time analytics platforms. Your approach to handling large-scale data streams aligns with my experience in distributed systems, and I would be excited to contribute to your next-generation analytics engine.

I have attached my resume detailing my technical experience and would welcome the opportunity to discuss how my skills in modern web technologies can benefit your team.

Thank you for your consideration.

Best regards,
Michael Rodriguez''',
            'is_shared': True,
            'customization_options': {
                'placeholders': ['[Hiring Manager\'s Name]', '[Position Title]', '[Company Name]', '[Years of Experience]', '[Technical Domain]', '[Primary Technologies]', '[Technical Skill 1]', '[Technical Skill 2]', '[Technical Skill 3]', '[Current Company]', '[Major Technical Achievement]', '[Technologies Used]', '[Impact/Result]', '[Key Technical Competency]', '[Technical Project/Product]', '[Technical Challenge]', '[Relevant Technical Area]', '[Specific Technical Goal]', '[Key Technologies]', '[Your Name]'],
                'sections': ['introduction', 'technical_skills', 'achievement', 'company_interest', 'closing']
            }
        },
        {
            'name': 'Healthcare Industry Template',
            'description': 'Professional template tailored for healthcare and medical positions.',
            'template_type': 'industry',
            'industry': 'Healthcare',
            'content': '''Dear [Hiring Manager's Name],

I am writing to express my interest in the [Position Title] position at [Healthcare Organization]. With my background in [Healthcare Specialization] and commitment to [Healthcare Value], I am eager to contribute to your team's mission of providing exceptional patient care.

My healthcare experience includes:
• [Healthcare Experience 1]
• [Healthcare Experience 2]
• [Healthcare Experience 3]

In my previous role at [Previous Healthcare Facility], I [Healthcare Achievement] which [Patient Impact]. I am particularly skilled in [Clinical Skill] and have experience with [Healthcare Systems/Protocols].

[Healthcare Organization]'s reputation for [Organization Strength] and commitment to [Healthcare Mission] strongly resonates with my professional values. I am excited about the opportunity to contribute to [Specific Healthcare Goal] and work with your team to [Healthcare Objective].

I am licensed/certified in [Relevant Certifications] and committed to maintaining the highest standards of patient care and professional development.

Thank you for considering my application. I look forward to discussing how I can contribute to your healthcare team.

Sincerely,
[Your Name]''',
            'sample_content': '''Dear Dr. Williams,

I am writing to express my interest in the Registered Nurse position at Mercy General Hospital. With my background in emergency care nursing and commitment to compassionate patient care, I am eager to contribute to your team's mission of providing exceptional patient care.

My healthcare experience includes:
• 3 years in emergency department nursing
• BLS, ACLS, and PALS certifications
• Experience with electronic health records (Epic)

In my previous role at City Medical Center, I managed care for up to 12 patients per shift which improved patient satisfaction scores by 15%. I am particularly skilled in IV insertion and have experience with trauma protocols and emergency procedures.

Mercy General Hospital's reputation for innovative emergency care and commitment to community health strongly resonates with my professional values. I am excited about the opportunity to contribute to your Level I trauma center and work with your team to provide life-saving care.

I am licensed as an RN in the state and committed to maintaining the highest standards of patient care and professional development.

Thank you for considering my application. I look forward to discussing how I can contribute to your healthcare team.

Sincerely,
Jennifer Martinez, RN''',
            'is_shared': True,
            'customization_options': {
                'placeholders': ['[Hiring Manager\'s Name]', '[Position Title]', '[Healthcare Organization]', '[Healthcare Specialization]', '[Healthcare Value]', '[Healthcare Experience 1]', '[Healthcare Experience 2]', '[Healthcare Experience 3]', '[Previous Healthcare Facility]', '[Healthcare Achievement]', '[Patient Impact]', '[Clinical Skill]', '[Healthcare Systems/Protocols]', '[Organization Strength]', '[Healthcare Mission]', '[Specific Healthcare Goal]', '[Healthcare Objective]', '[Relevant Certifications]', '[Your Name]'],
                'sections': ['introduction', 'experience', 'achievements', 'organization_alignment', 'credentials', 'closing']
            }
        }
    ]
    
    for template_data in templates:
        CoverLetterTemplate.objects.create(**template_data)


def reverse_default_cover_letter_templates(apps, schema_editor):
    """Remove default templates."""
    CoverLetterTemplate = apps.get_model('core', 'CoverLetterTemplate')
    template_names = [
        'Formal Business Template',
        'Creative Industry Template', 
        'Technical Engineering Template',
        'Healthcare Industry Template'
    ]
    CoverLetterTemplate.objects.filter(name__in=template_names, is_shared=True).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('behavioral', 'Behavioral'), ('technical', 'Technical'), ('system_design', 'System Design'), ('case_study', 'Case Study'), ('cultural_fit', 'Cultural Fit')], max_length=20)),
                ('question_text', models.TextField()),
                ('context', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('suggested_answer_framework', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('headline', models.CharField(blank=True, help_text='Professional title/headline (LinkedIn-style)', max_length=160)),
                ('summary', models.TextField(blank=True, help_text='Brief bio/summary (500 character limit)', max_length=500)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('experience_level', models.CharField(blank=True, choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('executive', 'Executive')], max_length=20)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture image file', null=True, upload_to='profile_pictures/%Y/%m/')),
                ('profile_picture_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('preferred_roles', models.JSONField(blank=True, default=list)),
                ('portfolio_url', models.URLField(blank=True)),
                ('visibility', models.CharField(default='private', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=200)),
                ('trigger_event', models.CharField(max_length=50)),
                ('trigger_conditions', models.JSONField(default=dict)),
                ('action_type', models.CharField(max_length=50)),
                ('action_config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('times_triggered', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='core.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('award', 'Award'), ('publication', 'Publication'), ('patent', 'Patent'), ('speaking', 'Speaking Engagement'), ('project', 'Notable Project'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('url', models.URLField(blank=True)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.candidateprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('credential_url', models.URLField(blank=True)),
                ('never_expires', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='certifications/%Y/%m/')),
                ('renewal_reminder_enabled', models.BooleanField(default=False)),
                ('reminder_days_before', models.PositiveSmallIntegerField(default=30)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='core.candidateprofile')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('domain', models.CharField(max_length=180, unique=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('hq_location', models.CharField(blank=True, max_length=160)),
                ('enrichment', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['domain'], name='idx_company_domain_lower')],
            },
        ),
        migrations.CreateModel(
            name='CompanyResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('mission_statement', models.TextField(blank=True)),
                ('culture_keywords', models.JSONField(blank=True, default=list)),
                ('recent_news', models.JSONField(blank=True, default=list)),
                ('funding_info', models.JSONField(blank=True, default=dict)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('growth_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('glassdoor_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('linkedin_url', models.URLField(blank=True)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('relationship_type', models.CharField(choices=[('colleague', 'Colleague'), ('manager', 'Manager'), ('mentor', 'Mentor'), ('recruiter', 'Recruiter'), ('employee', 'Employee at Target Company'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('last_contacted', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.candidateprofile')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='core.company')),
            ],
            options={
                'ordering': ['-last_contacted', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('resume', 'Resume'), ('cover_letter', 'Cover Letter'), ('portfolio', 'Portfolio'), ('cert', 'Certification')], max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('storage_url', models.URLField()),
                ('file_hash', models.CharField(blank=True, max_length=128)),
                ('generated_by_ai', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('applied', 'Applied'), ('phone', 'Phone Screen'), ('onsite', 'Onsite/Panel'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='interested', max_length=20)),
                ('applied_via', models.CharField(blank=True, max_length=40)),
                ('salary_expectation', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.candidateprofile')),
                ('cover_letter_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for', to='core.document')),
                ('resume_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_for', to='core.document')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree_type', models.CharField(choices=[('hs', 'High School'), ('aa', 'Associate'), ('ba', 'Bachelor'), ('ma', 'Master'), ('phd', 'PhD'), ('cert', 'Certificate'), ('boot', 'Bootcamp')], max_length=20)),
                ('field_of_study', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_enrolled', models.BooleanField(default=False)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('gpa_private', models.BooleanField(default=False, help_text='If true, GPA is hidden from shared/public views')),
                ('honors', models.CharField(blank=True, max_length=200)),
                ('achievements', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='core.candidateprofile')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=24)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('location_or_link', models.CharField(blank=True, max_length=255)),
                ('interviewer_contact', models.JSONField(blank=True, default=dict)),
                ('result', models.CharField(blank=True, max_length=16)),
                ('feedback', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewPrepSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('confidence_level', models.IntegerField(default=3)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_sessions', to='core.application')),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prep_sessions', to='core.interview')),
                ('questions_practiced', models.ManyToManyField(blank=True, related_name='practice_sessions', to='core.interviewquestion')),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='JobEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('company_name', models.CharField(max_length=180)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('posting_url', models.URLField(blank=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('job_type', models.CharField(choices=[('ft', 'Full-time'), ('pt', 'Part-time'), ('contract', 'Contract'), ('intern', 'Internship'), ('temp', 'Temporary')], default='ft', max_length=20)),
                ('personal_notes', models.TextField(blank=True, help_text='Unlimited text for personal observations')),
                ('recruiter_name', models.CharField(blank=True, max_length=180)),
                ('recruiter_email', models.EmailField(blank=True, max_length=254)),
                ('recruiter_phone', models.CharField(blank=True, max_length=20)),
                ('hiring_manager_name', models.CharField(blank=True, max_length=180)),
                ('hiring_manager_email', models.EmailField(blank=True, max_length=254)),
                ('salary_negotiation_notes', models.TextField(blank=True)),
                ('interview_notes', models.TextField(blank=True)),
                ('application_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('applied', 'Applied'), ('phone_screen', 'Phone Screen'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected')], default='interested', max_length=20)),
                ('last_status_change', models.DateTimeField(auto_now_add=True, null=True)),
                ('three_day_notice_sent_at', models.DateTimeField(blank=True, null=True)),
                ('day_of_notice_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archive_reason', models.CharField(blank=True, choices=[('completed', 'Position Filled/Completed'), ('not_interested', 'No Longer Interested'), ('rejected', 'Application Rejected'), ('expired', 'Posting Expired'), ('auto', 'Auto-archived'), ('other', 'Other')], max_length=100)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_entries', to='core.candidateprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('employment_type', models.CharField(choices=[('ft', 'Full-time'), ('pt', 'Part-time'), ('contract', 'Contract'), ('intern', 'Internship')], default='ft', max_length=20)),
                ('seniority', models.CharField(blank=True, max_length=60)),
                ('source', models.CharField(default='manual', max_length=60)),
                ('external_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('raw_posting', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.company')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='source_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.jobopportunity'),
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.jobopportunity'),
        ),
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('resume', 'Resume'), ('cover_letter', 'Cover Letter'), ('email', 'Email Template'), ('linkedin_message', 'LinkedIn Message'), ('company_research', 'Company Research'), ('interview_answer', 'Interview Answer')], max_length=30)),
                ('prompt_used', models.TextField()),
                ('generated_content', models.TextField()),
                ('model_version', models.CharField(max_length=50)),
                ('tokens_used', models.IntegerField(default=0)),
                ('generation_time_ms', models.IntegerField(default=0)),
                ('user_edited', models.BooleanField(default=False)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to='core.candidateprofile')),
                ('associated_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.jobopportunity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_required', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.jobopportunity')),
            ],
            options={
                'ordering': ['-is_required', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='JobStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('interested', 'Interested'), ('applied', 'Applied'), ('phone_screen', 'Phone Screen'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected')], max_length=20)),
                ('new_status', models.CharField(choices=[('interested', 'Interested'), ('applied', 'Applied'), ('phone_screen', 'Phone Screen'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='core.jobentry')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=220)),
                ('location', models.CharField(max_length=160)),
                ('experience_level', models.CharField(max_length=50)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('median_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentile_25', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentile_75', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sample_size', models.IntegerField(default=0)),
                ('demand_score', models.IntegerField(default=50)),
                ('growth_trend', models.CharField(default='stable', max_length=20)),
                ('top_skills', models.JSONField(blank=True, default=list)),
                ('data_source', models.CharField(blank=True, max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['job_title', 'location'], name='core_market_job_tit_af60e4_idx'), models.Index(fields=['industry'], name='core_market_industr_f60089_idx')],
            },
        ),
        migrations.CreateModel(
            name='MockInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_url', models.URLField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('ai_feedback', models.JSONField(blank=True, default=dict)),
                ('mentor_feedback', models.TextField(blank=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('areas_for_improvement', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prep_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_interviews', to='core.interviewprepsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(max_length=50)),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField()),
                ('total_applications', models.IntegerField(default=0)),
                ('applications_this_week', models.IntegerField(default=0)),
                ('phone_screens', models.IntegerField(default=0)),
                ('onsite_interviews', models.IntegerField(default=0)),
                ('offers_received', models.IntegerField(default=0)),
                ('rejections', models.IntegerField(default=0)),
                ('avg_response_time_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('conversion_rate_to_phone', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('conversion_rate_to_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('active_pipelines', models.IntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.candidateprofile')),
            ],
            options={
                'ordering': ['-metric_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('role', models.CharField(blank=True, max_length=160)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project_url', models.URLField(blank=True)),
                ('team_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('collaboration_details', models.TextField(blank=True)),
                ('outcomes', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(blank=True, help_text='Project type categorization', max_length=120)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('planned', 'Planned')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.IntegerField(default=0, help_text='Custom display order for portfolio')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.candidateprofile')),
                ('skills_used', models.ManyToManyField(blank=True, related_name='used_in_projects', to='core.skill')),
            ],
            options={
                'ordering': ['display_order', '-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('potential', 'Potential'), ('requested', 'Requested'), ('received', 'Received'), ('used', 'Used'), ('declined', 'Declined')], default='potential', max_length=20)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.application')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_given', to='core.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('follow_up', 'Follow Up'), ('interview_prep', 'Interview Preparation'), ('deadline', 'Application Deadline'), ('networking', 'Network Contact'), ('document_update', 'Update Document')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.candidateprofile')),
            ],
            options={
                'ordering': ['is_completed', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='SalaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('salary_period', models.CharField(default='yearly', max_length=20)),
                ('equity_offered', models.BooleanField(default=False)),
                ('benefits_summary', models.TextField(blank=True)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_info', to='core.jobopportunity')),
            ],
        ),
        migrations.CreateModel(
            name='SharedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_notes', to='core.application')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='related_skills',
            field=models.ManyToManyField(blank=True, related_name='interview_questions', to='core.skill'),
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='intermediate', max_length=20)),
                ('years', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('order', models.IntegerField(default=0, help_text='Display order within category')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.candidateprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.skill')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SuccessPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(max_length=50)),
                ('pattern_value', models.CharField(max_length=200)),
                ('success_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sample_size', models.IntegerField(default=0)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('insights', models.TextField(blank=True)),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_patterns', to='core.candidateprofile')),
            ],
            options={
                'ordering': ['-success_rate', '-confidence_score'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('coach', 'Career Coach'), ('mentor', 'Mentor'), ('partner', 'Accountability Partner'), ('viewer', 'Viewer')], max_length=20)),
                ('permission_level', models.CharField(choices=[('view', 'View Only'), ('comment', 'View & Comment'), ('edit', 'Edit'), ('admin', 'Admin')], default='view', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='core.candidateprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborating_on', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('profile_update', 'Profile Update'), ('application_created', 'Application Created'), ('application_updated', 'Application Status Update'), ('document_generated', 'Document Generated'), ('interview_scheduled', 'Interview Scheduled'), ('company_research', 'Company Research')], max_length=30)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=180)),
                ('job_title', models.CharField(max_length=220)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='core.candidateprofile')),
                ('skills_used', models.ManyToManyField(blank=True, related_name='used_in_experiences', to='core.skill')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=24)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.application')),
            ],
            options={
                'indexes': [models.Index(fields=['application', '-at'], name='core_applic_applica_2d3256_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoverLetterTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('formal', 'Formal'), ('creative', 'Creative'), ('technical', 'Technical'), ('industry', 'Industry-specific'), ('custom', 'Custom')], default='formal', max_length=20)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('sample_content', models.TextField(blank=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('imported_from', models.CharField(blank=True, max_length=200)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customization_options', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['template_type'], name='core_coverl_templat_7b4c6b_idx'),
                    models.Index(fields=['industry'], name='core_coverl_industr_2f8e9a_idx'),
                    models.Index(fields=['owner'], name='core_coverl_owner_i_1a3c4d_idx'),
                    models.Index(fields=['is_shared'], name='core_coverl_is_shar_5e6f7g_idx'),
                ],
            },
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['user'], name='core_candid_user_id_d5fe80_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['candidate', 'is_active'], name='core_automa_candida_c65d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['candidate', 'type', '-date'], name='core_achiev_candida_d8fb59_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['candidate', '-issue_date'], name='core_certif_candida_bcbd98_idx'),
        ),
        migrations.AddIndex(
            model_name='companyresearch',
            index=models.Index(fields=['company'], name='core_compan_company_1fef13_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['candidate', '-last_contacted'], name='core_contac_candida_f1d955_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company'], name='core_contac_company_8e065f_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['candidate', '-end_date'], name='core_educat_candida_0fa96f_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['application', '-scheduled_start'], name='core_interv_applica_1633bd_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewprepsession',
            index=models.Index(fields=['application', '-session_date'], name='core_interv_applica_9fbb33_idx'),
        ),
        migrations.AddIndex(
            model_name='jobentry',
            index=models.Index(fields=['candidate', '-updated_at'], name='core_jobent_candida_ca8b22_idx'),
        ),
        migrations.AddIndex(
            model_name='jobentry',
            index=models.Index(fields=['job_type'], name='core_jobent_job_typ_4f5186_idx'),
        ),
        migrations.AddIndex(
            model_name='jobentry',
            index=models.Index(fields=['industry'], name='core_jobent_industr_b37f74_idx'),
        ),
        migrations.AddIndex(
            model_name='jobentry',
            index=models.Index(fields=['candidate', 'status'], name='core_jobent_candida_4e0dd2_idx'),
        ),
        migrations.AddIndex(
            model_name='jobentry',
            index=models.Index(fields=['candidate', 'is_archived'], name='core_jobent_candida_036601_idx'),
        ),
        migrations.AddIndex(
            model_name='jobopportunity',
            index=models.Index(fields=['company', '-posted_at'], name='core_jobopp_company_37a625_idx'),
        ),
        migrations.AddIndex(
            model_name='jobopportunity',
            index=models.Index(fields=['active'], name='core_jobopp_active_731542_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['candidate', 'doc_type', '-created_at'], name='core_docume_candida_a64f63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('candidate', 'doc_type', 'version')},
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate', 'status', '-updated_at'], name='core_applic_candida_3c4170_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('candidate', 'job')},
        ),
        migrations.AddIndex(
            model_name='aigenerationlog',
            index=models.Index(fields=['candidate', 'content_type', '-created_at'], name='core_aigene_candida_250b78_idx'),
        ),
        migrations.AddIndex(
            model_name='aigenerationlog',
            index=models.Index(fields=['associated_job'], name='core_aigene_associa_93c33e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequirement',
            index=models.Index(fields=['job', 'category'], name='core_jobreq_job_id_088e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='jobstatuschange',
            index=models.Index(fields=['job', '-changed_at'], name='core_jobsta_job_id_456425_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='core_notifi_user_id_f286cd_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['candidate', '-metric_date'], name='core_perfor_candida_42db25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performancemetric',
            unique_together={('candidate', 'metric_date')},
        ),
        migrations.AddIndex(
            model_name='projectmedia',
            index=models.Index(fields=['project', 'order'], name='core_projec_project_486b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['application', 'status'], name='core_referr_applica_df3865_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['contact'], name='core_referr_contact_57de15_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['candidate', 'is_completed', 'due_date'], name='core_remind_candida_82df9a_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['application'], name='core_remind_applica_2081e3_idx'),
        ),
        migrations.AddIndex(
            model_name='salarydata',
            index=models.Index(fields=['job'], name='core_salary_job_id_2a0a45_idx'),
        ),
        migrations.AddIndex(
            model_name='sharednote',
            index=models.Index(fields=['application', '-created_at'], name='core_shared_applica_14df8d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['candidate', '-start_date'], name='core_projec_candida_80e864_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='core_projec_status_2020cc_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['candidate', 'display_order'], name='core_projec_candida_6564ee_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['type', 'category'], name='core_interv_type_60a7f2_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateskill',
            index=models.Index(fields=['candidate'], name='core_candid_candida_3c99f4_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateskill',
            index=models.Index(fields=['skill'], name='core_candid_skill_i_48d21d_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateskill',
            index=models.Index(fields=['candidate', 'order'], name='core_candid_candida_b6abd3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateskill',
            unique_together={('candidate', 'skill')},
        ),
        migrations.AddIndex(
            model_name='successpattern',
            index=models.Index(fields=['candidate', 'pattern_type'], name='core_succes_candida_43e3f3_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['candidate', 'is_active'], name='core_teamme_candida_a91087_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('candidate', 'user')},
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['email'], name='core_userac_email_2300c3_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', '-timestamp'], name='core_userac_user_id_efaa8e_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['action_type', '-timestamp'], name='core_userac_action__cc318d_idx'),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=models.Index(fields=['candidate', '-start_date'], name='core_workex_candida_d7b808_idx'),
        ),
        migrations.RunPython(create_default_cover_letter_templates, reverse_default_cover_letter_templates),
    ]
