# Generated by Django 5.2.7 on 2025-10-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('executive', 'Executive')], max_length=20),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='headline',
            field=models.CharField(blank=True, help_text='Professional title/headline (LinkedIn-style)', max_length=160),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='summary',
            field=models.TextField(blank=True, help_text='Brief bio/summary (500 character limit)', max_length=500),
        ),
    ]
