# Generated by Django 5.2.7 on 2025-11-07 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMaterialsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='default_cover_letter_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_cover_letter_for', to='core.document'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='default_resume_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_resume_for', to='core.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='cover_letter_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_cover_letter_in', to='core.document'),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='resume_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_resume_in', to='core.document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='storage_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='jobentry',
            index=models.Index(fields=['resume_doc'], name='core_jobent_resume__feb0a5_idx'),
        ),
        migrations.AddIndex(
            model_name='jobentry',
            index=models.Index(fields=['cover_letter_doc'], name='core_jobent_cover_l_723998_idx'),
        ),
        migrations.AddField(
            model_name='jobmaterialshistory',
            name='cover_letter_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials_history_cover', to='core.document'),
        ),
        migrations.AddField(
            model_name='jobmaterialshistory',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_history', to='core.jobentry'),
        ),
        migrations.AddField(
            model_name='jobmaterialshistory',
            name='resume_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials_history_resume', to='core.document'),
        ),
        migrations.AddIndex(
            model_name='jobmaterialshistory',
            index=models.Index(fields=['job', '-changed_at'], name='core_jobmat_job_id_6c48b2_idx'),
        ),
    ]
