# Generated by Django 5.2.7 on 2025-10-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_candidateprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture image file', null=True, upload_to='profile_pictures/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_picture_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
