# Generated by Django 5.2.7 on 2025-10-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_candidateprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateskill',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='candidateskill',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order within category'),
        ),
        migrations.AddIndex(
            model_name='candidateskill',
            index=models.Index(fields=['candidate', 'order'], name='core_candid_candida_b6abd3_idx'),
        ),
    ]
