# Generated by Django 5.2.7 on 2025-11-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_content_type_document_default_for_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyresearch',
            name='company_values',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companyresearch',
            name='competitors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='companyresearch',
            name='executives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companyresearch',
            name='products',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companyresearch',
            name='social_media',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
