# Generated by Django 5.2.8 on 2025-11-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_uc_063_automated_company_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobentry',
            name='preferred_skills',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred/nice-to-have skills'),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='required_skills',
            field=models.JSONField(blank=True, default=list, help_text='List of required skills for this job'),
        ),
    ]
