# Generated by Django 5.2.7 on 2025-10-25 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_candidateskill_options_candidateskill_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='education',
            name='currently_enrolled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='gpa_private',
            field=models.BooleanField(default=False, help_text='If true, GPA is hidden from shared/public views'),
        ),
        migrations.AlterField(
            model_name='education',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='core.candidateprofile'),
        ),
    ]
