# Generated by Django 5.2.8 on 2025-11-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_skills_to_job_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobentry',
            name='preferred_skills',
        ),
        migrations.RemoveField(
            model_name='jobentry',
            name='required_skills',
        ),
    ]
