# Generated by Django 5.2.8 on 2025-11-09 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_skills_to_job_entry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coverlettertemplate',
            new_name='core_coverl_templat_4665ba_idx',
            old_name='core_coverl_templat_7b4c6b_idx',
        ),
        migrations.RenameIndex(
            model_name='coverlettertemplate',
            new_name='core_coverl_industr_118a37_idx',
            old_name='core_coverl_industr_2f8e9a_idx',
        ),
        migrations.RenameIndex(
            model_name='coverlettertemplate',
            new_name='core_coverl_owner_i_3e4d95_idx',
            old_name='core_coverl_owner_i_1a3c4d_idx',
        ),
        migrations.RenameIndex(
            model_name='coverlettertemplate',
            new_name='core_coverl_is_shar_6d23c7_idx',
            old_name='core_coverl_is_shar_5e6f7g_idx',
        ),
        migrations.RemoveField(
            model_name='jobentry',
            name='preferred_skills',
        ),
        migrations.RemoveField(
            model_name='jobentry',
            name='required_skills',
        ),
    ]
