# Generated by Django 5.2.8 on 2025-11-09 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_jobentry_preferred_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=220)),
                ('location', models.CharField(max_length=160)),
                ('experience_level', models.CharField(blank=True, choices=[('entry', 'Entry Level (0-2 years)'), ('mid', 'Mid Level (3-5 years)'), ('senior', 'Senior Level (6-10 years)'), ('lead', 'Lead/Principal (10+ years)'), ('executive', 'Executive')], max_length=20)),
                ('company_size', models.CharField(blank=True, choices=[('startup', 'Startup (1-50)'), ('small', 'Small (51-200)'), ('medium', 'Medium (201-1000)'), ('large', 'Large (1001-5000)'), ('enterprise', 'Enterprise (5000+)')], max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_median', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonus_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_comp_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_comp_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('benefits', models.JSONField(blank=True, default=dict, help_text='Benefits package details')),
                ('market_trend', models.CharField(blank=True, help_text='up, down, stable', max_length=20)),
                ('percentile_25', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentile_75', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('negotiation_leverage', models.CharField(blank=True, help_text='high, medium, low', max_length=20)),
                ('recommended_ask', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('negotiation_tips', models.TextField(blank=True)),
                ('user_current_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_source', models.CharField(choices=[('glassdoor', 'Glassdoor'), ('payscale', 'PayScale'), ('indeed', 'Indeed'), ('linkedin', 'LinkedIn'), ('levels_fyi', 'Levels.fyi'), ('manual', 'Manual Entry'), ('aggregated', 'Aggregated Data')], default='aggregated', max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('sample_size', models.PositiveIntegerField(blank=True, help_text='Number of data points', null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='0-1 confidence', max_digits=3, null=True)),
                ('company_comparisons', models.JSONField(blank=True, default=list, help_text='List of company salary comparisons')),
                ('historical_data', models.JSONField(blank=True, default=list, help_text='Historical salary trends')),
                ('research_notes', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_research', to='core.jobentry')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job', '-created_at'], name='core_salary_job_id_e43a02_idx'), models.Index(fields=['position_title', 'location'], name='core_salary_positio_e0d28c_idx'), models.Index(fields=['experience_level'], name='core_salary_experie_73ffd4_idx')],
            },
        ),
    ]
