# Generated by Django 5.2.8 on 2025-11-10 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_uc_067_salary_research'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewInsightsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=220)),
                ('company_name', models.CharField(max_length=220)),
                ('insights_data', models.JSONField(help_text='Complete interview insights JSON including process, questions, tips, checklist')),
                ('generated_by', models.CharField(choices=[('ai', 'AI Generated'), ('template', 'Template Based')], default='ai', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True, help_text='Set to False to force regeneration')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_insights_cache', to='core.jobentry')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['job', 'is_valid'], name='core_interv_job_id_4e9d30_idx'), models.Index(fields=['company_name', 'job_title'], name='core_interv_company_f9b693_idx')],
            },
        ),
    ]
