# Generated by Django 5.2 on 2025-10-26 00:30
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_account_deletion_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('role', models.CharField(blank=True, max_length=160)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project_url', models.URLField(blank=True)),
                ('team_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('collaboration_details', models.TextField(blank=True)),
                ('outcomes', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(blank=True, help_text='Project type categorization', max_length=120)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('planned', 'Planned')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.candidateprofile')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='skills_used',
            field=models.ManyToManyField(blank=True, related_name='used_in_projects', to='core.skill'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['candidate', '-start_date'], name='core_projec_candidat_5d5f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmedia',
            index=models.Index(fields=['project', 'order'], name='core_projec_project__6a3f7f_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='core_projec_status_0a791b_idx'),
        ),
    ]
