# Generated by Django 5.2.7 on 2025-10-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_uc031_projects'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='project',
            new_name='core_projec_candida_80e864_idx',
            old_name='core_projec_candidat_5d5f0a_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='core_projec_status_2020cc_idx',
            old_name='core_projec_status_0a791b_idx',
        ),
        migrations.RenameIndex(
            model_name='projectmedia',
            new_name='core_projec_project_486b1a_idx',
            old_name='core_projec_project__6a3f7f_idx',
        ),
    ]
