# Generated by Django 5.2 on 2025-10-26
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_uc031_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Custom display order for portfolio'),
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['display_order', '-start_date', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['candidate', 'display_order'], name='core_projec_candidat_orde_idx'),
        ),
    ]
