# Generated by Django 5.2.8 on 2025-11-10 02:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_interview_insights_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('provider', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('resource_type', models.CharField(choices=[('course', 'Online Course'), ('tutorial', 'Tutorial'), ('documentation', 'Documentation'), ('video', 'Video'), ('book', 'Book'), ('practice', 'Practice Platform'), ('certification', 'Certification')], default='course', max_length=20)),
                ('cost_type', models.CharField(choices=[('free', 'Free'), ('freemium', 'Freemium'), ('paid', 'Paid')], default='free', max_length=20)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('difficulty_level', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('credibility_score', models.IntegerField(default=50, help_text='0-100 internal quality score')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_resources', to='core.skill')),
            ],
            options={
                'ordering': ['-credibility_score', '-rating', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SkillDevelopmentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('practice', 'Practice Session'), ('course', 'Course Progress'), ('project', 'Project Work'), ('certification', 'Certification Earned'), ('review', 'Review/Refresh')], default='practice', max_length=20)),
                ('hours_spent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('progress_percent', models.IntegerField(default=0, help_text='0-100 completion percentage')),
                ('notes', models.TextField(blank=True)),
                ('activity_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to='core.candidateprofile')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to='core.jobentry')),
                ('learning_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.learningresource')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='core.skill')),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='SkillGapAnalysisCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=220)),
                ('company_name', models.CharField(max_length=220)),
                ('analysis_data', models.JSONField(help_text='Complete skills gap analysis including skills, gaps, resources, learning paths')),
                ('source', models.CharField(choices=[('requirements', 'Job Requirements'), ('parsed', 'Parsed Description'), ('ai', 'AI Analysis')], default='parsed', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True, help_text='Set to False to force regeneration')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_gap_cache', to='core.jobentry')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['skill', 'is_active', '-credibility_score'], name='core_learni_skill_i_fdaa21_idx'),
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['difficulty_level'], name='core_learni_difficu_39dbe7_idx'),
        ),
        migrations.AddIndex(
            model_name='skilldevelopmentprogress',
            index=models.Index(fields=['candidate', 'skill', '-activity_date'], name='core_skilld_candida_00d19a_idx'),
        ),
        migrations.AddIndex(
            model_name='skilldevelopmentprogress',
            index=models.Index(fields=['job', '-activity_date'], name='core_skilld_job_id_a2cdab_idx'),
        ),
        migrations.AddIndex(
            model_name='skillgapanalysiscache',
            index=models.Index(fields=['job', 'is_valid'], name='core_skillg_job_id_b27076_idx'),
        ),
        migrations.AddIndex(
            model_name='skillgapanalysiscache',
            index=models.Index(fields=['job_title'], name='core_skillg_job_tit_79a6c6_idx'),
        ),
    ]
