# Generated by Django 5.2.7 on 2025-10-28 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20251027_0000'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='project',
            new_name='core_projec_candida_6564ee_idx',
            old_name='core_projec_candidat_orde_idx',
        ),
    ]
