# Generated by Django 5.2.8 on 2025-11-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_core_coverl_templat_7b4c6b_idx_core_coverl_templat_4665ba_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverlettertemplate',
            name='original_file_content',
            field=models.BinaryField(blank=True, help_text='Original file content for Word documents', null=True),
        ),
        migrations.AddField(
            model_name='coverlettertemplate',
            name='original_file_type',
            field=models.CharField(blank=True, help_text='Original file extension (txt, docx)', max_length=10),
        ),
        migrations.AddField(
            model_name='coverlettertemplate',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original uploaded filename', max_length=255),
        ),
    ]
