# Generated by Django 5.2.8 on 2025-11-10 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_original_file_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMatchAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('skills_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('experience_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('education_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('match_data', models.JSONField(help_text='Detailed analysis including strengths, gaps, and recommendations')),
                ('user_weights', models.JSONField(default=dict, help_text='Custom category weights (skills, experience, education)')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField(default=True, help_text='False if analysis is outdated due to profile changes')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='core.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_analysis', to='core.jobentry')),
            ],
            options={
                'ordering': ['-overall_score', '-generated_at'],
                'indexes': [models.Index(fields=['candidate', '-overall_score'], name='core_jobmat_candida_eb5438_idx'), models.Index(fields=['job', '-overall_score'], name='core_jobmat_job_id_8122d2_idx'), models.Index(fields=['candidate', '-generated_at'], name='core_jobmat_candida_3bcebf_idx'), models.Index(fields=['-overall_score'], name='core_jobmat_overall_7767a0_idx')],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
