# Generated migration for UC-052: Resume Version Management

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_original_file_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_name', models.CharField(help_text="Descriptive name for this resume version (e.g., 'Software Engineer - Tech Companies')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional notes about what makes this version unique')),
                ('content', models.JSONField(help_text='Resume content in structured format (sections, experiences, skills, etc.)')),
                ('latex_content', models.TextField(blank=True, help_text='LaTeX source if generated by AI')),
                ('is_default', models.BooleanField(default=False, help_text='Mark as the master/default resume version')),
                ('is_archived', models.BooleanField(default=False, help_text='Archive old versions without deleting them')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by_ai', models.BooleanField(default=False)),
                ('generation_params', models.JSONField(blank=True, default=dict, help_text='AI generation parameters (tone, variation, etc.)')),
                ('applications', models.ManyToManyField(blank=True, help_text='Applications that used this resume version', related_name='resume_versions_used', to='core.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_versions', to='core.candidateprofile')),
                ('created_from', models.ForeignKey(blank=True, help_text='Parent version this was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='core.resumeversion')),
                ('source_job', models.ForeignKey(blank=True, help_text='Job this version was tailored for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_versions', to='core.jobopportunity')),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resumeversion',
            index=models.Index(fields=['candidate', '-created_at'], name='core_resume_candida_b8c9f2_idx'),
        ),
        migrations.AddIndex(
            model_name='resumeversion',
            index=models.Index(fields=['candidate', 'is_default'], name='core_resume_candida_6a4d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='resumeversion',
            index=models.Index(fields=['candidate', 'is_archived'], name='core_resume_candida_7f2b5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='resumeversion',
            constraint=models.UniqueConstraint(fields=('candidate', 'version_name'), name='unique_version_name_per_candidate'),
        ),
    ]
