# Generated by Django 5.2.8 on 2025-11-11 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_jobmatchanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('phone', 'Phone Interview'), ('video', 'Video Interview'), ('in_person', 'In-Person Interview'), ('assessment', 'Technical Assessment'), ('group', 'Group Interview')], max_length=20)),
                ('scheduled_at', models.DateTimeField(db_index=True, help_text='Interview date and time')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Expected duration in minutes')),
                ('location', models.CharField(blank=True, help_text='Physical address for in-person interviews', max_length=500)),
                ('meeting_link', models.URLField(blank=True, help_text='Video conference link (Zoom, Teams, etc.)', max_length=500)),
                ('interviewer_name', models.CharField(blank=True, max_length=200)),
                ('interviewer_email', models.EmailField(blank=True, max_length=254)),
                ('interviewer_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('', 'Not Yet Recorded'), ('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor'), ('rejected', 'Rejected'), ('withdrew', 'Withdrew Application')], default='', max_length=20)),
                ('feedback_notes', models.TextField(blank=True, help_text='Post-interview notes and feedback')),
                ('preparation_notes', models.TextField(blank=True, help_text='Preparation notes and research')),
                ('questions_to_ask', models.TextField(blank=True, help_text='Questions prepared for interviewer')),
                ('show_24h_reminder', models.BooleanField(default=False, help_text='Show 24h reminder in app')),
                ('show_1h_reminder', models.BooleanField(default=False, help_text='Show 1h reminder in app')),
                ('reminder_24h_dismissed', models.BooleanField(default=False)),
                ('reminder_1h_dismissed', models.BooleanField(default=False)),
                ('original_datetime', models.DateTimeField(blank=True, help_text='Original scheduled time if rescheduled', null=True)),
                ('rescheduled_reason', models.CharField(blank=True, max_length=500)),
                ('cancelled_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='core.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='core.jobentry')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewPreparationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('research_company', 'Research Company'), ('review_job', 'Review Job Description'), ('prepare_questions', 'Prepare Questions'), ('practice_answers', 'Practice Common Answers'), ('review_resume', 'Review Your Resume'), ('prepare_examples', 'Prepare STAR Examples'), ('research_interviewer', 'Research Interviewer'), ('test_tech', 'Test Technology (for video)'), ('plan_route', 'Plan Route (for in-person)'), ('prepare_materials', 'Prepare Materials'), ('custom', 'Custom Task')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_tasks', to='core.interviewschedule')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='interviewschedule',
            index=models.Index(fields=['candidate', 'scheduled_at'], name='core_interv_candida_146696_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewschedule',
            index=models.Index(fields=['job', 'scheduled_at'], name='core_interv_job_id_23b9b9_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewschedule',
            index=models.Index(fields=['candidate', 'status'], name='core_interv_candida_db3888_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewschedule',
            index=models.Index(fields=['scheduled_at', 'status'], name='core_interv_schedul_47956f_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewschedule',
            index=models.Index(fields=['show_24h_reminder', 'show_1h_reminder'], name='core_interv_show_24_c4f69e_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewpreparationtask',
            index=models.Index(fields=['interview', 'is_completed'], name='core_interv_intervi_eacbc9_idx'),
        ),
    ]
