# Generated by Django 5.2.7 on 2025-10-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_backfill_useraccounts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='useraccount',
            new_name='core_userac_email_2300c3_idx',
            old_name='core_userac_email_7b3a29_idx',
        ),
    ]
