# Generated by Django 4.2 on 2025-11-04
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_core_userac_email_7b3a29_idx_core_userac_email_2300c3_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('company_name', models.CharField(max_length=180)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('posting_url', models.URLField(blank=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('job_type', models.CharField(choices=[('ft', 'Full-time'), ('pt', 'Part-time'), ('contract', 'Contract'), ('intern', 'Internship'), ('temp', 'Temporary')], default='ft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_entries', to='core.candidateprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='jobentry',
            index=models.Index(fields=['candidate', '-updated_at'], name='core_jobent_candida_b1e1c4_idx'),
        ),
        migrations.AddIndex(
            model_name='jobentry',
            index=models.Index(fields=['job_type'], name='core_jobent_job_typ_7fffb9_idx'),
        ),
        migrations.AddIndex(
            model_name='jobentry',
            index=models.Index(fields=['industry'], name='core_jobent_industr_5a9f0b_idx'),
        ),
    ]
