# Generated by Django 5.2.8 on 2025-11-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_resume_version_changes'),
        ('core', '0014_uc071_interview_scheduling'),
    ]

    operations = [
    ]
