# Generated by Django 5.2.8 on 2025-11-10 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_automation_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User-friendly rule name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of what this rule does')),
                ('trigger_type', models.CharField(choices=[('new_job', 'New Job Added'), ('match_score', 'Match Score Threshold'), ('deadline_approaching', 'Deadline Approaching'), ('status_change', 'Application Status Change'), ('time_based', 'Time-Based Schedule')], max_length=30)),
                ('trigger_conditions', models.JSONField(default=dict, help_text='Conditions that activate this rule')),
                ('action_type', models.CharField(choices=[('generate_package', 'Generate Application Package'), ('schedule_application', 'Schedule Application Submission'), ('send_followup', 'Send Follow-up Reminder'), ('update_status', 'Update Application Status'), ('create_reminder', 'Create Reminder')], max_length=30)),
                ('action_parameters', models.JSONField(default=dict, help_text='Parameters for the action to take')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='Execution priority (1=highest, 10=lowest)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('execution_count', models.PositiveIntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='core.candidateprofile')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Checklist name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('auto_update_enabled', models.BooleanField(default=True, help_text='Whether to auto-update based on application progress')),
                ('template_used', models.CharField(blank=True, help_text='Template this checklist was based on', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_checklists', to='core.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_checklists', to='core.jobentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_url', models.URLField(blank=True, help_text='Link to portfolio or additional materials')),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('failed', 'Generation Failed')], default='generating', max_length=20)),
                ('generation_parameters', models.JSONField(default=dict, help_text='Parameters used for generation')),
                ('match_score', models.FloatField(blank=True, help_text='Job match score at time of generation', null=True)),
                ('resume_template', models.CharField(blank=True, help_text='Resume template used', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_packages', to='core.candidateprofile')),
                ('cover_letter_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_letter_packages', to='core.document')),
                ('cover_letter_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coverlettertemplate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_packages', to='core.jobentry')),
                ('resume_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_packages', to='core.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('bulk_apply', 'Bulk Apply'), ('status_update', 'Status Update'), ('package_generation', 'Package Generation'), ('reminder_creation', 'Reminder Creation'), ('export', 'Data Export'), ('archive', 'Archive Jobs')], max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('parameters', models.JSONField(default=dict, help_text='Operation parameters and settings')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('processed_items', models.PositiveIntegerField(default=0)),
                ('successful_items', models.PositiveIntegerField(default=0)),
                ('failed_items', models.PositiveIntegerField(default=0)),
                ('results', models.JSONField(default=dict, help_text='Operation results and summary')),
                ('error_log', models.JSONField(default=list, help_text='List of errors encountered')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_operations', to='core.candidateprofile')),
                ('target_jobs', models.ManyToManyField(related_name='bulk_operations', to='core.jobentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('auto_complete_trigger', models.CharField(blank=True, help_text='Event that auto-completes this task', max_length=100)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by_automation', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.applicationchecklist')),
                ('depends_on', models.ManyToManyField(blank=True, related_name='dependents', to='core.checklisttask')),
            ],
            options={
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('application_followup', 'Application Follow-up'), ('interview_followup', 'Interview Follow-up'), ('offer_response', 'Offer Response'), ('thank_you', 'Thank You Note'), ('status_inquiry', 'Status Inquiry')], max_length=30)),
                ('subject', models.CharField(help_text='Email subject or reminder title', max_length=200)),
                ('message_template', models.TextField(help_text='Template message with placeholders')),
                ('scheduled_datetime', models.DateTimeField(help_text='When to send the reminder')),
                ('interval_days', models.PositiveSmallIntegerField(blank=True, help_text='Days between reminders for recurring', null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('max_occurrences', models.PositiveSmallIntegerField(default=1, help_text='Maximum times to send')),
                ('occurrence_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('dismissed', 'Dismissed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('response_received', models.BooleanField(default=False)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_reminders', to='core.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_reminders', to='core.jobentry')),
            ],
            options={
                'ordering': ['scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField(help_text='When to submit the application')),
                ('timezone', models.CharField(default='UTC', help_text="User's timezone for scheduling", max_length=50)),
                ('submission_method', models.CharField(default='email', help_text='How to submit (email, portal, etc.)', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('submitted', 'Submitted'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='Submission priority (1=highest)')),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('submission_parameters', models.JSONField(default=dict, help_text='Parameters for submission')),
                ('submission_result', models.JSONField(default=dict, help_text='Result of submission attempt')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_submissions', to='core.applicationpackage')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_submissions', to='core.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_submissions', to='core.jobentry')),
            ],
            options={
                'ordering': ['scheduled_datetime', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('context', models.JSONField(default=dict, help_text='Additional context data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('automation_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='core.applicationautomationrule')),
                ('bulk_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bulkoperation')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='core.candidateprofile')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.jobentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AutomationRule',
        ),
        migrations.AddIndex(
            model_name='applicationautomationrule',
            index=models.Index(fields=['candidate', 'is_active'], name='core_applic_candida_84450a_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationautomationrule',
            index=models.Index(fields=['trigger_type', 'is_active'], name='core_applic_trigger_8d58f2_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationchecklist',
            index=models.Index(fields=['candidate', 'status'], name='core_applic_candida_97a0be_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationchecklist',
            index=models.Index(fields=['job', 'status'], name='core_applic_job_id_ff6faa_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationpackage',
            index=models.Index(fields=['candidate', 'status'], name='core_applic_candida_5f0971_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationpackage',
            index=models.Index(fields=['job', 'created_at'], name='core_applic_job_id_db9115_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkoperation',
            index=models.Index(fields=['candidate', 'status'], name='core_bulkop_candida_3cb9b9_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkoperation',
            index=models.Index(fields=['operation_type', 'status'], name='core_bulkop_operati_4b4e57_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttask',
            index=models.Index(fields=['checklist', 'status'], name='core_checkl_checkli_86699f_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttask',
            index=models.Index(fields=['due_date', 'status'], name='core_checkl_due_dat_192db6_idx'),
        ),
        migrations.AddIndex(
            model_name='followupreminder',
            index=models.Index(fields=['candidate', 'status'], name='core_follow_candida_fb1693_idx'),
        ),
        migrations.AddIndex(
            model_name='followupreminder',
            index=models.Index(fields=['scheduled_datetime', 'status'], name='core_follow_schedul_532f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledsubmission',
            index=models.Index(fields=['candidate', 'status'], name='core_schedu_candida_0e7889_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledsubmission',
            index=models.Index(fields=['scheduled_datetime', 'status'], name='core_schedu_schedul_3aabb0_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowautomationlog',
            index=models.Index(fields=['candidate', 'level'], name='core_workfl_candida_e4e6c5_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowautomationlog',
            index=models.Index(fields=['automation_rule', 'created_at'], name='core_workfl_automat_84375e_idx'),
        ),
    ]
