# Generated by Django 5.2.7 on 2025-11-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_jobentry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobentry',
            new_name='core_jobent_candida_ca8b22_idx',
            old_name='core_jobent_candida_b1e1c4_idx',
        ),
        migrations.RenameIndex(
            model_name='jobentry',
            new_name='core_jobent_job_typ_4f5186_idx',
            old_name='core_jobent_job_typ_7fffb9_idx',
        ),
        migrations.RenameIndex(
            model_name='jobentry',
            new_name='core_jobent_industr_b37f74_idx',
            old_name='core_jobent_industr_5a9f0b_idx',
        ),
        migrations.AddField(
            model_name='jobentry',
            name='application_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='hiring_manager_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='hiring_manager_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='interview_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='personal_notes',
            field=models.TextField(blank=True, help_text='Unlimited text for personal observations'),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='recruiter_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='recruiter_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='recruiter_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='salary_negotiation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
