# Generated by Django 5.2.8 on 2025-11-11 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_uc_052_resume_version_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeVersionChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('create', 'Created'), ('edit', 'Edited'), ('merge', 'Merged'), ('duplicate', 'Duplicated')], default='edit', max_length=50)),
                ('changes', models.JSONField(help_text='Details of what changed (field-level diffs)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='resumeversion',
            new_name='core_resume_candida_2a7abf_idx',
            old_name='core_resume_candida_b8c9f2_idx',
        ),
        migrations.RenameIndex(
            model_name='resumeversion',
            new_name='core_resume_candida_12f2fc_idx',
            old_name='core_resume_candida_6a4d3e_idx',
        ),
        migrations.RenameIndex(
            model_name='resumeversion',
            new_name='core_resume_candida_89f237_idx',
            old_name='core_resume_candida_7f2b5c_idx',
        ),
        migrations.AddField(
            model_name='resumeversionchange',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='core.resumeversion'),
        ),
        migrations.AddIndex(
            model_name='resumeversionchange',
            index=models.Index(fields=['version', '-created_at'], name='core_resume_version_1f1fcc_idx'),
        ),
    ]
