# Generated by Django 5.2.7 on 2025-11-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_uc038_fields_to_jobentry'),
        ('core', '0016_merge_20251104_0000'),
    ]

    operations = [
    ]
