# Generated by Django 5.2.7 on 2025-11-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20251105_1553'),
    ]

    operations = [
        # Index renames already applied in database - skip to avoid errors
        # migrations.RenameIndex(
        #     model_name='jobentry',
        #     new_name='core_jobent_candida_4e0dd2_idx',
        #     old_name='core_jobentr_candida_6a6926_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='jobstatuschange',
        #     new_name='core_jobsta_job_id_456425_idx',
        #     old_name='core_jobstat_job_id__1a3daa_idx',
        # ),
        migrations.AlterField(
            model_name='education',
            name='degree_type',
            field=models.CharField(choices=[('hs', 'High School'), ('aa', 'Associate'), ('ba', 'Bachelor'), ('ma', 'Master'), ('phd', 'PhD'), ('cert', 'Certificate'), ('boot', 'Bootcamp')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobstatuschange',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
