# Generated by Django 5.2.8 on 2025-11-10 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_jobmatchanalysis'),
    ]

    operations = [
    ]
