# Generated by Django 5.2.7 on 2025-11-06 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_jobentry_deadline_notices'),
        ('core', '0018_rename_core_jobentr_candida_6a6926_idx_core_jobent_candida_4e0dd2_idx_and_more'),
    ]

    operations = [
    ]
