# Generated by Django 5.2.7 on 2025-11-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20251106_0124'),
    ]

    operations = [
        # Index renames already applied in database - skip to avoid errors
        # migrations.RenameIndex(
        #     model_name='jobentry',
        #     new_name='core_jobent_candida_ca8b22_idx',
        #     old_name='core_jobent_candida_b1e1c4_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='jobentry',
        #     new_name='core_jobent_job_typ_4f5186_idx',
        #     old_name='core_jobent_job_typ_7fffb9_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='jobentry',
        #     new_name='core_jobent_industr_b37f74_idx',
        #     old_name='core_jobent_industr_5a9f0b_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='jobentry',
        #     new_name='core_jobent_candida_4e0dd2_idx',
        #     old_name='core_jobentr_candida_6a6926_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='jobstatuschange',
        #     new_name='core_jobsta_job_id_456425_idx',
        #     old_name='core_jobstat_job_id__1a3daa_idx',
        # ),
        migrations.AddField(
            model_name='jobentry',
            name='archive_reason',
            field=models.CharField(blank=True, choices=[('completed', 'Position Filled/Completed'), ('not_interested', 'No Longer Interested'), ('rejected', 'Application Rejected'), ('expired', 'Posting Expired'), ('auto', 'Auto-archived'), ('other', 'Other')], max_length=100),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='jobentry',
            index=models.Index(fields=['candidate', 'is_archived'], name='core_jobent_candida_036601_idx'),
        ),
    ]
