# Generated by Django 5.2.7 on 2025-11-06 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20251106_0333'),
        ('core', '0019_merge_20251106_0124'),
    ]

    operations = [
    ]
