# Generated by Django 5.2.8 on 2025-11-11 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_workflow_automation_models'),
    ]
    # Duplicate CreateModel operations for InterviewSchedule/InterviewPreparationTask
    # were previously present here (likely from a merge / migration reordering).
    # This migration is intentionally a no-op to avoid re-creating models that are
    # already introduced by an earlier migration (e.g. 0018_uc071_interview_scheduling).
    operations = []
