# Generated by Django 5.2.7 on 2025-11-06 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_uc045_job_archiving'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobentry',
            new_name='core_jobent_candida_ca8b22_idx',
            old_name='core_jobent_candida_b1e1c4_idx',
        ),
        migrations.RenameIndex(
            model_name='jobentry',
            new_name='core_jobent_job_typ_4f5186_idx',
            old_name='core_jobent_job_typ_7fffb9_idx',
        ),
        migrations.RenameIndex(
            model_name='jobentry',
            new_name='core_jobent_industr_b37f74_idx',
            old_name='core_jobent_industr_5a9f0b_idx',
        ),
        migrations.RenameIndex(
            model_name='jobentry',
            new_name='core_jobent_candida_4e0dd2_idx',
            old_name='core_jobentr_candida_6a6926_idx',
        ),
        migrations.RenameIndex(
            model_name='jobstatuschange',
            new_name='core_jobsta_job_id_456425_idx',
            old_name='core_jobstat_job_id__1a3daa_idx',
        ),
    ]
