# Generated by Django 5.2.8 on 2025-11-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_applicationautomationrule_action_type_and_more'),
        ('core', '0018_uc071_interview_scheduling'),
    ]

    operations = [
    ]
