# Generated by Django 5.2.7 on 2025-11-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20251106_0459'),
        ('core', '0021_rename_core_jobent_candida_b1e1c4_idx_core_jobent_candida_ca8b22_idx_and_more'),
    ]

    operations = [
    ]
