# Generated by Django 5.2.8 on 2025-11-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_merge_20251111_0841'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE core_applicationautomationrule RENAME COLUMN execution_count TO trigger_count;",
            reverse_sql="ALTER TABLE core_applicationautomationrule RENAME COLUMN trigger_count TO execution_count;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_applicationautomationrule RENAME COLUMN last_executed TO last_triggered_at;",
            reverse_sql="ALTER TABLE core_applicationautomationrule RENAME COLUMN last_triggered_at TO last_executed;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_applicationautomationrule DROP COLUMN IF EXISTS priority;",
            reverse_sql=""
        ),
    ]
