# Generated by Django 5.2.8 on 2025-11-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20251111_0842'),
        ('core', '0024_ensure_coverlettertemplate_table'),
    ]

    operations = [
    ]
