# Generated by Django 5.2.8 on 2025-11-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_merge_20251111_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ai_generation_tone',
            field=models.CharField(blank=True, help_text='AI generation tone (e.g., formal, analytical, warm)', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='ai_generation_params',
            field=models.JSONField(blank=True, default=dict, help_text='AI generation parameters for analytics'),
        ),
    ]
