# Generated by Django 5.2.8 on 2025-11-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_b_uc_052_resume_sharing_feedback'),
        ('core', '0026_add_document_analytics_fields'),
    ]

    operations = [
    ]
