# Generated by Django 5.2.8 on 2025-11-11 21:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


def add_field_if_not_exists(apps, schema_editor, model_name, field_name, field):
    """Helper function to add a field only if it doesn't already exist"""
    table_name = f'core_{model_name.lower()}'
    connection = schema_editor.connection

    if not column_exists(connection, table_name, field_name):
        schema_editor.add_field(
            apps.get_model('core', model_name),
            field_name,
            field.clone()
        )


def safe_add_last_triggered_at(apps, schema_editor):
    """Add last_triggered_at field if it doesn't exist"""
    field = models.DateTimeField(blank=True, help_text='When this rule was last executed', null=True)
    add_field_if_not_exists(apps, schema_editor, 'ApplicationAutomationRule', 'last_triggered_at', field)


def safe_add_trigger_count(apps, schema_editor):
    """Add trigger_count field if it doesn't exist"""
    field = models.PositiveIntegerField(default=0, help_text='How many times this rule has been triggered')
    add_field_if_not_exists(apps, schema_editor, 'ApplicationAutomationRule', 'trigger_count', field)


def reverse_noop(apps, schema_editor):
    """No-op for reverse migration"""
    pass


def clone_model_with_uuid_pk(model_class, app_registry):
    """Create a temporary model definition that matches the given model but swaps the PK to UUID."""
    meta_attrs = {
        'app_label': model_class._meta.app_label,
        'db_table': model_class._meta.db_table,
        'managed': True,
        'apps': app_registry,
    }
    if model_class._meta.ordering:
        meta_attrs['ordering'] = model_class._meta.ordering
    if model_class._meta.unique_together:
        meta_attrs['unique_together'] = model_class._meta.unique_together
    index_together = getattr(model_class._meta, 'index_together', None)
    if index_together:
        meta_attrs['index_together'] = index_together
    if model_class._meta.constraints:
        meta_attrs['constraints'] = [constraint.clone() for constraint in model_class._meta.constraints]
    if model_class._meta.indexes:
        meta_attrs['indexes'] = [index.clone() for index in model_class._meta.indexes]

    Meta = type('Meta', (), meta_attrs)
    attrs = {'__module__': model_class.__module__, 'Meta': Meta}

    for field in model_class._meta.local_fields:
        if field.primary_key:
            attrs[field.name] = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
        else:
            attrs[field.name] = field.clone()

    return type(f'Temp{model_class.__name__}', (models.Model,), attrs)


def recreate_table_with_uuid_pk_sqlite(apps, schema_editor, model_name):
    """SQLite helper to rebuild a table with a UUID primary key while preserving other columns."""
    model_class = apps.get_model('core', model_name)
    temp_model = clone_model_with_uuid_pk(model_class, apps)
    non_pk_fields = [field for field in model_class._meta.local_fields if not field.primary_key]
    attnames = [field.attname for field in non_pk_fields]
    rows = list(model_class.objects.using(schema_editor.connection.alias).values_list(*attnames))

    connection = schema_editor.connection
    with connection.constraint_checks_disabled():
        schema_editor.delete_model(model_class)
        schema_editor.create_model(temp_model)

    if not rows:
        return

    column_sql = [
        schema_editor.quote_name('id'),
        *[schema_editor.quote_name(field.column) for field in non_pk_fields],
    ]
    placeholders = ', '.join('?' for _ in column_sql)
    insert_sql = f"INSERT INTO {schema_editor.quote_name(model_class._meta.db_table)} ({', '.join(column_sql)}) VALUES ({placeholders})"

    with connection.cursor() as cursor:
        for row in rows:
            cursor.execute(insert_sql, [str(uuid.uuid4())] + list(row))


def convert_id_to_uuid_applicationautomationrule(apps, schema_editor):
    """Convert ApplicationAutomationRule id from BigInt to UUID."""
    if schema_editor.connection.vendor == 'sqlite':
        recreate_table_with_uuid_pk_sqlite(apps, schema_editor, 'ApplicationAutomationRule')
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE core_applicationautomationrule 
            DROP COLUMN id CASCADE;
        """)
        cursor.execute("""
            ALTER TABLE core_applicationautomationrule 
            ADD COLUMN id UUID PRIMARY KEY DEFAULT gen_random_uuid();
        """)


def convert_id_to_uuid_applicationpackage(apps, schema_editor):
    """Convert ApplicationPackage id from BigInt to UUID."""
    if schema_editor.connection.vendor == 'sqlite':
        recreate_table_with_uuid_pk_sqlite(apps, schema_editor, 'ApplicationPackage')
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE core_applicationpackage 
            DROP COLUMN id CASCADE;
        """)
        cursor.execute("""
            ALTER TABLE core_applicationpackage 
            ADD COLUMN id UUID PRIMARY KEY DEFAULT gen_random_uuid();
        """)


def column_exists(connection, table_name, column_name):
    """Return True if the given column exists on the table for the active DB backend."""
    with connection.cursor() as cursor:
        if connection.vendor == 'sqlite':
            cursor.execute(f"PRAGMA table_info('{table_name}')")
            return any(row[1] == column_name for row in cursor.fetchall())
        cursor.execute(
            """
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = %s AND column_name = %s
            """,
            [table_name, column_name],
        )
        return cursor.fetchone() is not None


def drop_old_automationrule_columns(apps, schema_editor):
    """Drop legacy ApplicationAutomationRule columns if present."""
    table_name = 'core_applicationautomationrule'
    connection = schema_editor.connection
    for column in ['execution_count', 'last_executed', 'priority']:
        if column_exists(connection, table_name, column):
            schema_editor.execute(
                f'ALTER TABLE {schema_editor.quote_name(table_name)} '
                f'DROP COLUMN {schema_editor.quote_name(column)}'
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_merge_20251111_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('weekly_applications', 'Weekly Applications'), ('response_rate', 'Response Rate Target'), ('interviews_per_month', 'Interviews per Month')], default='weekly_applications', max_length=30)),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Target number (e.g., 5 applications per week)', max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, help_text='Current progress toward goal', max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this goal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=200)),
                ('trigger_event', models.CharField(max_length=50)),
                ('trigger_conditions', models.JSONField(default=dict)),
                ('action_type', models.CharField(max_length=50)),
                ('action_config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('times_triggered', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='applicationchecklist',
            name='core_applic_candida_97a0be_idx',
        ),
        migrations.RemoveIndex(
            model_name='applicationchecklist',
            name='core_applic_job_id_ff6faa_idx',
        ),
        migrations.RemoveIndex(
            model_name='checklisttask',
            name='core_checkl_checkli_86699f_idx',
        ),
        migrations.RemoveIndex(
            model_name='bulkoperation',
            name='core_bulkop_candida_3cb9b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowautomationlog',
            name='core_workfl_candida_e4e6c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowautomationlog',
            name='core_workfl_automat_84375e_idx',
        ),
        migrations.RemoveIndex(
            model_name='followupreminder',
            name='core_follow_candida_fb1693_idx',
        ),
        migrations.RemoveIndex(
            model_name='scheduledsubmission',
            name='core_schedu_candida_0e7889_idx',
        ),
        migrations.RemoveField(
            model_name='applicationchecklist',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='applicationchecklist',
            name='job',
        ),
        migrations.RemoveField(
            model_name='checklisttask',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='bulkoperation',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='bulkoperation',
            name='target_jobs',
        ),
        migrations.RemoveField(
            model_name='workflowautomationlog',
            name='bulk_operation',
        ),
        migrations.RemoveField(
            model_name='checklisttask',
            name='depends_on',
        ),
        migrations.RemoveField(
            model_name='followupreminder',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='followupreminder',
            name='job',
        ),
        migrations.RemoveField(
            model_name='scheduledsubmission',
            name='application_package',
        ),
        migrations.RemoveField(
            model_name='scheduledsubmission',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='scheduledsubmission',
            name='job',
        ),
        migrations.RemoveField(
            model_name='workflowautomationlog',
            name='automation_rule',
        ),
        migrations.RemoveField(
            model_name='workflowautomationlog',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='workflowautomationlog',
            name='job',
        ),
        migrations.AlterModelOptions(
            name='applicationautomationrule',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='applicationpackage',
            name='core_applic_job_id_db9115_idx',
        ),
        migrations.RenameIndex(
            model_name='feedbackcomment',
            new_name='core_feedba_feedbac_f44d81_idx',
            old_name='core_feedba_feedbac_cmt_idx',
        ),
        migrations.RenameIndex(
            model_name='feedbackcomment',
            new_name='core_feedba_parent__4adac6_idx',
            old_name='core_feedba_parent__cmt_idx',
        ),
        migrations.RenameIndex(
            model_name='feedbackcomment',
            new_name='core_feedba_section_4971a3_idx',
            old_name='core_feedba_section_cmt_idx',
        ),
        migrations.RenameIndex(
            model_name='feedbacknotification',
            new_name='core_feedba_user_id_c102b0_idx',
            old_name='core_feedba_user_notif_idx',
        ),
        migrations.RenameIndex(
            model_name='feedbacknotification',
            new_name='core_feedba_user_id_ade516_idx',
            old_name='core_feedba_user_is_notif_idx',
        ),
        migrations.RenameIndex(
            model_name='resumefeedback',
            new_name='core_resume_resume__c74ce1_idx',
            old_name='core_resume_resume_v_fb_idx',
        ),
        migrations.RenameIndex(
            model_name='resumefeedback',
            new_name='core_resume_share_i_4f59d5_idx',
            old_name='core_resume_share_fb_idx',
        ),
        migrations.RenameIndex(
            model_name='resumefeedback',
            new_name='core_resume_status_610122_idx',
            old_name='core_resume_status_fb_idx',
        ),
        migrations.RenameIndex(
            model_name='resumefeedback',
            new_name='core_resume_reviewe_7fdbbe_idx',
            old_name='core_resume_reviewe_fb_idx',
        ),
        migrations.RenameIndex(
            model_name='resumeshare',
            new_name='core_resume_share_t_5aa5d2_idx',
            old_name='core_resum_share_t_idx',
        ),
        migrations.RenameIndex(
            model_name='resumeshare',
            new_name='core_resume_resume__527f39_idx',
            old_name='core_resum_resume_v_idx',
        ),
        migrations.RenameIndex(
            model_name='resumeshare',
            new_name='core_resume_is_acti_5ef0f7_idx',
            old_name='core_resum_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='shareaccesslog',
            new_name='core_sharea_share_i_c8e017_idx',
            old_name='core_share_share_a_idx',
        ),
        migrations.RenameIndex(
            model_name='shareaccesslog',
            new_name='core_sharea_reviewe_08506b_idx',
            old_name='core_share_reviewe_idx',
        ),
        migrations.RunPython(drop_old_automationrule_columns, reverse_noop),
        migrations.AlterUniqueTogether(
            name='applicationpackage',
            unique_together={('candidate', 'job')},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(safe_add_last_triggered_at, reverse_noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='applicationautomationrule',
                    name='last_triggered_at',
                    field=models.DateTimeField(blank=True, help_text='When this rule was last executed', null=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(safe_add_trigger_count, reverse_noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='applicationautomationrule',
                    name='trigger_count',
                    field=models.PositiveIntegerField(default=0, help_text='How many times this rule has been triggered'),
                ),
            ],
        ),
        migrations.AddField(
            model_name='applicationpackage',
            name='automation_rule',
            field=models.ForeignKey(blank=True, help_text='Automation rule that generated this package (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_packages', to='core.applicationautomationrule'),
        ),
        migrations.AddField(
            model_name='applicationpackage',
            name='generation_method',
            field=models.CharField(choices=[('manual', 'Manual Generation'), ('automation_rule', 'Automation Rule'), ('batch_process', 'Batch Processing')], default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationpackage',
            name='notes',
            field=models.TextField(blank=True, help_text='User notes about this application package'),
        ),
        migrations.AddField(
            model_name='applicationpackage',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When this package was submitted for the job', null=True),
        ),
        migrations.AlterField(
            model_name='applicationautomationrule',
            name='action_parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Parameters for the action (e.g., which document templates to use)'),
        ),
        migrations.AlterField(
            model_name='applicationautomationrule',
            name='action_type',
            field=models.CharField(choices=[('generate_documents', 'Generate Application Documents'), ('set_reminder', 'Set Application Reminder'), ('update_status', 'Update Application Status'), ('send_email', 'Send Email Notification')], help_text='Action to take when rule is triggered', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationautomationrule',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_automation_rules', to='core.candidateprofile'),
        ),
        migrations.AlterField(
            model_name='applicationautomationrule',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of what this rule does'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(convert_id_to_uuid_applicationautomationrule, reverse_noop),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='applicationautomationrule',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='applicationautomationrule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this rule is currently active'),
        ),
        migrations.AlterField(
            model_name='applicationautomationrule',
            name='name',
            field=models.CharField(help_text='User-defined name for this automation rule', max_length=255),
        ),
        migrations.AlterField(
            model_name='applicationautomationrule',
            name='trigger_conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Additional conditions that must be met for trigger (e.g., job title contains keywords)'),
        ),
        migrations.AlterField(
            model_name='applicationautomationrule',
            name='trigger_type',
            field=models.CharField(choices=[('job_saved', 'Job Saved'), ('job_updated', 'Job Updated'), ('deadline_approaching', 'Application Deadline Approaching'), ('status_changed', 'Application Status Changed')], help_text='Event that triggers this automation', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationpackage',
            name='cover_letter_document',
            field=models.ForeignKey(blank=True, help_text='Generated cover letter document for this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_letter_packages', to='core.document'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(convert_id_to_uuid_applicationpackage, reverse_noop),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='applicationpackage',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='applicationpackage',
            name='resume_document',
            field=models.ForeignKey(blank=True, help_text='Generated resume document for this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_packages', to='core.document'),
        ),
        migrations.AlterField(
            model_name='applicationpackage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready to Submit'), ('submitted', 'Submitted'), ('needs_review', 'Needs Review')], default='ready', max_length=50),
        ),
        migrations.AddIndex(
            model_name='applicationautomationrule',
            index=models.Index(fields=['last_triggered_at'], name='core_applic_last_tr_c1ae07_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationpackage',
            index=models.Index(fields=['job', 'status'], name='core_applic_job_id_95d091_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationpackage',
            index=models.Index(fields=['automation_rule'], name='core_applic_automat_c2aae5_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationpackage',
            index=models.Index(fields=['created_at'], name='core_applic_created_dfc62f_idx'),
        ),
        migrations.AddField(
            model_name='applicationgoal',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_goals', to='core.candidateprofile'),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='core.candidateprofile'),
        ),
        migrations.DeleteModel(
            name='ApplicationChecklist',
        ),
        migrations.DeleteModel(
            name='BulkOperation',
        ),
        migrations.DeleteModel(
            name='ChecklistTask',
        ),
        migrations.DeleteModel(
            name='FollowUpReminder',
        ),
        migrations.DeleteModel(
            name='ScheduledSubmission',
        ),
        migrations.DeleteModel(
            name='WorkflowAutomationLog',
        ),
        migrations.RemoveField(
            model_name='applicationpackage',
            name='cover_letter_template',
        ),
        migrations.RemoveField(
            model_name='applicationpackage',
            name='generation_parameters',
        ),
        migrations.RemoveField(
            model_name='applicationpackage',
            name='match_score',
        ),
        migrations.RemoveField(
            model_name='applicationpackage',
            name='portfolio_url',
        ),
        migrations.RemoveField(
            model_name='applicationpackage',
            name='resume_template',
        ),
        migrations.AddIndex(
            model_name='applicationgoal',
            index=models.Index(fields=['candidate', 'goal_type', 'is_active'], name='core_applic_candida_72ab43_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationgoal',
            index=models.Index(fields=['start_date', 'end_date'], name='core_applic_start_d_e1c040_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['candidate', 'is_active'], name='core_automa_candida_c65d9e_idx'),
        ),
    ]
