# Generated by Django 5.2.8 on 2025-11-11 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20251111_0725'),
        ('core', '0028_applicationgoal_automationrule_and_more'),
    ]

    operations = [
    ]
