# Generated by Django 5.2.8 on 2025-11-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_normalized_name_trgm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['normalized_name'], name='idx_company_normalized_name'),
        ),
    ]
