# Generated by Django 5.2.8 on 2025-11-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_company_idx_company_normalized_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyresearch',
            name='profile_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyresearch',
            name='company_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyresearch',
            name='recent_developments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companyresearch',
            name='potential_interviewers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companyresearch',
            name='competitive_landscape',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyresearch',
            name='strategic_initiatives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companyresearch',
            name='talking_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companyresearch',
            name='interview_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companyresearch',
            name='export_summary',
            field=models.TextField(blank=True),
        ),
    ]
