# Generated by Django 5.2.8 on 2025-11-16 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_preparationchecklistprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewChecklistProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(help_text='Unique identifier for the task', max_length=64)),
                ('category', models.CharField(help_text="Checklist category (e.g., 'Company Research')", max_length=200)),
                ('task', models.CharField(help_text='Task description', max_length=500)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='jobquestionpractice',
            new_name='core_jobque_job_id_f5c42a_idx',
            old_name='core_jobque_job_id_2bbc37_idx',
        ),
        migrations.RenameIndex(
            model_name='jobquestionpractice',
            new_name='core_jobque_job_id_63cf03_idx',
            old_name='core_jobque_job_id_364843_idx',
        ),
        migrations.RenameIndex(
            model_name='preparationchecklistprogress',
            new_name='core_prepar_job_id_f03914_idx',
            old_name='core_prepar_job_id_9f38c7_idx',
        ),
        migrations.RenameIndex(
            model_name='preparationchecklistprogress',
            new_name='core_prepar_job_id_0ce3ad_idx',
            old_name='core_prepar_job_id_3e5f28_idx',
        ),
        migrations.RenameIndex(
            model_name='questionbankcache',
            new_name='core_questi_job_id_26a951_idx',
            old_name='core_questi_job_id_a459d3_idx',
        ),
        migrations.AddField(
            model_name='interviewchecklistprogress',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_progress', to='core.interviewschedule'),
        ),
        migrations.AddIndex(
            model_name='interviewchecklistprogress',
            index=models.Index(fields=['interview', 'completed'], name='core_interv_intervi_b0b5dd_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewchecklistprogress',
            index=models.Index(fields=['interview', 'task_id'], name='core_interv_intervi_edce9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewchecklistprogress',
            unique_together={('interview', 'task_id')},
        ),
    ]
