# Generated by Django 5.2.8 on 2025-11-16 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_contacts_uc086'),
        ('core', '0035_preparationchecklistprogress'),
    ]

    operations = [
    ]
