# Generated by Django 5.2.8 on 2025-11-17 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_z_contacts_uc086_noop'),
        ('core', '0038_conservative_referral_legacy_mapping'),
    ]

    operations = [
    ]
