# Generated by Django 5.2.8 on 2025-11-18 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_make_contact_phone_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Use safe SQL that tolerates already-migrated or slightly different DB states.
        migrations.RunSQL("DROP INDEX IF EXISTS core_contac_owner_lastint_3f1e2d_idx;"),
        migrations.RunSQL("DROP INDEX IF EXISTS core_contac_company_8e065f_idx;"),
        migrations.RunSQL("DROP INDEX IF EXISTS idx_core_contactcompanylink_contact_company;"),
        migrations.RunSQL("DROP INDEX IF EXISTS idx_core_contactjoblink_contact_job;"),
        migrations.RunSQL("DROP INDEX IF EXISTS idx_core_importjob_owner_provider_status;"),
        migrations.RunSQL("DROP INDEX IF EXISTS idx_core_interaction_contact_date;"),
        migrations.RunSQL("DROP INDEX IF EXISTS idx_core_interaction_owner_date;"),
        migrations.RunSQL("DROP INDEX IF EXISTS idx_core_mutualconnection_contact_related;"),
        migrations.RunSQL("DROP INDEX IF EXISTS core_remind_candida_82df9a_idx;"),
        # Conditional rename: only rename if the old index exists.
        migrations.RunSQL("""
        DO $$
        BEGIN
          IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'idx_core_contact_owner_external_id') THEN
            EXECUTE 'ALTER INDEX idx_core_contact_owner_external_id RENAME TO core_contac_owner_i_d5b3da_idx';
          END IF;
        END
        $$;
        """),
        migrations.RunSQL("""
        DO $$
        BEGIN
          IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'idx_core_contact_owner_updated_at') THEN
            EXECUTE 'ALTER INDEX idx_core_contact_owner_updated_at RENAME TO core_contac_owner_i_1d3232_idx';
          END IF;
        END
        $$;
        """),
        migrations.RunSQL("ALTER TABLE core_applicationautomationrule DROP COLUMN IF EXISTS execution_count;"),
        migrations.RunSQL("ALTER TABLE core_applicationautomationrule DROP COLUMN IF EXISTS last_executed;"),
        migrations.RunSQL("ALTER TABLE core_applicationautomationrule DROP COLUMN IF EXISTS priority;"),

        migrations.AlterField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='contactcompanylink',
            name='role_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contactjoblink',
            name='relationship_to_job',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='contactnote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='mutualconnection',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutuals', to='core.contact'),
        ),
        migrations.AlterField(
            model_name='mutualconnection',
            name='context',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
