# Generated by Django 5.2.8 on 2025-11-18 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_fix_reminder_contact_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('linkedin_url', models.URLField(blank=True)),
                ('conversation_notes', models.TextField(blank=True, help_text='What you discussed')),
                ('potential_value', models.CharField(choices=[('high', 'High - Strong Lead/Connection'), ('medium', 'Medium - Worth Following Up'), ('low', 'Low - Casual Connection')], default='medium', max_length=30)),
                ('follow_up_completed', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, help_text='Link to existing contact if available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_connections', to='core.contact')),
            ],
            options={
                'ordering': ['-potential_value', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('meetup', 'Meetup'), ('workshop', 'Workshop'), ('webinar', 'Webinar'), ('career_fair', 'Career Fair'), ('networking_mixer', 'Networking Mixer'), ('panel', 'Panel Discussion'), ('virtual', 'Virtual Event'), ('other', 'Other')], default='other', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text="Physical location or 'Virtual'", max_length=250)),
                ('is_virtual', models.BooleanField(default=False)),
                ('virtual_link', models.URLField(blank=True, help_text='Zoom, Teams, or other virtual event link')),
                ('event_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('organizer', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('event_url', models.URLField(blank=True, help_text='Event page or registration link')),
                ('attendance_status', models.CharField(choices=[('planned', 'Planning to Attend'), ('registered', 'Registered'), ('attended', 'Attended'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='planned', max_length=30)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pre_event_notes', models.TextField(blank=True, help_text='Research, people to meet, companies attending')),
                ('post_event_notes', models.TextField(blank=True, help_text='Key takeaways, impressions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networking_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal_type', models.CharField(choices=[('connections', 'Make New Connections'), ('leads', 'Generate Job Leads'), ('learning', 'Learn About Industry/Company'), ('visibility', 'Increase Professional Visibility'), ('skills', 'Develop Skills'), ('other', 'Other')], max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('target_value', models.IntegerField(blank=True, help_text='e.g., number of connections to make', null=True)),
                ('achieved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.networkingevent')),
            ],
        ),
        migrations.CreateModel(
            name='EventFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('email', 'Send Email'), ('linkedin', 'LinkedIn Connection Request'), ('phone', 'Phone Call'), ('meeting', 'Schedule Meeting'), ('application', 'Submit Job Application'), ('thank_you', 'Send Thank You Note'), ('other', 'Other')], max_length=60)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='core.eventconnection')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='core.networkingevent')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='eventconnection',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='core.networkingevent'),
        ),
        migrations.AddIndex(
            model_name='networkingevent',
            index=models.Index(fields=['owner', '-event_date'], name='core_networ_owner_i_f0fe0e_idx'),
        ),
        migrations.AddIndex(
            model_name='networkingevent',
            index=models.Index(fields=['owner', 'attendance_status'], name='core_networ_owner_i_e52f97_idx'),
        ),
        migrations.AddIndex(
            model_name='networkingevent',
            index=models.Index(fields=['industry'], name='core_networ_industr_c4dc0f_idx'),
        ),
        migrations.AddIndex(
            model_name='networkingevent',
            index=models.Index(fields=['is_virtual'], name='core_networ_is_virt_f4a110_idx'),
        ),
        migrations.AddIndex(
            model_name='eventgoal',
            index=models.Index(fields=['event', 'achieved'], name='core_eventg_event_i_4bc51d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventfollowup',
            index=models.Index(fields=['event', 'completed', 'due_date'], name='core_eventf_event_i_952819_idx'),
        ),
        migrations.AddIndex(
            model_name='eventfollowup',
            index=models.Index(fields=['connection', 'completed'], name='core_eventf_connect_9bb35b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventconnection',
            index=models.Index(fields=['event', 'potential_value'], name='core_eventc_event_i_25829b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventconnection',
            index=models.Index(fields=['event', 'follow_up_completed'], name='core_eventc_event_i_a87d61_idx'),
        ),
    ]
