# Generated by Django 5.2.8 on 2025-11-26 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_questionresponsecoaching'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryNegotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talking_points', models.JSONField(blank=True, default=list, help_text='Personalized talking points based on experience')),
                ('negotiation_scripts', models.JSONField(blank=True, default=dict, help_text='Scripts for different scenarios')),
                ('timing_strategies', models.TextField(blank=True, help_text='Suggested timing for discussions')),
                ('initial_offer', models.JSONField(blank=True, default=dict, help_text='{base, bonus, equity, benefits, total}')),
                ('target_comp', models.JSONField(blank=True, default=dict, help_text="User's target compensation")),
                ('counter_offer_analysis', models.JSONField(blank=True, default=dict, help_text='Analysis of the offer vs market')),
                ('confidence_exercises', models.JSONField(blank=True, default=list, help_text='List of exercises completed')),
                ('status', models.CharField(choices=[('preparation', 'Preparation'), ('active', 'Negotiating'), ('completed', 'Completed')], default='preparation', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('accepted', 'Offer Accepted'), ('declined', 'Offer Declined'), ('rescinded', 'Offer Rescinded'), ('negotiated', 'Successfully Negotiated'), ('failed', 'Negotiation Failed')], max_length=20)),
                ('final_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_negotiation', to='core.jobentry')),
            ],
            options={
                'indexes': [models.Index(fields=['job'], name='core_salary_job_id_a41c55_idx'), models.Index(fields=['status'], name='core_salary_status_561f74_idx')],
            },
        ),
    ]
