# Generated by Django 5.2.8 on 2025-11-26 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_salarynegotiation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryNegotiationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_details', models.JSONField(blank=True, default=dict)),
                ('market_context', models.JSONField(blank=True, default=dict)),
                ('talking_points', models.JSONField(blank=True, default=list)),
                ('total_comp_framework', models.JSONField(blank=True, default=dict)),
                ('scenario_scripts', models.JSONField(blank=True, default=list)),
                ('timing_strategy', models.JSONField(blank=True, default=dict)),
                ('counter_offer_templates', models.JSONField(blank=True, default=list)),
                ('confidence_exercises', models.JSONField(blank=True, default=list)),
                ('offer_guidance', models.JSONField(blank=True, default=dict)),
                ('readiness_checklist', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('generated_by', models.CharField(default='planner', max_length=60)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_plan', to='core.jobentry')),
                ('salary_research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negotiation_plans', to='core.salaryresearch')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryNegotiationOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('pre-offer', 'Pre-Offer Research'), ('offer', 'Offer Review'), ('counter', 'Counter Submitted'), ('final', 'Final Decision')], default='offer', max_length=20)),
                ('company_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('counter_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_result', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_comp_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leverage_used', models.CharField(blank=True, max_length=80)),
                ('confidence_score', models.PositiveSmallIntegerField(blank=True, help_text='1-5 self-assessed confidence', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_outcomes', to='core.jobentry')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcomes', to='core.salarynegotiationplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SalaryNegotiation',
        ),
        migrations.AddIndex(
            model_name='salarynegotiationplan',
            index=models.Index(fields=['job'], name='core_salary_job_id_6d9631_idx'),
        ),
        migrations.AddIndex(
            model_name='salarynegotiationplan',
            index=models.Index(fields=['updated_at'], name='core_salary_updated_7ef64c_idx'),
        ),
        migrations.AddIndex(
            model_name='salarynegotiationoutcome',
            index=models.Index(fields=['job', '-created_at'], name='core_salary_job_id_73b618_idx'),
        ),
        migrations.AddIndex(
            model_name='salarynegotiationoutcome',
            index=models.Index(fields=['stage'], name='core_salary_stage_d49c0d_idx'),
        ),
    ]
