# Generated by ChatGPT on 2025-11-26
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_salarynegotiationplan_salarynegotiationoutcome_and_more'),
        ('core', '0060_technicalprep_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalPrepGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=32)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_progress_at', models.DateTimeField(blank=True, null=True)),
                ('cache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='core.technicalprepcache')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_prep_generations', to='core.jobentry')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_prep_generations', to='core.candidateprofile')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_prep_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='technicalprepgeneration',
            index=models.Index(fields=['job', 'status'], name='techprep_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='technicalprepgeneration',
            index=models.Index(fields=['job', '-created_at'], name='techprep_job_created_idx'),
        ),
    ]
