# Generated by Django 5.2.8 on 2025-11-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_technicalprep_models'),
        ('core', '0048_technicalprepgeneration'),
    ]

    operations = [
    ]
