# Generated by Django 5.2.8 on 2025-11-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_calendarintegration'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='calendarintegration',
            new_name='core_calend_candida_6af480_idx',
            old_name='core_cal_cand_provider_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarintegration',
            new_name='core_calend_provide_e175df_idx',
            old_name='core_cal_prov_status_idx',
        ),
        migrations.RenameIndex(
            model_name='interviewevent',
            new_name='core_interv_calenda_c4b89e_idx',
            old_name='core_inter_calendar_a3b9ca_idx',
        ),
        migrations.RenameIndex(
            model_name='interviewevent',
            new_name='core_interv_intervi_fffcac_idx',
            old_name='core_inter_intervie_2cd140_idx',
        ),
        migrations.RenameIndex(
            model_name='interviewevent',
            new_name='core_interv_follow__107572_idx',
            old_name='core_inter_follow__ec5b91_idx',
        ),
        migrations.AlterField(
            model_name='calendarintegration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='interviewevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
