# Generated by Django 5.2.8 on 2025-11-28 00:00

from django.db import migrations, models
import django.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_rename_core_cal_cand_provider_idx_core_calend_candida_6af480_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarintegration',
            name='frontend_redirect_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='calendarintegration',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='calendarintegration',
            constraint=models.UniqueConstraint(
                condition=~django.db.models.Q(external_account_id=''),
                fields=('candidate', 'provider', 'external_account_id'),
                name='unique_calendar_account_per_provider',
            ),
        ),
    ]
