# Generated by Django 5.2.8 on 2025-11-28 23:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_interviewsuccessprediction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_submitted', models.BooleanField(default=False)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('interview_received', models.BooleanField(default=False)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_stage', models.CharField(blank=True, max_length=100)),
                ('offer_received', models.BooleanField(default=False)),
                ('offer_date', models.DateField(blank=True, null=True)),
                ('offer_accepted', models.BooleanField(blank=True, null=True)),
                ('success_score', models.IntegerField(default=0, help_text='1-10 score for referral effectiveness')),
                ('time_to_response_days', models.IntegerField(blank=True, null=True)),
                ('time_to_interview_days', models.IntegerField(blank=True, null=True)),
                ('outcome_details', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True, help_text='What worked well or could be improved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_source_name', models.CharField(blank=True, max_length=200)),
                ('referral_source_title', models.CharField(blank=True, max_length=200)),
                ('referral_source_company', models.CharField(blank=True, max_length=200)),
                ('referral_source_email', models.EmailField(blank=True, max_length=254)),
                ('referral_source_phone', models.CharField(blank=True, max_length=50)),
                ('referral_source_linkedin', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending - Not Sent'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed - Referral Given'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('relationship_strength', models.CharField(choices=[('strong', 'Strong - Close Connection'), ('moderate', 'Moderate - Regular Contact'), ('weak', 'Weak - Occasional Contact'), ('minimal', 'Minimal - Limited Interaction')], default='moderate', max_length=20)),
                ('request_message', models.TextField(blank=True, help_text='Personalized referral request message')),
                ('message_tone', models.CharField(blank=True, help_text='Tone used for message (e.g., professional, casual)', max_length=50)),
                ('template_params', models.JSONField(blank=True, default=dict, help_text='Parameters used for AI generation')),
                ('optimal_timing_suggestion', models.TextField(blank=True, help_text='AI suggestion for best time to request')),
                ('etiquette_guidance', models.TextField(blank=True, help_text='Guidelines on appropriate referral etiquette')),
                ('last_contact_date', models.DateField(blank=True, help_text='Last time you contacted this person', null=True)),
                ('suggested_send_date', models.DateField(blank=True, help_text='Suggested date to send request', null=True)),
                ('request_sent_date', models.DateTimeField(blank=True, null=True)),
                ('response_received_date', models.DateTimeField(blank=True, null=True)),
                ('referral_given_date', models.DateTimeField(blank=True, null=True)),
                ('follow_up_scheduled_date', models.DateField(blank=True, null=True)),
                ('follow_up_completed', models.BooleanField(default=False)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('referral_successful', models.BooleanField(blank=True, help_text='Did the referral lead to interview/offer?', null=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('gratitude_expressed', models.BooleanField(default=False, help_text='Have you thanked the referrer?')),
                ('gratitude_date', models.DateTimeField(blank=True, null=True)),
                ('reciprocity_potential', models.TextField(blank=True, help_text='Notes on how you might reciprocate')),
                ('relationship_impact', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this referral request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='interviewsuccessprediction',
            new_name='core_interv_intervi_9bc100_idx',
            old_name='core_succ_pred_interview_idx',
        ),
        migrations.RenameIndex(
            model_name='interviewsuccessprediction',
            new_name='core_interv_candida_178a75_idx',
            old_name='core_succ_pred_candidate_idx',
        ),
        migrations.RenameIndex(
            model_name='interviewsuccessprediction',
            new_name='core_interv_job_id_1a36cc_idx',
            old_name='core_succ_pred_job_idx',
        ),
        migrations.RenameIndex(
            model_name='interviewsuccessprediction',
            new_name='core_interv_is_late_d6548a_idx',
            old_name='core_succ_pred_latest_idx',
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Contact who might provide referral', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_requests', to='core.contact'),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='job',
            field=models.ForeignKey(help_text='Job opportunity for which referral is requested', on_delete=django.db.models.deletion.CASCADE, related_name='referral_requests', to='core.jobopportunity'),
        ),
        migrations.AddField(
            model_name='referralrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referraloutcome',
            name='referral_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='core.referralrequest'),
        ),
        migrations.AddIndex(
            model_name='referralrequest',
            index=models.Index(fields=['user', 'status', '-created_at'], name='core_referr_user_id_4661e3_idx'),
        ),
        migrations.AddIndex(
            model_name='referralrequest',
            index=models.Index(fields=['job', 'status'], name='core_referr_job_id_a06b61_idx'),
        ),
        migrations.AddIndex(
            model_name='referralrequest',
            index=models.Index(fields=['contact', 'status'], name='core_referr_contact_7879d3_idx'),
        ),
        migrations.AddIndex(
            model_name='referralrequest',
            index=models.Index(fields=['user', 'follow_up_scheduled_date'], name='core_referr_user_id_b6ee03_idx'),
        ),
        migrations.AddIndex(
            model_name='referralrequest',
            index=models.Index(fields=['user', 'gratitude_expressed'], name='core_referr_user_id_bb95d6_idx'),
        ),
    ]
