# Generated by Django 5.2.8 on 2025-11-29 01:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_interviewsuccessprediction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Specific goal title', max_length=200)),
                ('description', models.TextField(help_text='Detailed goal description')),
                ('goal_type', models.CharField(choices=[('short_term', 'Short-term (< 6 months)'), ('long_term', 'Long-term (6+ months)')], default='short_term', max_length=20)),
                ('target_metric', models.CharField(blank=True, help_text="What metric defines success? e.g., '5 interviews', '$120K salary'", max_length=200)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, help_text='Current progress value', max_digits=10)),
                ('target_value', models.DecimalField(decimal_places=2, default=100, help_text='Target value to achieve', max_digits=10)),
                ('action_steps', models.JSONField(blank=True, default=list, help_text='List of actionable steps to achieve goal')),
                ('target_date', models.DateField(help_text='Goal deadline')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused'), ('abandoned', 'Abandoned')], default='not_started', max_length=20)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Auto-calculated or manual progress %', max_digits=5)),
                ('motivation_notes', models.TextField(blank=True, help_text='Why this goal matters')),
                ('accountability_partner', models.EmailField(blank=True, help_text='Optional accountability partner email', max_length=254)),
                ('share_progress', models.BooleanField(default=False, help_text='Share progress with accountability partner')),
                ('ai_recommendations', models.JSONField(blank=True, default=dict, help_text='AI-generated recommendations for achieving goal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'target_date'],
            },
        ),
        migrations.RenameIndex(
            model_name='interviewsuccessprediction',
            new_name='core_interv_intervi_9bc100_idx',
            old_name='core_succ_pred_interview_idx',
        ),
        migrations.RenameIndex(
            model_name='interviewsuccessprediction',
            new_name='core_interv_candida_178a75_idx',
            old_name='core_succ_pred_candidate_idx',
        ),
        migrations.RenameIndex(
            model_name='interviewsuccessprediction',
            new_name='core_interv_job_id_1a36cc_idx',
            old_name='core_succ_pred_job_idx',
        ),
        migrations.RenameIndex(
            model_name='interviewsuccessprediction',
            new_name='core_interv_is_late_d6548a_idx',
            old_name='core_succ_pred_latest_idx',
        ),
        migrations.AddField(
            model_name='careergoal',
            name='linked_jobs',
            field=models.ManyToManyField(blank=True, help_text='Jobs connected to this goal', related_name='career_goals', to='core.jobopportunity'),
        ),
        migrations.AddField(
            model_name='careergoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goalmilestone',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.careergoal'),
        ),
        migrations.AddIndex(
            model_name='careergoal',
            index=models.Index(fields=['user', 'status'], name='core_career_user_id_ca3947_idx'),
        ),
        migrations.AddIndex(
            model_name='careergoal',
            index=models.Index(fields=['user', 'target_date'], name='core_career_user_id_def5be_idx'),
        ),
        migrations.AddIndex(
            model_name='careergoal',
            index=models.Index(fields=['status', 'target_date'], name='core_career_status_4e544d_idx'),
        ),
        migrations.AddIndex(
            model_name='goalmilestone',
            index=models.Index(fields=['goal', 'completed'], name='core_goalmi_goal_id_d67d4d_idx'),
        ),
    ]
