# Generated by Django 5.2.8 on 2025-11-29 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_careergoal_goalmilestone_and_more'),
        ('core', '0057_referraloutcome_referralrequest_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='interviewsuccessprediction',
            new_name='core_interv_intervi_9bc100_idx',
            old_name='core_succ_pred_interview_idx',
        ),
        migrations.RenameIndex(
            model_name='interviewsuccessprediction',
            new_name='core_interv_candida_178a75_idx',
            old_name='core_succ_pred_candidate_idx',
        ),
        migrations.RenameIndex(
            model_name='interviewsuccessprediction',
            new_name='core_interv_job_id_1a36cc_idx',
            old_name='core_succ_pred_job_idx',
        ),
        migrations.RenameIndex(
            model_name='interviewsuccessprediction',
            new_name='core_interv_is_late_d6548a_idx',
            old_name='core_succ_pred_latest_idx',
        ),
    ]
