# Generated by Django 5.2.8 on 2025-11-29 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_referraloutcome_referralrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralrequest',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='referralrequest',
            name='job',
        ),
        migrations.RemoveField(
            model_name='referralrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReferralOutcome',
        ),
        migrations.DeleteModel(
            name='ReferralRequest',
        ),
    ]
