"""
This is a no-op placeholder migration to reconcile migration graph
during branch merges. It intentionally has no operations — its
presence satisfies dependencies for merge commits that reference
this name. Remove or replace with the canonical migration when
reconciling upstream history.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_referraloutcome_referralrequest_and_more'),
    ]

    operations = [
    ]
# Generated by Django 5.2.8 on 2025-11-29 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_referraloutcome_referralrequest_and_more'),
    ]
    # This migration was previously attempting to remove fields and delete
    # ReferralRequest/ReferralOutcome models, but repository history contains
    # alternate migration paths that already adjusted these models. To avoid
    # migration conflicts during test DB creation we make this migration a
    # no-op. The original remove/delete operations were left out intentionally.
    operations = []
