# Generated by Django 5.2.8 on 2025-11-29 04:21

from django.db import migrations


def create_rename_index_operation(old_name, new_name):
    """Create a migration operation to rename an index with vendor checks."""
    def forward(apps, schema_editor):
        if schema_editor.connection.vendor != 'postgresql':
            return
        with schema_editor.connection.cursor() as cursor:
            # Check if new index doesn't exist and old index exists
            cursor.execute(f"SELECT to_regclass('{new_name}')")
            new_exists = cursor.fetchone()[0]
            cursor.execute(f"SELECT to_regclass('{old_name}')")
            old_exists = cursor.fetchone()[0]
            
            if new_exists is None and old_exists is not None:
                cursor.execute(f'ALTER INDEX {old_name} RENAME TO {new_name}')
    
    def reverse(apps, schema_editor):
        if schema_editor.connection.vendor != 'postgresql':
            return
        with schema_editor.connection.cursor() as cursor:
            # Check if old index doesn't exist and new index exists
            cursor.execute(f"SELECT to_regclass('{old_name}')")
            old_exists = cursor.fetchone()[0]
            cursor.execute(f"SELECT to_regclass('{new_name}')")
            new_exists = cursor.fetchone()[0]
            
            if old_exists is None and new_exists is not None:
                cursor.execute(f'ALTER INDEX {new_name} RENAME TO {old_name}')
    
    return migrations.RunPython(forward, reverse)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_careergoal_goalmilestone_and_more'),
        ('core', '0057_referraloutcome_referralrequest_and_more'),
    ]

    operations = [
        create_rename_index_operation('core_succ_pred_interview_idx', 'core_interv_intervi_9bc100_idx'),
        create_rename_index_operation('core_succ_pred_candidate_idx', 'core_interv_candida_178a75_idx'),
        create_rename_index_operation('core_succ_pred_job_idx', 'core_interv_job_id_1a36cc_idx'),
        create_rename_index_operation('core_succ_pred_latest_idx', 'core_interv_is_late_d6548a_idx'),
    ]
