# Generated by Django 5.2.8 on 2025-11-29 04:21

from django.db import migrations


def rename_index_if_exists(old_name: str, new_name: str) -> migrations.RunSQL:
    sql = f"""
    DO $$
    BEGIN
        IF to_regclass('{new_name}') IS NULL AND to_regclass('{old_name}') IS NOT NULL THEN
            EXECUTE 'ALTER INDEX {old_name} RENAME TO {new_name}';
        END IF;
    END
    $$;
    """
    reverse_sql = f"""
    DO $$
    BEGIN
        IF to_regclass('{old_name}') IS NULL AND to_regclass('{new_name}') IS NOT NULL THEN
            EXECUTE 'ALTER INDEX {new_name} RENAME TO {old_name}';
        END IF;
    END
    $$;
    """
    return migrations.RunSQL(sql=sql, reverse_sql=reverse_sql)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_careergoal_goalmilestone_and_more'),
        ('core', '0057_referraloutcome_referralrequest_and_more'),
    ]

    operations = [
        rename_index_if_exists('core_succ_pred_interview_idx', 'core_interv_intervi_9bc100_idx'),
        rename_index_if_exists('core_succ_pred_candidate_idx', 'core_interv_candida_178a75_idx'),
        rename_index_if_exists('core_succ_pred_job_idx', 'core_interv_job_id_1a36cc_idx'),
        rename_index_if_exists('core_succ_pred_latest_idx', 'core_interv_is_late_d6548a_idx'),
    ]
