# Generated by Django 5.2.8 on 2025-11-29 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_merge_20251128_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referraloutcome',
            name='referral_request',
        ),
        migrations.RemoveField(
            model_name='referralrequest',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='referralrequest',
            name='job',
        ),
        migrations.RemoveField(
            model_name='referralrequest',
            name='user',
        ),
        migrations.RenameIndex(
            model_name='mentorshipmessage',
            new_name='core_mentor_team_me_23df97_idx',
            old_name='core_mentors_team_me_efacc8_idx',
        ),
        migrations.RenameIndex(
            model_name='mentorshiprequest',
            new_name='core_mentor_request_b2615c_idx',
            old_name='core_mr_request_status',
        ),
        migrations.RenameIndex(
            model_name='mentorshiprequest',
            new_name='core_mentor_receive_2209d8_idx',
            old_name='core_mr_receiv_status',
        ),
        migrations.RenameIndex(
            model_name='mentorshipsharedapplication',
            new_name='core_mentor_team_me_6a4eed_idx',
            old_name='core_mshare_team_job',
        ),
        migrations.DeleteModel(
            name='ReferralOutcome',
        ),
        migrations.DeleteModel(
            name='ReferralRequest',
        ),
    ]
