# Generated by Django 5.2.8 on 2025-11-29 03:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_technicalprep_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Removed operations that try to delete non-existent ReferralRequest/ReferralOutcome models
        migrations.CreateModel(
            name='ProfessionalReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(help_text='Professional title/position', max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('linkedin_url', models.URLField(blank=True)),
                ('relationship_type', models.CharField(choices=[('supervisor', 'Direct Supervisor'), ('manager', 'Manager'), ('colleague', 'Colleague'), ('mentor', 'Mentor'), ('professor', 'Professor/Academic'), ('client', 'Client'), ('other', 'Other')], max_length=30)),
                ('relationship_description', models.TextField(blank=True, help_text='How you worked together')),
                ('years_known', models.PositiveSmallIntegerField(default=0, help_text='Years known')),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited Availability'), ('unavailable', 'Currently Unavailable'), ('pending_permission', 'Pending Permission')], default='pending_permission', max_length=30)),
                ('permission_granted_date', models.DateField(blank=True, null=True)),
                ('last_used_date', models.DateField(blank=True, null=True)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('either', 'Either')], default='email', max_length=20)),
                ('best_for_roles', models.JSONField(blank=True, default=list, help_text='Role types this reference is best for')),
                ('best_for_industries', models.JSONField(blank=True, default=list, help_text='Industries this reference is best for')),
                ('key_strengths_to_highlight', models.TextField(blank=True, help_text='Key strengths this reference can speak to')),
                ('projects_worked_together', models.TextField(blank=True, help_text='Specific projects or achievements')),
                ('talking_points', models.JSONField(blank=True, default=list, help_text='Specific talking points for reference')),
                ('last_contacted_date', models.DateField(blank=True, null=True)),
                ('next_check_in_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Private notes about this reference')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_references', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceAppreciation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appreciation_type', models.CharField(choices=[('thank_you_note', 'Thank You Note'), ('coffee_meetup', 'Coffee/Lunch Meetup'), ('gift', 'Gift/Token of Appreciation'), ('linkedin_endorsement', 'LinkedIn Endorsement'), ('recommendation', 'Written Recommendation'), ('referral_returned', 'Returned Referral/Favor'), ('update_call', 'Update Call'), ('holiday_greeting', 'Holiday Greeting'), ('other', 'Other')], max_length=30)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Private notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations', to='core.professionalreference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_appreciations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReferencePortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'Software Engineering Roles', 'Management Positions'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_role_types', models.JSONField(blank=True, default=list)),
                ('target_industries', models.JSONField(blank=True, default=list)),
                ('target_companies', models.JSONField(blank=True, default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('references', models.ManyToManyField(blank=True, related_name='portfolios', to='core.professionalreference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('position_title', models.CharField(max_length=200)),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to Reference'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('request_sent_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('custom_message', models.TextField(blank=True, help_text='Personalized message sent to reference')),
                ('preparation_materials_sent', models.BooleanField(default=False)),
                ('feedback_received', models.TextField(blank=True, help_text='Feedback from reference about the request')),
                ('reference_rating', models.PositiveSmallIntegerField(blank=True, help_text='How reference rated the experience (1-5)', null=True)),
                ('contributed_to_success', models.BooleanField(default=False, help_text='Did this reference contribute to getting the job?')),
                ('outcome_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_requests', to='core.application')),
                ('job_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_requests', to='core.jobopportunity')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.professionalreference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('request_email', 'Reference Request Email'), ('preparation_guide', 'Preparation Guide'), ('talking_points', 'Talking Points'), ('thank_you', 'Thank You Note')], max_length=30)),
                ('subject_line', models.CharField(blank=True, help_text='Email subject (for email templates)', max_length=200)),
                ('content', models.TextField(help_text='Template content with placeholders')),
                ('for_relationship_types', models.JSONField(blank=True, default=list, help_text='Relationship types this template is for')),
                ('for_role_types', models.JSONField(blank=True, default=list, help_text='Job role types this template is for')),
                ('is_default', models.BooleanField(default=False)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        # Removed DeleteModel operations for ReferralOutcome and ReferralRequest
        migrations.AddIndex(
            model_name='professionalreference',
            index=models.Index(fields=['user', 'is_active'], name='core_profes_user_id_9867b0_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalreference',
            index=models.Index(fields=['user', 'availability_status'], name='core_profes_user_id_77d5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalreference',
            index=models.Index(fields=['user', 'last_used_date'], name='core_profes_user_id_a84d38_idx'),
        ),
        migrations.AddIndex(
            model_name='referenceappreciation',
            index=models.Index(fields=['user', 'date'], name='core_refere_user_id_f112c7_idx'),
        ),
        migrations.AddIndex(
            model_name='referenceappreciation',
            index=models.Index(fields=['reference', 'date'], name='core_refere_referen_93588a_idx'),
        ),
        migrations.AddIndex(
            model_name='referenceportfolio',
            index=models.Index(fields=['user', 'is_default'], name='core_refere_user_id_07b252_idx'),
        ),
        migrations.AddIndex(
            model_name='referencerequest',
            index=models.Index(fields=['user', 'request_status'], name='core_refere_user_id_a9f661_idx'),
        ),
        migrations.AddIndex(
            model_name='referencerequest',
            index=models.Index(fields=['reference', 'request_status'], name='core_refere_referen_8f51ba_idx'),
        ),
        migrations.AddIndex(
            model_name='referencerequest',
            index=models.Index(fields=['application'], name='core_refere_applica_557ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='referencerequest',
            index=models.Index(fields=['user', 'due_date'], name='core_refere_user_id_88eb9e_idx'),
        ),
        migrations.AddIndex(
            model_name='referencetemplate',
            index=models.Index(fields=['user', 'template_type'], name='core_refere_user_id_1b03cc_idx'),
        ),
        migrations.AddIndex(
            model_name='referencetemplate',
            index=models.Index(fields=['user', 'is_default'], name='core_refere_user_id_90eb0f_idx'),
        ),
    ]
