# Generated by Django 5.2.8 on 2025-11-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_merge_20251116_2213'),
        ('core', '0058_remove_referralrequest_contact_and_more'),
        ('core', '0059_uc_052_resume_sharing_feedback'),
        ('core', '0061_remove_referralrequest_contact_and_more'),
    ]

    operations = [
    ]
