# Generated by Django 5.2.8 on 2025-11-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_merge_20251116_2213'),
        ('core', '0058_merge_20251128_2321'),
        ('core', '0059_uc_052_resume_sharing_feedback'),
        ('core', '0061_mentorship_features'),
    ]

    operations = [
    ]
