# Generated by Django 5.2.8 on 2025-11-29 23:18

from django.db import migrations, models


def rename_indexes_if_exist(apps, schema_editor):
    """Safely rename indexes only if they exist."""
    from django.db import connection
    
    # Get existing indexes
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE schemaname = 'public'
        """)
        existing_indexes = {row[0] for row in cursor.fetchall()}
    
    # Only rename if old index exists
    index_renames = [
        ('core_feedbackcomment', 'core_feedba_feedbac_cmt_idx', 'core_feedba_feedbac_f44d81_idx'),
        ('core_feedbackcomment', 'core_feedba_parent__cmt_idx', 'core_feedba_parent__4adac6_idx'),
        ('core_feedbackcomment', 'core_feedba_section_cmt_idx', 'core_feedba_section_4971a3_idx'),
        ('core_feedbacknotification', 'core_feedba_user_notif_idx', 'core_feedba_user_id_c102b0_idx'),
        ('core_feedbacknotification', 'core_feedba_user_is_notif_idx', 'core_feedba_user_id_ade516_idx'),
        ('core_resumefeedback', 'core_resume_resume_v_fb_idx', 'core_resume_resume__c74ce1_idx'),
        ('core_resumefeedback', 'core_resume_share_fb_idx', 'core_resume_share_i_4f59d5_idx'),
        ('core_resumefeedback', 'core_resume_status_fb_idx', 'core_resume_status_610122_idx'),
        ('core_resumefeedback', 'core_resume_reviewe_fb_idx', 'core_resume_reviewe_7fdbbe_idx'),
        ('core_resumeshare', 'core_resum_share_t_idx', 'core_resume_share_t_5aa5d2_idx'),
        ('core_resumeshare', 'core_resum_resume_v_idx', 'core_resume_resume__527f39_idx'),
        ('core_resumeshare', 'core_resum_is_acti_idx', 'core_resume_is_acti_5ef0f7_idx'),
        ('core_shareaccesslog', 'core_share_share_a_idx', 'core_sharea_share_i_c8e017_idx'),
        ('core_shareaccesslog', 'core_share_reviewe_idx', 'core_sharea_reviewe_08506b_idx'),
    ]
    
    for table, old_name, new_name in index_renames:
        if old_name in existing_indexes:
            with connection.cursor() as cursor:
                cursor.execute(f'ALTER INDEX {old_name} RENAME TO {new_name}')


def reverse_rename_indexes(apps, schema_editor):
    """Reverse the index renames."""
    from django.db import connection
    
    index_renames = [
        ('core_feedbackcomment', 'core_feedba_feedbac_f44d81_idx', 'core_feedba_feedbac_cmt_idx'),
        ('core_feedbackcomment', 'core_feedba_parent__4adac6_idx', 'core_feedba_parent__cmt_idx'),
        ('core_feedbackcomment', 'core_feedba_section_4971a3_idx', 'core_feedba_section_cmt_idx'),
        ('core_feedbacknotification', 'core_feedba_user_id_c102b0_idx', 'core_feedba_user_notif_idx'),
        ('core_feedbacknotification', 'core_feedba_user_id_ade516_idx', 'core_feedba_user_is_notif_idx'),
        ('core_resumefeedback', 'core_resume_resume__c74ce1_idx', 'core_resume_resume_v_fb_idx'),
        ('core_resumefeedback', 'core_resume_share_i_4f59d5_idx', 'core_resume_share_fb_idx'),
        ('core_resumefeedback', 'core_resume_status_610122_idx', 'core_resume_status_fb_idx'),
        ('core_resumefeedback', 'core_resume_reviewe_7fdbbe_idx', 'core_resume_reviewe_fb_idx'),
        ('core_resumeshare', 'core_resume_share_t_5aa5d2_idx', 'core_resum_share_t_idx'),
        ('core_resumeshare', 'core_resume_resume__527f39_idx', 'core_resum_resume_v_idx'),
        ('core_resumeshare', 'core_resume_is_acti_5ef0f7_idx', 'core_resum_is_acti_idx'),
        ('core_shareaccesslog', 'core_sharea_share_i_c8e017_idx', 'core_share_share_a_idx'),
        ('core_shareaccesslog', 'core_sharea_reviewe_08506b_idx', 'core_share_reviewe_idx'),
    ]
    
    with connection.cursor() as cursor:
        cursor.execute("SELECT indexname FROM pg_indexes WHERE schemaname = 'public'")
        existing_indexes = {row[0] for row in cursor.fetchall()}
    
    for table, new_name, old_name in index_renames:
        if new_name in existing_indexes:
            with connection.cursor() as cursor:
                cursor.execute(f'ALTER INDEX {new_name} RENAME TO {old_name}')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_merge_conflicting_merges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referraloutcome',
            name='referral_request',
        ),
        migrations.RemoveField(
            model_name='referralrequest',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='referralrequest',
            name='job',
        ),
        migrations.RemoveField(
            model_name='referralrequest',
            name='user',
        ),
        # Use custom function to safely rename indexes
        migrations.RunPython(rename_indexes_if_exist, reverse_rename_indexes),
        migrations.AddField(
            model_name='jobopportunity',
            name='company_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.DeleteModel(
            name='ReferralOutcome',
        ),
        migrations.DeleteModel(
            name='ReferralRequest',
        ),
    ]
