# Generated by Django 5.2.8 on 2025-11-29 23:18

from django.db import migrations, models


def drop_index_if_exists_factory(name: str):
    """Factory function that returns a migrations operation."""
    def forward(apps, schema_editor):
        # Only run for PostgreSQL - SQLite handles indexes differently
        if schema_editor.connection.vendor == 'postgresql':
            try:
                with schema_editor.connection.cursor() as cursor:
                    cursor.execute(f"DROP INDEX IF EXISTS {name};")
            except Exception:
                pass  # Index doesn't exist, that's fine
    
    def backward(apps, schema_editor):
        pass  # No-op for reverse
    
    return migrations.RunPython(forward, backward)


def drop_column_if_exists_factory(table: str, column: str):
    """Factory function that returns a migrations operation."""
    def forward(apps, schema_editor):
        # Only run for PostgreSQL - SQLite migrations handle this differently
        if schema_editor.connection.vendor == 'postgresql':
            try:
                with schema_editor.connection.cursor() as cursor:
                    cursor.execute(f"ALTER TABLE IF EXISTS {table} DROP COLUMN IF EXISTS {column} CASCADE;")
            except Exception:
                pass  # Column doesn't exist, that's fine
    
    def backward(apps, schema_editor):
        pass  # No-op for reverse
    
    return migrations.RunPython(forward, backward)


def drop_table_if_exists_factory(table: str):
    """Factory function that returns a migrations operation."""
    def forward(apps, schema_editor):
        if schema_editor.connection.vendor != 'postgresql':
            # SQLite: check if table exists first
            return  # Skip for SQLite in tests
        try:
            sql = f"DROP TABLE IF EXISTS {table} CASCADE;"
            with schema_editor.connection.cursor() as cursor:
                cursor.execute(sql)
        except Exception:
            pass  # Table doesn't exist, that's fine
    
    def backward(apps, schema_editor):
        pass  # No-op for reverse
    
    return migrations.RunPython(forward, backward)


def rename_indexes_if_exist(apps, schema_editor):
    """Safely rename indexes only if they exist."""
    from django.db import connection
    
    # Skip for SQLite (used in tests)
    if connection.vendor == 'sqlite':
        return
    
    # Get existing indexes
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE schemaname = 'public'
        """)
        existing_indexes = {row[0] for row in cursor.fetchall()}
    
    # Only rename if old index exists
    index_renames = [
        ('core_feedbackcomment', 'core_feedba_feedbac_cmt_idx', 'core_feedba_feedbac_f44d81_idx'),
        ('core_feedbackcomment', 'core_feedba_parent__cmt_idx', 'core_feedba_parent__4adac6_idx'),
        ('core_feedbackcomment', 'core_feedba_section_cmt_idx', 'core_feedba_section_4971a3_idx'),
        ('core_feedbacknotification', 'core_feedba_user_notif_idx', 'core_feedba_user_id_c102b0_idx'),
        ('core_feedbacknotification', 'core_feedba_user_is_notif_idx', 'core_feedba_user_id_ade516_idx'),
        ('core_resumefeedback', 'core_resume_resume_v_fb_idx', 'core_resume_resume__c74ce1_idx'),
        ('core_resumefeedback', 'core_resume_share_fb_idx', 'core_resume_share_i_4f59d5_idx'),
        ('core_resumefeedback', 'core_resume_status_fb_idx', 'core_resume_status_610122_idx'),
        ('core_resumefeedback', 'core_resume_reviewe_fb_idx', 'core_resume_reviewe_7fdbbe_idx'),
        ('core_resumeshare', 'core_resum_share_t_idx', 'core_resume_share_t_5aa5d2_idx'),
        ('core_resumeshare', 'core_resum_resume_v_idx', 'core_resume_resume__527f39_idx'),
        ('core_resumeshare', 'core_resum_is_acti_idx', 'core_resume_is_acti_5ef0f7_idx'),
        ('core_shareaccesslog', 'core_share_share_a_idx', 'core_sharea_share_i_c8e017_idx'),
        ('core_shareaccesslog', 'core_share_reviewe_idx', 'core_sharea_reviewe_08506b_idx'),
    ]
    
    for table, old_name, new_name in index_renames:
        if old_name in existing_indexes:
            with connection.cursor() as cursor:
                cursor.execute(f'ALTER INDEX {old_name} RENAME TO {new_name}')


def reverse_rename_indexes(apps, schema_editor):
    """Reverse the index renames."""
    from django.db import connection
    
    # Skip for SQLite (used in tests)
    if connection.vendor == 'sqlite':
        return
    
    index_renames = [
        ('core_feedbackcomment', 'core_feedba_feedbac_f44d81_idx', 'core_feedba_feedbac_cmt_idx'),
        ('core_feedbackcomment', 'core_feedba_parent__4adac6_idx', 'core_feedba_parent__cmt_idx'),
        ('core_feedbackcomment', 'core_feedba_section_4971a3_idx', 'core_feedba_section_cmt_idx'),
        ('core_feedbacknotification', 'core_feedba_user_id_c102b0_idx', 'core_feedba_user_notif_idx'),
        ('core_feedbacknotification', 'core_feedba_user_id_ade516_idx', 'core_feedba_user_is_notif_idx'),
        ('core_resumefeedback', 'core_resume_resume__c74ce1_idx', 'core_resume_resume_v_fb_idx'),
        ('core_resumefeedback', 'core_resume_share_i_4f59d5_idx', 'core_resume_share_fb_idx'),
        ('core_resumefeedback', 'core_resume_status_610122_idx', 'core_resume_status_fb_idx'),
        ('core_resumefeedback', 'core_resume_reviewe_7fdbbe_idx', 'core_resume_reviewe_fb_idx'),
        ('core_resumeshare', 'core_resume_share_t_5aa5d2_idx', 'core_resum_share_t_idx'),
        ('core_resumeshare', 'core_resume_resume__527f39_idx', 'core_resum_resume_v_idx'),
        ('core_resumeshare', 'core_resume_is_acti_5ef0f7_idx', 'core_resum_is_acti_idx'),
        ('core_shareaccesslog', 'core_sharea_share_i_c8e017_idx', 'core_share_share_a_idx'),
        ('core_shareaccesslog', 'core_sharea_reviewe_08506b_idx', 'core_share_reviewe_idx'),
    ]
    
    with connection.cursor() as cursor:
        cursor.execute("SELECT indexname FROM pg_indexes WHERE schemaname = 'public'")
        existing_indexes = {row[0] for row in cursor.fetchall()}
    
    for table, new_name, old_name in index_renames:
        if new_name in existing_indexes:
            with connection.cursor() as cursor:
                cursor.execute(f'ALTER INDEX {new_name} RENAME TO {old_name}')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_merge_conflicting_merges'),
    ]

    operations = [
        # First, update state to remove fields (prevents Django from trying to create indexes)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='referraloutcome',
                    name='referral_request',
                ),
                migrations.RemoveField(
                    model_name='referralrequest',
                    name='contact',
                ),
                migrations.RemoveField(
                    model_name='referralrequest',
                    name='job',
                ),
                migrations.RemoveField(
                    model_name='referralrequest',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='ReferralOutcome',
                ),
                migrations.DeleteModel(
                    name='ReferralRequest',
                ),
            ],
            database_operations=[
                # Database operations that work with both PostgreSQL and SQLite
                migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
            ],
        ),
        
        # Now do the actual database cleanup (only for PostgreSQL)
        drop_index_if_exists_factory('core_referr_user_id_4661e3_idx'),
        drop_index_if_exists_factory('core_referr_job_id_a06b61_idx'),
        drop_index_if_exists_factory('core_referr_contact_7879d3_idx'),
        drop_index_if_exists_factory('core_referr_user_id_b6ee03_idx'),
        drop_index_if_exists_factory('core_referr_user_id_bb95d6_idx'),
        
        drop_column_if_exists_factory('core_referraloutcome', 'referral_request_id'),
        drop_column_if_exists_factory('core_referralrequest', 'contact_id'),
        drop_column_if_exists_factory('core_referralrequest', 'job_id'),
        drop_column_if_exists_factory('core_referralrequest', 'user_id'),
        
        drop_table_if_exists_factory('core_referraloutcome'),
        drop_table_if_exists_factory('core_referralrequest'),
        
        # Rename indexes for resume feedback models
        migrations.RunPython(rename_indexes_if_exist, reverse_rename_indexes),
        
        # Add new field
        migrations.AddField(
            model_name='jobopportunity',
            name='company_name',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
