# Generated by Django 5.2.8 on 2025-11-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_merge_conflicting_merges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referraloutcome',
            name='referral_request',
        ),
        migrations.RemoveField(
            model_name='referralrequest',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='referralrequest',
            name='job',
        ),
        migrations.RemoveField(
            model_name='referralrequest',
            name='user',
        ),
        migrations.RenameIndex(
            model_name='feedbackcomment',
            new_name='core_feedba_feedbac_f44d81_idx',
            old_name='core_feedba_feedbac_cmt_idx',
        ),
        migrations.RenameIndex(
            model_name='feedbackcomment',
            new_name='core_feedba_parent__4adac6_idx',
            old_name='core_feedba_parent__cmt_idx',
        ),
        migrations.RenameIndex(
            model_name='feedbackcomment',
            new_name='core_feedba_section_4971a3_idx',
            old_name='core_feedba_section_cmt_idx',
        ),
        migrations.RenameIndex(
            model_name='feedbacknotification',
            new_name='core_feedba_user_id_c102b0_idx',
            old_name='core_feedba_user_notif_idx',
        ),
        migrations.RenameIndex(
            model_name='feedbacknotification',
            new_name='core_feedba_user_id_ade516_idx',
            old_name='core_feedba_user_is_notif_idx',
        ),
        migrations.RenameIndex(
            model_name='resumefeedback',
            new_name='core_resume_resume__c74ce1_idx',
            old_name='core_resume_resume_v_fb_idx',
        ),
        migrations.RenameIndex(
            model_name='resumefeedback',
            new_name='core_resume_share_i_4f59d5_idx',
            old_name='core_resume_share_fb_idx',
        ),
        migrations.RenameIndex(
            model_name='resumefeedback',
            new_name='core_resume_status_610122_idx',
            old_name='core_resume_status_fb_idx',
        ),
        migrations.RenameIndex(
            model_name='resumefeedback',
            new_name='core_resume_reviewe_7fdbbe_idx',
            old_name='core_resume_reviewe_fb_idx',
        ),
        migrations.RenameIndex(
            model_name='resumeshare',
            new_name='core_resume_share_t_5aa5d2_idx',
            old_name='core_resum_share_t_idx',
        ),
        migrations.RenameIndex(
            model_name='resumeshare',
            new_name='core_resume_resume__527f39_idx',
            old_name='core_resum_resume_v_idx',
        ),
        migrations.RenameIndex(
            model_name='resumeshare',
            new_name='core_resume_is_acti_5ef0f7_idx',
            old_name='core_resum_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='shareaccesslog',
            new_name='core_sharea_share_i_c8e017_idx',
            old_name='core_share_share_a_idx',
        ),
        migrations.RenameIndex(
            model_name='shareaccesslog',
            new_name='core_sharea_reviewe_08506b_idx',
            old_name='core_share_reviewe_idx',
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='company_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.DeleteModel(
            name='ReferralOutcome',
        ),
        migrations.DeleteModel(
            name='ReferralRequest',
        ),
    ]
