# Generated by Django 5.2.8 on 2025-11-29 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_remove_referraloutcome_referral_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('behavioral', 'Behavioral'), ('technical', 'Technical'), ('case_study', 'Case Study'), ('mixed', 'Mixed')], default='behavioral', max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('question_count', models.PositiveIntegerField(default=5)),
                ('difficulty_level', models.CharField(default='mid', max_length=20)),
                ('focus_areas', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_duration_seconds', models.PositiveIntegerField(default=0)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('areas_for_improvement', models.JSONField(blank=True, default=list)),
                ('ai_summary', models.TextField(blank=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_sessions', to='core.jobentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MockInterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('question_category', models.CharField(blank=True, max_length=50)),
                ('suggested_framework', models.CharField(blank=True, max_length=50)),
                ('ideal_answer_points', models.JSONField(blank=True, default=list)),
                ('user_answer', models.TextField(blank=True)),
                ('answer_timestamp', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('answer_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('improvements', models.JSONField(blank=True, default=list)),
                ('keyword_coverage', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.mockinterviewsession')),
            ],
            options={
                'ordering': ['session', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='MockInterviewSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_by_category', models.JSONField(blank=True, default=dict)),
                ('response_quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('communication_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('structure_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('top_strengths', models.JSONField(blank=True, default=list)),
                ('critical_areas', models.JSONField(blank=True, default=list)),
                ('recommended_practice_topics', models.JSONField(blank=True, default=list)),
                ('next_steps', models.JSONField(blank=True, default=list)),
                ('overall_assessment', models.TextField(blank=True)),
                ('readiness_level', models.CharField(blank=True, max_length=20)),
                ('estimated_interview_readiness', models.PositiveIntegerField(blank=True, null=True)),
                ('compared_to_previous_sessions', models.JSONField(blank=True, default=dict)),
                ('improvement_trend', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='core.mockinterviewsession')),
            ],
            options={
                'verbose_name_plural': 'Mock interview summaries',
            },
        ),
        migrations.AddIndex(
            model_name='mockinterviewsession',
            index=models.Index(fields=['user', 'status'], name='core_mockin_user_id_647b77_idx'),
        ),
        migrations.AddIndex(
            model_name='mockinterviewsession',
            index=models.Index(fields=['user', '-started_at'], name='core_mockin_user_id_240cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='mockinterviewquestion',
            index=models.Index(fields=['session', 'question_number'], name='core_mockin_session_b9c6d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mockinterviewquestion',
            unique_together={('session', 'question_number')},
        ),
    ]
