# Generated by Django 5.2.8 on 2025-11-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_mock_interview_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobentry',
            name='application_method',
            field=models.CharField(blank=True, choices=[('online_form', 'Online Application Form'), ('email', 'Email'), ('referral', 'Internal Referral'), ('recruiter', 'Through Recruiter'), ('direct_contact', 'Direct Contact'), ('other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='application_source',
            field=models.CharField(blank=True, choices=[('company_website', 'Company Website'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('referral', 'Referral'), ('recruiter', 'Recruiter'), ('job_board', 'Job Board'), ('networking', 'Networking Event'), ('other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='application_submitted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='company_size',
            field=models.CharField(blank=True, choices=[('startup', 'Startup (1-50)'), ('small', 'Small (51-200)'), ('medium', 'Medium (201-1000)'), ('large', 'Large (1001-5000)'), ('enterprise', 'Enterprise (5000+)')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='cover_letter_customized',
            field=models.BooleanField(default=False, help_text='Was the cover letter customized for this application?'),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='days_to_response',
            field=models.IntegerField(blank=True, help_text='Days from application to first response', null=True),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='resume_customized',
            field=models.BooleanField(default=False, help_text='Was the resume customized for this application?'),
        ),
    ]
