# Generated by Django 5.2.8 on 2025-11-30 06:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_sync_uc097_jobentry_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationalInterview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('identified', 'Candidate Identified'), ('outreach_sent', 'Outreach Sent'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('declined', 'Declined'), ('no_response', 'No Response')], default='identified', max_length=20)),
                ('outreach_template_used', models.CharField(blank=True, help_text='Template type used for outreach', max_length=50)),
                ('outreach_sent_at', models.DateTimeField(blank=True, null=True)),
                ('outreach_message', models.TextField(blank=True, help_text='Actual outreach message sent')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Interview date and time', null=True)),
                ('meeting_location', models.CharField(blank=True, help_text='Physical location or video link', max_length=500)),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Expected duration')),
                ('preparation_notes', models.TextField(blank=True, help_text='User preparation notes')),
                ('questions_to_ask', models.JSONField(blank=True, default=list, help_text='List of prepared questions')),
                ('research_notes', models.TextField(blank=True, help_text='Research about the contact/company')),
                ('goals', models.JSONField(blank=True, default=list, help_text='What user wants to learn/achieve')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('', 'Not Yet Recorded'), ('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], default='', max_length=20)),
                ('interview_notes', models.TextField(blank=True, help_text='Notes taken during/after interview')),
                ('key_insights', models.JSONField(blank=True, default=list, help_text='Key takeaways and insights')),
                ('industry_intelligence', models.TextField(blank=True, help_text='Industry trends and intelligence gathered')),
                ('follow_up_sent_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_message', models.TextField(blank=True)),
                ('relationship_strength_change', models.IntegerField(default=0, help_text='Change in relationship strength (-5 to +5)')),
                ('future_opportunities', models.JSONField(blank=True, default=list, help_text='Potential opportunities identified')),
                ('led_to_job_application', models.BooleanField(default=False)),
                ('led_to_referral', models.BooleanField(default=False)),
                ('led_to_introduction', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-scheduled_at', '-created_at'],
            },
        ),
        # Note: RenameIndex operations commented out to allow migrations to work on fresh databases
        # These indexes will use the new naming convention from migration 0055
        # migrations.RenameIndex(
        #     model_name='interviewsuccessprediction',
        #     new_name='core_interv_intervi_9bc100_idx',
        #     old_name='core_succ_pred_interview_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='interviewsuccessprediction',
        #     new_name='core_interv_candida_178a75_idx',
        #     old_name='core_succ_pred_candidate_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='interviewsuccessprediction',
        #     new_name='core_interv_job_id_1a36cc_idx',
        #     old_name='core_succ_pred_job_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='interviewsuccessprediction',
        #     new_name='core_interv_is_late_d6548a_idx',
        #     old_name='core_succ_pred_latest_idx',
        # ),
        migrations.AddField(
            model_name='informationalinterview',
            name='connected_jobs',
            field=models.ManyToManyField(blank=True, related_name='from_informational_interviews', to='core.jobentry'),
        ),
        migrations.AddField(
            model_name='informationalinterview',
            name='contact',
            field=models.ForeignKey(help_text='The contact being interviewed', on_delete=django.db.models.deletion.CASCADE, related_name='informational_interviews', to='core.contact'),
        ),
        migrations.AddField(
            model_name='informationalinterview',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='informational_interviews', to='core.tag'),
        ),
        migrations.AddField(
            model_name='informationalinterview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informational_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='informationalinterview',
            index=models.Index(fields=['user', 'status'], name='core_inform_user_id_820dba_idx'),
        ),
        migrations.AddIndex(
            model_name='informationalinterview',
            index=models.Index(fields=['user', '-scheduled_at'], name='core_inform_user_id_5508cb_idx'),
        ),
        migrations.AddIndex(
            model_name='informationalinterview',
            index=models.Index(fields=['contact', 'status'], name='core_inform_contact_54eb7c_idx'),
        ),
    ]
