# Generated by Django 5.2.8 on 2025-11-30 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_rename_core_succ_pred_interview_idx_core_interv_intervi_9bc100_idx_and_more'),
        ('core', '0069_uc090_informational_interviews'),
    ]

    operations = [
    ]
