# Generated by Django 5.2.8 on 2025-11-30 17:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_merge_20251130_1218'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverySearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_companies', models.JSONField(blank=True, default=list)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('target_industries', models.JSONField(blank=True, default=list)),
                ('target_locations', models.JSONField(blank=True, default=list)),
                ('include_alumni', models.BooleanField(default=True)),
                ('include_mutual_connections', models.BooleanField(default=True)),
                ('include_industry_leaders', models.BooleanField(default=True)),
                ('results_count', models.IntegerField(default=0)),
                ('contacted_count', models.IntegerField(default=0)),
                ('connected_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_refreshed', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Discovery searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggested_name', models.CharField(max_length=255)),
                ('suggested_title', models.CharField(blank=True, max_length=220)),
                ('suggested_company', models.CharField(blank=True, max_length=180)),
                ('suggested_linkedin_url', models.URLField(blank=True)),
                ('suggested_location', models.CharField(blank=True, max_length=160)),
                ('suggested_industry', models.CharField(blank=True, max_length=120)),
                ('suggestion_type', models.CharField(choices=[('target_company', 'Target Company Employee'), ('alumni', 'Alumni Connection'), ('industry_leader', 'Industry Leader/Influencer'), ('mutual_connection', '2nd/3rd Degree Connection'), ('conference_speaker', 'Conference Speaker/Event Participant'), ('similar_role', 'Similar Role Professional')], max_length=30)),
                ('relevance_score', models.FloatField(default=0.0, help_text='0.0-1.0 relevance score')),
                ('reason', models.TextField(help_text='Why this contact is suggested')),
                ('connection_path', models.JSONField(blank=True, default=list, help_text='List of intermediary contacts')),
                ('mutual_connections', models.JSONField(blank=True, default=list)),
                ('shared_institution', models.CharField(blank=True, max_length=200)),
                ('shared_degree', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('contacted', 'Contacted'), ('connected', 'Connected'), ('dismissed', 'Dismissed')], default='suggested', max_length=20)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_from_suggestion', to='core.contact')),
                ('related_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company')),
                ('related_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_suggestions', to='core.jobopportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-relevance_score', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-relevance_score'], name='core_contac_user_id_035ce8_idx'), models.Index(fields=['user', 'suggestion_type', '-created_at'], name='core_contac_user_id_2c8626_idx'), models.Index(fields=['-relevance_score'], name='core_contac_relevan_d9bd1d_idx')],
            },
        ),
    ]
