# Generated by Django 5.2.8 on 2025-11-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_supporter_chat'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supporterchatmessage',
            new_name='core_suppor_candida_d69f26_idx',
            old_name='core_suppo_candidat_5dd3e8_idx',
        ),
        migrations.RenameIndex(
            model_name='supporterencouragement',
            new_name='core_suppor_candida_e37c4e_idx',
            old_name='core_suppo_candidat_3dca1b_idx',
        ),
        migrations.RenameIndex(
            model_name='supporterinvite',
            new_name='core_suppor_candida_6fe7ba_idx',
            old_name='core_suppo_candidat_4bef1c_idx',
        ),
        migrations.RenameIndex(
            model_name='supporterinvite',
            new_name='core_suppor_email_9a83f3_idx',
            old_name='core_suppo_email_77b443_idx',
        ),
    ]
