# Generated by Django 5.2.8 on 2025-11-30 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_add_outcome_comp_fields'),
        ('core', '0071_uc092_contact_discovery'),
    ]

    operations = [
    ]
