# Generated by Django 5.2.8 on 2025-12-02 20:31

from django.db import migrations


def _rename_linked_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    statements = [
        "ALTER INDEX IF EXISTS core_linked_user_id_idx RENAME TO core_linked_user_id_c0550f_idx;",
        "ALTER INDEX IF EXISTS core_linked_user_id_c0550f_idx RENAME TO core_linked_user_id_idx;",
        "ALTER INDEX IF EXISTS core_linked_linkedin_id_idx RENAME TO core_linked_linkedi_290f08_idx;",
        "ALTER INDEX IF EXISTS core_linked_linkedi_290f08_idx RENAME TO core_linked_linkedin_id_idx;",
    ]
    with schema_editor.connection.cursor() as cursor:
        # Execute in pairs to keep behavior similar to forward/reverse blocks
        cursor.execute(statements[0])
        cursor.execute(statements[2])


def _rename_linked_indexes_reverse(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    statements = [
        "ALTER INDEX IF EXISTS core_linked_user_id_c0550f_idx RENAME TO core_linked_user_id_idx;",
        "ALTER INDEX IF EXISTS core_linked_linkedi_290f08_idx RENAME TO core_linked_linkedin_id_idx;",
    ]
    with schema_editor.connection.cursor() as cursor:
        for sql in statements:
            cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_merge_linkedin_and_features'),
    ]

    operations = [
        migrations.RunPython(
            code=_rename_linked_indexes,
            reverse_code=_rename_linked_indexes_reverse,
        ),
    ]
