# Generated by Django 5.2.8 on 2025-11-30 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_add_outcome_comp_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupporterInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('last_access_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporter_invites', to='core.candidateprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupporterEncouragement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supporter_name', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporter_encouragements', to='core.candidateprofile')),
                ('supporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encouragements', to='core.supporterinvite')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supporterencouragement',
            index=models.Index(fields=['candidate', '-created_at'], name='core_suppo_candidat_3dca1b_idx'),
        ),
        migrations.AddIndex(
            model_name='supporterinvite',
            index=models.Index(fields=['candidate', 'is_active'], name='core_suppo_candidat_4bef1c_idx'),
        ),
        migrations.AddIndex(
            model_name='supporterinvite',
            index=models.Index(fields=['email'], name='core_suppo_email_77b443_idx'),
        ),
    ]
