# Generated by Django 5.2.8 on 2025-11-30 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_supporter_invites'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupporterChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('supporter', 'Supporter'), ('candidate', 'Candidate')], max_length=20)),
                ('sender_name', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporter_messages', to='core.candidateprofile')),
                ('supporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.supporterinvite')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supporterchatmessage',
            index=models.Index(fields=['candidate', '-created_at'], name='core_suppo_candidat_5dd3e8_idx'),
        ),
    ]
