# Generated by Django 5.2.8 on 2025-11-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_supporter_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='supporter_mood_note',
            field=models.TextField(blank=True, help_text='Optional note on how the candidate is feeling for supporters'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='supporter_mood_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional 1-10 score for supporter visibility', null=True),
        ),
    ]
