# Generated by Django 5.2.8 on 2025-11-30 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_uc090_informational_interviews'),
        ('core', '0075_supporter_mood'),
    ]

    operations = [
    ]
