# Generated by Django 5.2.8 on 2025-11-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_merge_20251130_1636'),
        ('core', '0077_supporter_index_state'),
    ]

    operations = [
    ]
