# Generated by Django 5.2.8 on 2025-12-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_merge_20251130_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeshare',
            name='allow_edit',
            field=models.BooleanField(
                default=False,
                help_text='Allow reviewers to edit the resume themselves'
            ),
        ),
        migrations.AlterField(
            model_name='shareaccesslog',
            name='action',
            field=models.CharField(
                choices=[
                    ('view', 'Viewed'),
                    ('download', 'Downloaded'),
                    ('comment', 'Commented'),
                    ('edit', 'Edited'),
                ],
                default='view',
                max_length=20
            ),
        ),
    ]
