# Generated by Django 5.2.8 on 2025-12-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_add_resume_share_allow_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsuggestion',
            name='connection_path',
            field=models.JSONField(blank=True, default=list, help_text='Intermediate contacts'),
        ),
        migrations.AlterField(
            model_name='contactsuggestion',
            name='suggestion_type',
            field=models.CharField(choices=[('target_company', 'Target Company Employee'), ('alumni', 'Alumni Connection'), ('industry_leader', 'Industry Leader/Influencer'), ('mutual_connection', 'Mutual Connection'), ('conference_speaker', 'Conference Speaker/Event Participant'), ('similar_role', 'Similar Role Professional')], max_length=30),
        ),
    ]
