# Generated by Django 5.2.8 on 2025-12-02 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_resume_feedback_cover_letter'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='resumefeedback',
            new_name='core_resume_resume__c74ce1_idx',
            old_name='core_resumefeedback_resume_version_0c3a71_idx',
        ),
        migrations.RenameIndex(
            model_name='resumefeedback',
            new_name='core_resume_cover_l_ac04d1_idx',
            old_name='core_resumefeedback_cover_letter_d_5ab3d9_idx',
        ),
        migrations.RenameIndex(
            model_name='resumefeedback',
            new_name='core_resume_share_i_4f59d5_idx',
            old_name='core_resumefeedback_share_92935d_idx',
        ),
        migrations.RenameIndex(
            model_name='resumefeedback',
            new_name='core_resume_status_610122_idx',
            old_name='core_resumefeedback_status_03b13a_idx',
        ),
        migrations.RenameIndex(
            model_name='resumefeedback',
            new_name='core_resume_reviewe_7fdbbe_idx',
            old_name='core_resumefeedback_review_2a84fb_idx',
        ),
        migrations.AlterField(
            model_name='resumeshare',
            name='resume_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.resumeversion'),
        ),
    ]
