# Generated by Django 5.2.8 on 2025-12-02 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_rename_core_linked_user_id_idx_core_linked_user_id_c0550f_idx_and_more'),
        ('core', '0083_rename_core_resumefeedback_resume_version_0c3a71_idx_core_resume_resume__c74ce1_idx_and_more'),
    ]

    operations = [
    ]
