# Generated by Django 5.2.8 on 2025-12-02 23:26

from django.conf import settings
from django.db import migrations, models


def safe_rename_index(old_name, new_name):
    """Generate SQL to safely rename an index, handling cases where it may already be renamed."""
    return f"""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = '{old_name}') THEN
                ALTER INDEX "{old_name}" RENAME TO "{new_name}";
            END IF;
        END $$;
    """


def noop_reverse(old_name, new_name):
    """Generate SQL to rename back (for reverse migration)."""
    return f"""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = '{new_name}') THEN
                ALTER INDEX "{new_name}" RENAME TO "{old_name}";
            END IF;
        END $$;
    """


def safe_remove_constraint(table_name, constraint_name):
    """Generate SQL to safely remove a constraint if it exists."""
    return f"""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.table_constraints 
                WHERE constraint_name = '{constraint_name}' AND table_name = '{table_name}'
            ) THEN
                ALTER TABLE "{table_name}" DROP CONSTRAINT "{constraint_name}";
            END IF;
        END $$;
    """


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_merge_20251202_1900'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Remove constraints safely
        migrations.RunSQL(
            safe_remove_constraint('core_teamcandidateaccess', 'core_teamcandidate_team_cand_member_uniq'),
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            safe_remove_constraint('core_teammembership', 'core_teammembership_team_user_uniq'),
            migrations.RunSQL.noop,
        ),
        # Rename indexes safely - LinkedInIntegration
        migrations.RunSQL(
            safe_rename_index('core_linked_user_id_idx', 'core_linked_user_id_c0550f_idx'),
            noop_reverse('core_linked_user_id_idx', 'core_linked_user_id_c0550f_idx'),
        ),
        migrations.RunSQL(
            safe_rename_index('core_linked_linkedin_id_idx', 'core_linked_linkedi_290f08_idx'),
            noop_reverse('core_linked_linkedin_id_idx', 'core_linked_linkedi_290f08_idx'),
        ),
        # TeamAccount
        migrations.RunSQL(
            safe_rename_index('core_teamac_owner_c1fe62_idx', 'core_teamac_owner_i_b66d84_idx'),
            noop_reverse('core_teamac_owner_c1fe62_idx', 'core_teamac_owner_i_b66d84_idx'),
        ),
        migrations.RunSQL(
            safe_rename_index('core_teamac_subscri_5df6f4_idx', 'core_teamac_subscri_2eb392_idx'),
            noop_reverse('core_teamac_subscri_5df6f4_idx', 'core_teamac_subscri_2eb392_idx'),
        ),
        # TeamCandidateAccess
        migrations.RunSQL(
            safe_rename_index('core_teamcan_team_id_a24e14_idx', 'core_teamca_team_id_514ea0_idx'),
            noop_reverse('core_teamcan_team_id_a24e14_idx', 'core_teamca_team_id_514ea0_idx'),
        ),
        migrations.RunSQL(
            safe_rename_index('core_teamcan_team_id_3f814f_idx', 'core_teamca_team_id_854e7a_idx'),
            noop_reverse('core_teamcan_team_id_3f814f_idx', 'core_teamca_team_id_854e7a_idx'),
        ),
        # TeamInvitation
        migrations.RunSQL(
            safe_rename_index('core_teamin_team_id_2e101d_idx', 'core_teamin_team_id_5ecc95_idx'),
            noop_reverse('core_teamin_team_id_2e101d_idx', 'core_teamin_team_id_5ecc95_idx'),
        ),
        migrations.RunSQL(
            safe_rename_index('core_teamin_email_031d6b_idx', 'core_teamin_email_5c2405_idx'),
            noop_reverse('core_teamin_email_031d6b_idx', 'core_teamin_email_5c2405_idx'),
        ),
        # TeamMembership
        migrations.RunSQL(
            safe_rename_index('core_teammem_team_id_930156_idx', 'core_teamme_team_id_31ddcd_idx'),
            noop_reverse('core_teammem_team_id_930156_idx', 'core_teamme_team_id_31ddcd_idx'),
        ),
        migrations.RunSQL(
            safe_rename_index('core_teammem_team_id_3e0925_idx', 'core_teamme_team_id_683f95_idx'),
            noop_reverse('core_teammem_team_id_3e0925_idx', 'core_teamme_team_id_683f95_idx'),
        ),
        migrations.RunSQL(
            safe_rename_index('core_teammem_user_id_3c5672_idx', 'core_teamme_user_id_18ce5c_idx'),
            noop_reverse('core_teammem_user_id_3c5672_idx', 'core_teamme_user_id_18ce5c_idx'),
        ),
        # TeamMessage
        migrations.RunSQL(
            safe_rename_index('core_teammem_team_id_fc0b5d_idx', 'core_teamme_team_id_f5dd70_idx'),
            noop_reverse('core_teammem_team_id_fc0b5d_idx', 'core_teamme_team_id_f5dd70_idx'),
        ),
        # AlterField operations
        migrations.AlterField(
            model_name='teamaccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teamcandidateaccess',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teammessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='teamcandidateaccess',
            unique_together={('team', 'candidate', 'granted_to')},
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('team', 'user')},
        ),
    ]
