# Generated by Django 5.2.8 on 2025-12-06 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_teamsharedjob_teamjobcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gmail_message_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('thread_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField()),
                ('snippet', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('email_type', models.CharField(choices=[('application_sent', 'Application Sent'), ('acknowledgment', 'Application Acknowledged'), ('recruiter_outreach', 'Recruiter Outreach'), ('interview_invitation', 'Interview Invitation'), ('interview_confirmation', 'Interview Confirmation'), ('interview_reminder', 'Interview Reminder'), ('rejection', 'Rejection'), ('offer', 'Offer Letter'), ('follow_up', 'Follow-up'), ('other', 'Other')], default='other', max_length=30)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_application_related', models.BooleanField(default=False)),
                ('suggested_job_status', models.CharField(blank=True, max_length=20)),
                ('status_applied', models.BooleanField(default=False)),
                ('is_linked', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('user_notes', models.TextField(blank=True)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('emails_processed', models.IntegerField(default=0)),
                ('emails_matched', models.IntegerField(default=0)),
                ('emails_linked', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GmailIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('gmail_address', models.EmailField(blank=True, max_length=254)),
                ('gmail_history_id', models.CharField(blank=True, max_length=100)),
                ('scan_enabled', models.BooleanField(default=False)),
                ('scan_frequency', models.CharField(choices=[('realtime', 'Real-time (as received)'), ('hourly', 'Every Hour'), ('daily', 'Daily'), ('manual', 'Manual Only')], default='daily', max_length=20)),
                ('auto_update_status', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('pending', 'Pending Authorization'), ('connected', 'Connected'), ('scanning', 'Scanning'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('last_scan_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('emails_scanned_count', models.IntegerField(default=0)),
                ('state_token', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        # These constraints were already removed in migration 0086
        # migrations.RemoveConstraint(
        #     model_name='teamcandidateaccess',
        #     name='core_teamcandidate_team_cand_member_uniq',
        # ),
        # migrations.RemoveConstraint(
        #     model_name='teammembership',
        #     name='core_teammembership_team_user_uniq',
        # ),
        # These index renames were already done or are not needed
        # migrations.RenameIndex(
        #     model_name='linkedinintegration',
        #     new_name='core_linked_user_id_c0550f_idx',
        #     old_name='core_linked_user_id_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='linkedinintegration',
        #     new_name='core_linked_linkedi_290f08_idx',
        #     old_name='core_linked_linkedin_id_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='teamaccount',
        #     new_name='core_teamac_owner_i_b66d84_idx',
        #     old_name='core_teamac_owner_c1fe62_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='teamaccount',
        #     new_name='core_teamac_subscri_2eb392_idx',
        #     old_name='core_teamac_subscri_5df6f4_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='teamcandidateaccess',
        #     new_name='core_teamca_team_id_514ea0_idx',
        #     old_name='core_teamcan_team_id_a24e14_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='teamcandidateaccess',
        #     new_name='core_teamca_team_id_854e7a_idx',
        #     old_name='core_teamcan_team_id_3f814f_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='teaminvitation',
        #     new_name='core_teamin_team_id_5ecc95_idx',
        #     old_name='core_teamin_team_id_2e101d_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='teaminvitation',
        #     new_name='core_teamin_email_5c2405_idx',
        #     old_name='core_teamin_email_031d6b_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='teammembership',
        #     new_name='core_teamme_team_id_31ddcd_idx',
        #     old_name='core_teammem_team_id_930156_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='teammembership',
        #     new_name='core_teamme_team_id_683f95_idx',
        #     old_name='core_teammem_team_id_3e0925_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='teammembership',
        #     new_name='core_teamme_user_id_18ce5c_idx',
        #     old_name='core_teammem_user_id_3c5672_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='teammessage',
        #     new_name='core_teamme_team_id_f5dd70_idx',
        #     old_name='core_teammem_team_id_fc0b5d_idx',
        # ),
        migrations.AddField(
            model_name='applicationemail',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.jobentry'),
        ),
        migrations.AddField(
            model_name='applicationemail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gmailintegration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_integration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailscanlog',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='core.gmailintegration'),
        ),
        migrations.AddIndex(
            model_name='applicationemail',
            index=models.Index(fields=['user', '-received_at'], name='core_applic_user_id_ff3a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationemail',
            index=models.Index(fields=['job', '-received_at'], name='core_applic_job_id_625fde_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationemail',
            index=models.Index(fields=['is_application_related', '-received_at'], name='core_applic_is_appl_c5a0c3_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationemail',
            index=models.Index(fields=['gmail_message_id'], name='core_applic_gmail_m_db9dae_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationemail',
            index=models.Index(fields=['thread_id'], name='core_applic_thread__82f751_idx'),
        ),
        migrations.AddIndex(
            model_name='gmailintegration',
            index=models.Index(fields=['user'], name='core_gmaili_user_id_d153a2_idx'),
        ),
        migrations.AddIndex(
            model_name='gmailintegration',
            index=models.Index(fields=['status', 'scan_enabled'], name='core_gmaili_status_1304d4_idx'),
        ),
        migrations.AddIndex(
            model_name='emailscanlog',
            index=models.Index(fields=['integration', '-started_at'], name='core_emails_integra_1d2783_idx'),
        ),
    ]
