# Generated by Django 5.2.8 on 2025-12-06 22:14

from django.db import migrations


def remove_constraint_if_exists(apps, schema_editor, table_name, constraint_name):
    """Remove a constraint if it exists (PostgreSQL only)."""
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"""
            SELECT 1 FROM information_schema.table_constraints 
            WHERE constraint_name = '{constraint_name}' AND table_name = '{table_name}'
        """)
        if cursor.fetchone():
            cursor.execute(f'ALTER TABLE "{table_name}" DROP CONSTRAINT "{constraint_name}"')


def rename_index_if_exists(apps, schema_editor, old_name, new_name):
    """Rename an index if it exists (PostgreSQL only)."""
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"""
            SELECT 1 FROM pg_indexes WHERE indexname = '{old_name}'
        """)
        if cursor.fetchone():
            cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')


def reverse_noop(apps, schema_editor):
    """No-op reverse migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_gmailintegration_rate_limit_reset_at'),
    ]

    operations = [
        # Remove constraints safely
        migrations.RunPython(
            lambda apps, schema_editor: remove_constraint_if_exists(
                apps, schema_editor, 'core_teamcandidateaccess', 'core_teamcandidate_team_cand_member_uniq'
            ),
            reverse_noop,
        ),
        migrations.RunPython(
            lambda apps, schema_editor: remove_constraint_if_exists(
                apps, schema_editor, 'core_teammembership', 'core_teammembership_team_user_uniq'
            ),
            reverse_noop,
        ),
        # Rename indexes safely - LinkedInIntegration
        migrations.RunPython(
            lambda apps, schema_editor: rename_index_if_exists(
                apps, schema_editor, 'core_linked_user_id_idx', 'core_linked_user_id_c0550f_idx'
            ),
            reverse_noop,
        ),
        migrations.RunPython(
            lambda apps, schema_editor: rename_index_if_exists(
                apps, schema_editor, 'core_linked_linkedin_id_idx', 'core_linked_linkedi_290f08_idx'
            ),
            reverse_noop,
        ),
        # TeamAccount
        migrations.RunPython(
            lambda apps, schema_editor: rename_index_if_exists(
                apps, schema_editor, 'core_teamac_owner_c1fe62_idx', 'core_teamac_owner_i_b66d84_idx'
            ),
            reverse_noop,
        ),
        migrations.RunPython(
            lambda apps, schema_editor: rename_index_if_exists(
                apps, schema_editor, 'core_teamac_subscri_5df6f4_idx', 'core_teamac_subscri_2eb392_idx'
            ),
            reverse_noop,
        ),
        # TeamCandidateAccess
        migrations.RunPython(
            lambda apps, schema_editor: rename_index_if_exists(
                apps, schema_editor, 'core_teamcan_team_id_a24e14_idx', 'core_teamca_team_id_514ea0_idx'
            ),
            reverse_noop,
        ),
        migrations.RunPython(
            lambda apps, schema_editor: rename_index_if_exists(
                apps, schema_editor, 'core_teamcan_team_id_3f814f_idx', 'core_teamca_team_id_854e7a_idx'
            ),
            reverse_noop,
        ),
        # TeamInvitation
        migrations.RunPython(
            lambda apps, schema_editor: rename_index_if_exists(
                apps, schema_editor, 'core_teamin_team_id_2e101d_idx', 'core_teamin_team_id_5ecc95_idx'
            ),
            reverse_noop,
        ),
        migrations.RunPython(
            lambda apps, schema_editor: rename_index_if_exists(
                apps, schema_editor, 'core_teamin_email_031d6b_idx', 'core_teamin_email_5c2405_idx'
            ),
            reverse_noop,
        ),
        # TeamMembership
        migrations.RunPython(
            lambda apps, schema_editor: rename_index_if_exists(
                apps, schema_editor, 'core_teammem_team_id_930156_idx', 'core_teamme_team_id_31ddcd_idx'
            ),
            reverse_noop,
        ),
        migrations.RunPython(
            lambda apps, schema_editor: rename_index_if_exists(
                apps, schema_editor, 'core_teammem_team_id_3e0925_idx', 'core_teamme_team_id_683f95_idx'
            ),
            reverse_noop,
        ),
        migrations.RunPython(
            lambda apps, schema_editor: rename_index_if_exists(
                apps, schema_editor, 'core_teammem_user_id_3c5672_idx', 'core_teamme_user_id_18ce5c_idx'
            ),
            reverse_noop,
        ),
        # TeamMessage
        migrations.RunPython(
            lambda apps, schema_editor: rename_index_if_exists(
                apps, schema_editor, 'core_teammem_team_id_fc0b5d_idx', 'core_teamme_team_id_f5dd70_idx'
            ),
            reverse_noop,
        ),
    ]
