# Generated by Django 5.2.8 on 2025-12-06 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_gmailintegration_rate_limit_reset_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teamcandidateaccess',
            name='core_teamcandidate_team_cand_member_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='teammembership',
            name='core_teammembership_team_user_uniq',
        ),
        migrations.RenameIndex(
            model_name='linkedinintegration',
            new_name='core_linked_user_id_c0550f_idx',
            old_name='core_linked_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='linkedinintegration',
            new_name='core_linked_linkedi_290f08_idx',
            old_name='core_linked_linkedin_id_idx',
        ),
        migrations.RenameIndex(
            model_name='teamaccount',
            new_name='core_teamac_owner_i_b66d84_idx',
            old_name='core_teamac_owner_c1fe62_idx',
        ),
        migrations.RenameIndex(
            model_name='teamaccount',
            new_name='core_teamac_subscri_2eb392_idx',
            old_name='core_teamac_subscri_5df6f4_idx',
        ),
        migrations.RenameIndex(
            model_name='teamcandidateaccess',
            new_name='core_teamca_team_id_514ea0_idx',
            old_name='core_teamcan_team_id_a24e14_idx',
        ),
        migrations.RenameIndex(
            model_name='teamcandidateaccess',
            new_name='core_teamca_team_id_854e7a_idx',
            old_name='core_teamcan_team_id_3f814f_idx',
        ),
        migrations.RenameIndex(
            model_name='teaminvitation',
            new_name='core_teamin_team_id_5ecc95_idx',
            old_name='core_teamin_team_id_2e101d_idx',
        ),
        migrations.RenameIndex(
            model_name='teaminvitation',
            new_name='core_teamin_email_5c2405_idx',
            old_name='core_teamin_email_031d6b_idx',
        ),
        migrations.RenameIndex(
            model_name='teammembership',
            new_name='core_teamme_team_id_31ddcd_idx',
            old_name='core_teammem_team_id_930156_idx',
        ),
        migrations.RenameIndex(
            model_name='teammembership',
            new_name='core_teamme_team_id_683f95_idx',
            old_name='core_teammem_team_id_3e0925_idx',
        ),
        migrations.RenameIndex(
            model_name='teammembership',
            new_name='core_teamme_user_id_18ce5c_idx',
            old_name='core_teammem_user_id_3c5672_idx',
        ),
        migrations.RenameIndex(
            model_name='teammessage',
            new_name='core_teamme_team_id_f5dd70_idx',
            old_name='core_teammem_team_id_fc0b5d_idx',
        ),
    ]
