# Generated by Django 5.2.8 on 2025-12-07 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_remove_teamcandidateaccess_core_teamcandidate_team_cand_member_uniq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('service_type', models.CharField(choices=[('gemini', 'Google Gemini AI'), ('gmail', 'Gmail API'), ('google_calendar', 'Google Calendar'), ('google_contacts', 'Google Contacts'), ('linkedin', 'LinkedIn API'), ('github', 'GitHub API'), ('openai', 'OpenAI API'), ('market_data', 'Market Data APIs'), ('other', 'Other API Service')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('rate_limit_enabled', models.BooleanField(default=True)),
                ('requests_per_minute', models.IntegerField(blank=True, help_text='Max requests per minute', null=True)),
                ('requests_per_hour', models.IntegerField(blank=True, help_text='Max requests per hour', null=True)),
                ('requests_per_day', models.IntegerField(blank=True, help_text='Max requests per day', null=True)),
                ('alert_threshold_warning', models.IntegerField(default=75, help_text='Warning threshold %')),
                ('alert_threshold_critical', models.IntegerField(default=90, help_text='Critical threshold %')),
                ('is_active', models.BooleanField(default=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['service_type', 'is_active'], name='core_apiser_service_a07727_idx'), models.Index(fields=['-last_error_at'], name='core_apiser_last_er_7911f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='API endpoint called', max_length=500)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('request_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('request_data', models.JSONField(blank=True, default=dict, help_text='Sanitized request data')),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Sanitized response data')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional tracking metadata')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='core.apiservice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_at'],
            },
        ),
        migrations.CreateModel(
            name='APIError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(db_index=True, max_length=100)),
                ('error_message', models.TextField()),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('endpoint', models.CharField(max_length=500)),
                ('request_method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('affected_users_count', models.IntegerField(default=0)),
                ('retry_count', models.IntegerField(default=0)),
                ('stack_trace', models.TextField(blank=True)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_api_errors', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='core.apiservice')),
                ('usage_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.apiusagelog')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='APIWeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True)),
                ('week_end', models.DateField()),
                ('total_requests', models.IntegerField(default=0)),
                ('total_errors', models.IntegerField(default=0)),
                ('error_rate', models.FloatField(default=0.0, help_text='Error rate as percentage')),
                ('avg_response_time_ms', models.FloatField(default=0.0)),
                ('service_stats', models.JSONField(default=dict, help_text='Per-service statistics')),
                ('top_errors', models.JSONField(default=list, help_text='Most common errors')),
                ('services_approaching_limit', models.JSONField(default=list, help_text='Services near quota')),
                ('total_alerts', models.IntegerField(default=0)),
                ('critical_alerts', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('html_content', models.TextField(blank=True)),
                ('summary_text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-week_start'],
                'indexes': [models.Index(fields=['-week_start'], name='core_apiwee_week_st_f15b34_idx')],
                'unique_together': {('week_start', 'week_end')},
            },
        ),
        migrations.CreateModel(
            name='APIQuotaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=20)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField()),
                ('total_requests', models.IntegerField(default=0)),
                ('successful_requests', models.IntegerField(default=0)),
                ('failed_requests', models.IntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(blank=True, null=True)),
                ('max_response_time_ms', models.IntegerField(blank=True, null=True)),
                ('min_response_time_ms', models.IntegerField(blank=True, null=True)),
                ('quota_limit', models.IntegerField(blank=True, null=True)),
                ('quota_remaining', models.IntegerField(blank=True, null=True)),
                ('quota_percentage_used', models.FloatField(blank=True, null=True)),
                ('alert_level', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('critical', 'Critical'), ('exceeded', 'Exceeded')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_usage', to='core.apiservice')),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['service', 'period_type', '-period_start'], name='core_apiquo_service_95612d_idx'), models.Index(fields=['alert_level', '-period_start'], name='core_apiquo_alert_l_8351a2_idx')],
                'unique_together': {('service', 'period_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='APIAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('quota_warning', 'Quota Warning'), ('quota_critical', 'Quota Critical'), ('quota_exceeded', 'Quota Exceeded'), ('high_error_rate', 'High Error Rate'), ('service_down', 'Service Down'), ('slow_response', 'Slow Response Time')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_api_alerts', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.apiservice')),
            ],
            options={
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['service', '-triggered_at'], name='core_apiale_service_4537cd_idx'), models.Index(fields=['alert_type', 'is_resolved'], name='core_apiale_alert_t_022002_idx'), models.Index(fields=['is_acknowledged', '-triggered_at'], name='core_apiale_is_ackn_35f6e4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['service', '-request_at'], name='core_apiusa_service_19622f_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['user', '-request_at'], name='core_apiusa_user_id_1d2888_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['success', '-request_at'], name='core_apiusa_success_7a8181_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['-request_at'], name='core_apiusa_request_8b1569_idx'),
        ),
        migrations.AddIndex(
            model_name='apierror',
            index=models.Index(fields=['service', '-occurred_at'], name='core_apierr_service_51df03_idx'),
        ),
        migrations.AddIndex(
            model_name='apierror',
            index=models.Index(fields=['error_type', '-occurred_at'], name='core_apierr_error_t_64c685_idx'),
        ),
        migrations.AddIndex(
            model_name='apierror',
            index=models.Index(fields=['is_resolved', '-occurred_at'], name='core_apierr_is_reso_770e1b_idx'),
        ),
    ]
