# Generated by Django 5.2.8 on 2025-12-06 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_teamsharedjob_teamjobcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GitHubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_user_id', models.BigIntegerField(unique=True)),
                ('login', models.CharField(max_length=255)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('access_token', models.CharField(max_length=255)),
                ('token_type', models.CharField(blank=True, default='', max_length=64)),
                ('scopes', models.CharField(blank=True, default='', max_length=512)),
                ('include_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('html_url', models.URLField()),
                ('private', models.BooleanField(default=False)),
                ('primary_language', models.CharField(blank=True, default='', max_length=128)),
                ('languages', models.JSONField(blank=True, default=dict)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('forks', models.PositiveIntegerField(default=0)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        # The following constraints were already removed in migration 0086.
        # Removing them again causes failures on some databases.
        # If needed, reintroduce conditional removal via RunSQL with IF EXISTS.
        # Skipping index rename operations due to missing old index names on this database.
        migrations.AddField(
            model_name='featuredrepository',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_repositories', to='core.candidateprofile'),
        ),
        migrations.AddField(
            model_name='githubaccount',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_account', to='core.candidateprofile'),
        ),
        migrations.AddField(
            model_name='repository',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='core.githubaccount'),
        ),
        migrations.AddField(
            model_name='featuredrepository',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_for', to='core.repository'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['account', '-stars'], name='core_reposi_account_eaea68_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['account', '-pushed_at'], name='core_reposi_account_fa8974_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('account', 'repo_id')},
        ),
        migrations.AddIndex(
            model_name='featuredrepository',
            index=models.Index(fields=['candidate', 'position'], name='core_featur_candida_162a7a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featuredrepository',
            unique_together={('candidate', 'repository')},
        ),
    ]
