# Generated by Django 5.2.8 on 2025-12-12 02:33

from django.db import migrations


def remove_fields_if_exist(apps, schema_editor):
    """Safely remove fields that may or may not exist."""
    connection = schema_editor.connection
    vendor = connection.vendor  # 'postgresql', 'sqlite', etc.
    
    fields_to_remove = [
        ('core_gmailintegration', 'auto_update_status'),
        ('core_gmailintegration', 'scan_frequency'),
    ]
    
    for table_name, column_name in fields_to_remove:
        with connection.cursor() as cursor:
            # Check if column exists using database-specific query
            if vendor == 'postgresql':
                cursor.execute("""
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = %s AND column_name = %s
                """, [table_name, column_name])
                column_exists = cursor.fetchone() is not None
            else:
                # SQLite: use PRAGMA table_info
                cursor.execute(f"PRAGMA table_info({table_name})")
                columns = [row[1] for row in cursor.fetchall()]
                column_exists = column_name in columns
            
            if column_exists:
                if vendor == 'postgresql':
                    cursor.execute(f'ALTER TABLE "{table_name}" DROP COLUMN "{column_name}"')
                # SQLite does not support DROP COLUMN in older versions; skip for SQLite
                # as the column will just be unused


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_remove_teamcandidateaccess_core_teamcandidate_team_cand_member_uniq_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_fields_if_exist, noop),
    ]
