# Generated by Django 5.2.8 on 2025-12-12 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_remove_teamcandidateaccess_core_teamcandidate_team_cand_member_uniq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmailintegration',
            name='auto_update_status',
        ),
        migrations.RemoveField(
            model_name='gmailintegration',
            name='scan_frequency',
        ),
    ]
