# Generated by Django 5.2.8 on 2025-12-12 02:33

from django.db import migrations


def remove_fields_if_exist(apps, schema_editor):
    """Safely remove fields that may or may not exist."""
    connection = schema_editor.connection
    
    fields_to_remove = [
        ('core_gmailintegration', 'auto_update_status'),
        ('core_gmailintegration', 'scan_frequency'),
    ]
    
    for table_name, column_name in fields_to_remove:
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT 1 FROM information_schema.columns
                WHERE table_name = %s AND column_name = %s
            """, [table_name, column_name])
            if cursor.fetchone():
                cursor.execute(f'ALTER TABLE "{table_name}" DROP COLUMN "{column_name}"')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_remove_teamcandidateaccess_core_teamcandidate_team_cand_member_uniq_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_fields_if_exist, noop),
    ]
