# Generated by Django 5.2.8 on 2025-12-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_merge_20251208_0000'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                'ALTER TABLE "core_teamcandidateaccess" '
                'DROP CONSTRAINT IF EXISTS "core_teamcandidate_team_cand_member_uniq";'
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=(
                'ALTER TABLE "core_teammembership" '
                'DROP CONSTRAINT IF EXISTS "core_teammembership_team_user_uniq";'
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql='ALTER INDEX IF EXISTS "core_linked_user_id_idx" RENAME TO "core_linked_user_id_c0550f_idx";',
            reverse_sql='ALTER INDEX IF EXISTS "core_linked_user_id_c0550f_idx" RENAME TO "core_linked_user_id_idx";',
        ),
        migrations.RunSQL(
            sql='ALTER INDEX IF EXISTS "core_linked_linkedin_id_idx" RENAME TO "core_linked_linkedi_290f08_idx";',
            reverse_sql='ALTER INDEX IF EXISTS "core_linked_linkedi_290f08_idx" RENAME TO "core_linked_linkedin_id_idx";',
        ),
        migrations.RunSQL(
            sql='ALTER INDEX IF EXISTS "core_teamac_owner_c1fe62_idx" RENAME TO "core_teamac_owner_i_b66d84_idx";',
            reverse_sql='ALTER INDEX IF EXISTS "core_teamac_owner_i_b66d84_idx" RENAME TO "core_teamac_owner_c1fe62_idx";',
        ),
        migrations.RunSQL(
            sql='ALTER INDEX IF EXISTS "core_teamac_subscri_5df6f4_idx" RENAME TO "core_teamac_subscri_2eb392_idx";',
            reverse_sql='ALTER INDEX IF EXISTS "core_teamac_subscri_2eb392_idx" RENAME TO "core_teamac_subscri_5df6f4_idx";',
        ),
        migrations.RunSQL(
            sql='ALTER INDEX IF EXISTS "core_teamcan_team_id_a24e14_idx" RENAME TO "core_teamca_team_id_514ea0_idx";',
            reverse_sql='ALTER INDEX IF EXISTS "core_teamca_team_id_514ea0_idx" RENAME TO "core_teamcan_team_id_a24e14_idx";',
        ),
        migrations.RunSQL(
            sql='ALTER INDEX IF EXISTS "core_teamcan_team_id_3f814f_idx" RENAME TO "core_teamca_team_id_854e7a_idx";',
            reverse_sql='ALTER INDEX IF EXISTS "core_teamca_team_id_854e7a_idx" RENAME TO "core_teamcan_team_id_3f814f_idx";',
        ),
        migrations.RunSQL(
            sql='ALTER INDEX IF EXISTS "core_teamin_team_id_2e101d_idx" RENAME TO "core_teamin_team_id_5ecc95_idx";',
            reverse_sql='ALTER INDEX IF EXISTS "core_teamin_team_id_5ecc95_idx" RENAME TO "core_teamin_team_id_2e101d_idx";',
        ),
        migrations.RunSQL(
            sql='ALTER INDEX IF EXISTS "core_teamin_email_031d6b_idx" RENAME TO "core_teamin_email_5c2405_idx";',
            reverse_sql='ALTER INDEX IF EXISTS "core_teamin_email_5c2405_idx" RENAME TO "core_teamin_email_031d6b_idx";',
        ),
        migrations.RunSQL(
            sql='ALTER INDEX IF EXISTS "core_teammem_team_id_930156_idx" RENAME TO "core_teamme_team_id_31ddcd_idx";',
            reverse_sql='ALTER INDEX IF EXISTS "core_teamme_team_id_31ddcd_idx" RENAME TO "core_teammem_team_id_930156_idx";',
        ),
        migrations.RunSQL(
            sql='ALTER INDEX IF EXISTS "core_teammem_team_id_3e0925_idx" RENAME TO "core_teamme_team_id_683f95_idx";',
            reverse_sql='ALTER INDEX IF EXISTS "core_teamme_team_id_683f95_idx" RENAME TO "core_teammem_team_id_3e0925_idx";',
        ),
        migrations.RunSQL(
            sql='ALTER INDEX IF EXISTS "core_teammem_user_id_3c5672_idx" RENAME TO "core_teamme_user_id_18ce5c_idx";',
            reverse_sql='ALTER INDEX IF EXISTS "core_teamme_user_id_18ce5c_idx" RENAME TO "core_teammem_user_id_3c5672_idx";',
        ),
        migrations.RunSQL(
            sql='ALTER INDEX IF EXISTS "core_teammem_team_id_fc0b5d_idx" RENAME TO "core_teamme_team_id_f5dd70_idx";',
            reverse_sql='ALTER INDEX IF EXISTS "core_teamme_team_id_f5dd70_idx" RENAME TO "core_teammem_team_id_fc0b5d_idx";',
        ),
    ]
