# Generated by Django 5.2.8 on 2025-12-08 19:30

from django.db import migrations


def _run_postgres_schema_updates(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    statements = [
        'ALTER TABLE "core_teamcandidateaccess" DROP CONSTRAINT IF EXISTS "core_teamcandidate_team_cand_member_uniq";',
        'ALTER TABLE "core_teammembership" DROP CONSTRAINT IF EXISTS "core_teammembership_team_user_uniq";',
        'ALTER INDEX IF EXISTS "core_linked_user_id_idx" RENAME TO "core_linked_user_id_c0550f_idx";',
        'ALTER INDEX IF EXISTS "core_linked_linkedin_id_idx" RENAME TO "core_linked_linkedi_290f08_idx";',
        'ALTER INDEX IF EXISTS "core_teamac_owner_c1fe62_idx" RENAME TO "core_teamac_owner_i_b66d84_idx";',
        'ALTER INDEX IF EXISTS "core_teamac_subscri_5df6f4_idx" RENAME TO "core_teamac_subscri_2eb392_idx";',
        'ALTER INDEX IF EXISTS "core_teamcan_team_id_a24e14_idx" RENAME TO "core_teamca_team_id_514ea0_idx";',
        'ALTER INDEX IF EXISTS "core_teamcan_team_id_3f814f_idx" RENAME TO "core_teamca_team_id_854e7a_idx";',
        'ALTER INDEX IF EXISTS "core_teamin_team_id_2e101d_idx" RENAME TO "core_teamin_team_id_5ecc95_idx";',
        'ALTER INDEX IF EXISTS "core_teamin_email_031d6b_idx" RENAME TO "core_teamin_email_5c2405_idx";',
        'ALTER INDEX IF EXISTS "core_teammem_team_id_930156_idx" RENAME TO "core_teamme_team_id_31ddcd_idx";',
        'ALTER INDEX IF EXISTS "core_teammem_team_id_3e0925_idx" RENAME TO "core_teamme_team_id_683f95_idx";',
        'ALTER INDEX IF EXISTS "core_teammem_user_id_3c5672_idx" RENAME TO "core_teamme_user_id_18ce5c_idx";',
        'ALTER INDEX IF EXISTS "core_teammem_team_id_fc0b5d_idx" RENAME TO "core_teamme_team_id_f5dd70_idx";',
    ]
    with schema_editor.connection.cursor() as cursor:
        for sql in statements:
            cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_merge_20251208_0000'),
    ]

    operations = [
        migrations.RunPython(
            code=_run_postgres_schema_updates,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
