# Generated by Django 5.2.8 on 2025-12-08 19:30

from django.db import migrations


def postgresql_only_operations(apps, schema_editor):
    """Execute PostgreSQL-specific SQL operations."""
    if schema_editor.connection.vendor != 'postgresql':
        return
    
    with schema_editor.connection.cursor() as cursor:
        # Drop constraints
        cursor.execute('ALTER TABLE "core_teamcandidateaccess" DROP CONSTRAINT IF EXISTS "core_teamcandidate_team_cand_member_uniq";')
        cursor.execute('ALTER TABLE "core_teammembership" DROP CONSTRAINT IF EXISTS "core_teammembership_team_user_uniq";')
        
        # Rename indexes
        cursor.execute('ALTER INDEX IF EXISTS "core_linked_user_id_idx" RENAME TO "core_linked_user_id_c0550f_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_linked_linkedin_id_idx" RENAME TO "core_linked_linkedi_290f08_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_teamac_owner_c1fe62_idx" RENAME TO "core_teamac_owner_i_b66d84_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_teamac_subscri_5df6f4_idx" RENAME TO "core_teamac_subscri_2eb392_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_teamcan_team_id_a24e14_idx" RENAME TO "core_teamca_team_id_514ea0_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_teamcan_team_id_3f814f_idx" RENAME TO "core_teamca_team_id_854e7a_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_teamin_team_id_2e101d_idx" RENAME TO "core_teamin_team_id_5ecc95_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_teamin_email_031d6b_idx" RENAME TO "core_teamin_email_5c2405_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_teammem_team_id_930156_idx" RENAME TO "core_teamme_team_id_31ddcd_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_teammem_team_id_3e0925_idx" RENAME TO "core_teamme_team_id_683f95_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_teammem_user_id_3c5672_idx" RENAME TO "core_teamme_user_id_18ce5c_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_teammem_team_id_fc0b5d_idx" RENAME TO "core_teamme_team_id_f5dd70_idx";')


def reverse_postgresql_operations(apps, schema_editor):
    """Reverse PostgreSQL-specific SQL operations."""
    if schema_editor.connection.vendor != 'postgresql':
        return
    
    with schema_editor.connection.cursor() as cursor:
        # Reverse index renames
        cursor.execute('ALTER INDEX IF EXISTS "core_linked_user_id_c0550f_idx" RENAME TO "core_linked_user_id_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_linked_linkedi_290f08_idx" RENAME TO "core_linked_linkedin_id_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_teamac_owner_i_b66d84_idx" RENAME TO "core_teamac_owner_c1fe62_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_teamac_subscri_2eb392_idx" RENAME TO "core_teamac_subscri_5df6f4_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_teamca_team_id_514ea0_idx" RENAME TO "core_teamcan_team_id_a24e14_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_teamca_team_id_854e7a_idx" RENAME TO "core_teamcan_team_id_3f814f_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_teamin_team_id_5ecc95_idx" RENAME TO "core_teamin_team_id_2e101d_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_teamin_email_5c2405_idx" RENAME TO "core_teamin_email_031d6b_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_teamme_team_id_31ddcd_idx" RENAME TO "core_teammem_team_id_930156_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_teamme_team_id_683f95_idx" RENAME TO "core_teammem_team_id_3e0925_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_teamme_user_id_18ce5c_idx" RENAME TO "core_teammem_user_id_3c5672_idx";')
        cursor.execute('ALTER INDEX IF EXISTS "core_teamme_team_id_f5dd70_idx" RENAME TO "core_teammem_team_id_fc0b5d_idx";')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_merge_20251208_0000'),
    ]

    operations = [
        migrations.RunPython(postgresql_only_operations, reverse_postgresql_operations),
    ]
