# Generated by Django 5.2.8 on 2025-12-12 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_remove_scan_frequency_and_auto_status'),
        ('core', '0105_remove_teamcandidateaccess_core_teamcandidate_team_cand_member_uniq_and_more'),
    ]

    operations = [
    ]
