# Generated by Django 5.2.8 on 2025-12-12 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_merge_20251211_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('application_deadline', 'Application Deadline'), ('application_followup', 'Application Follow-up'), ('interview_followup', 'Interview Follow-up'), ('offer_response', 'Offer Response'), ('thank_you', 'Thank You Note'), ('status_inquiry', 'Status Inquiry')], max_length=30)),
                ('subject', models.CharField(help_text='Email subject or reminder title', max_length=200)),
                ('message_template', models.TextField(help_text='Template message with placeholders')),
                ('scheduled_datetime', models.DateTimeField(help_text='When to send the reminder')),
                ('interval_days', models.PositiveSmallIntegerField(blank=True, help_text='Days between reminders for recurring', null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('max_occurrences', models.PositiveSmallIntegerField(default=1, help_text='Maximum times to send')),
                ('occurrence_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('dismissed', 'Dismissed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('response_received', models.BooleanField(default=False)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField(help_text='When to submit the application')),
                ('timezone', models.CharField(default='UTC', help_text="User's timezone for scheduling", max_length=50)),
                ('submission_method', models.CharField(default='email', help_text='How to submit (email, portal, etc.)', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('submitted', 'Submitted'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='Submission priority (1=highest)')),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('submission_parameters', models.JSONField(default=dict, help_text='Parameters for submission')),
                ('submission_result', models.JSONField(default=dict, help_text='Result of submission attempt')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='Day of week when submitted (0=Monday, 6=Sunday)', null=True)),
                ('hour_of_day', models.PositiveSmallIntegerField(blank=True, help_text='Hour of day when submitted (0-23)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheduled_datetime', 'priority'],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "core_teamcandidateaccess" '
                        'DROP CONSTRAINT IF EXISTS "core_teamcandidate_team_cand_member_uniq";'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='teamcandidateaccess',
                    name='core_teamcandidate_team_cand_member_uniq',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "core_teammembership" '
                        'DROP CONSTRAINT IF EXISTS "core_teammembership_team_user_uniq";'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='teammembership',
                    name='core_teammembership_team_user_uniq',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER INDEX IF EXISTS "core_linked_user_id_idx" RENAME TO "core_linked_user_id_c0550f_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "core_linked_user_id_c0550f_idx" RENAME TO "core_linked_user_id_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='linkedinintegration',
                    new_name='core_linked_user_id_c0550f_idx',
                    old_name='core_linked_user_id_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER INDEX IF EXISTS "core_linked_linkedin_id_idx" RENAME TO "core_linked_linkedi_290f08_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "core_linked_linkedi_290f08_idx" RENAME TO "core_linked_linkedin_id_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='linkedinintegration',
                    new_name='core_linked_linkedi_290f08_idx',
                    old_name='core_linked_linkedin_id_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER INDEX IF EXISTS "core_teamac_owner_c1fe62_idx" RENAME TO "core_teamac_owner_i_b66d84_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "core_teamac_owner_i_b66d84_idx" RENAME TO "core_teamac_owner_c1fe62_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='teamaccount',
                    new_name='core_teamac_owner_i_b66d84_idx',
                    old_name='core_teamac_owner_c1fe62_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER INDEX IF EXISTS "core_teamac_subscri_5df6f4_idx" RENAME TO "core_teamac_subscri_2eb392_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "core_teamac_subscri_2eb392_idx" RENAME TO "core_teamac_subscri_5df6f4_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='teamaccount',
                    new_name='core_teamac_subscri_2eb392_idx',
                    old_name='core_teamac_subscri_5df6f4_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER INDEX IF EXISTS "core_teamcan_team_id_a24e14_idx" RENAME TO "core_teamca_team_id_514ea0_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "core_teamca_team_id_514ea0_idx" RENAME TO "core_teamcan_team_id_a24e14_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='teamcandidateaccess',
                    new_name='core_teamca_team_id_514ea0_idx',
                    old_name='core_teamcan_team_id_a24e14_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER INDEX IF EXISTS "core_teamcan_team_id_3f814f_idx" RENAME TO "core_teamca_team_id_854e7a_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "core_teamca_team_id_854e7a_idx" RENAME TO "core_teamcan_team_id_3f814f_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='teamcandidateaccess',
                    new_name='core_teamca_team_id_854e7a_idx',
                    old_name='core_teamcan_team_id_3f814f_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER INDEX IF EXISTS "core_teamin_team_id_2e101d_idx" RENAME TO "core_teamin_team_id_5ecc95_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "core_teamin_team_id_5ecc95_idx" RENAME TO "core_teamin_team_id_2e101d_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='teaminvitation',
                    new_name='core_teamin_team_id_5ecc95_idx',
                    old_name='core_teamin_team_id_2e101d_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER INDEX IF EXISTS "core_teamin_email_031d6b_idx" RENAME TO "core_teamin_email_5c2405_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "core_teamin_email_5c2405_idx" RENAME TO "core_teamin_email_031d6b_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='teaminvitation',
                    new_name='core_teamin_email_5c2405_idx',
                    old_name='core_teamin_email_031d6b_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER INDEX IF EXISTS "core_teammem_team_id_930156_idx" RENAME TO "core_teamme_team_id_31ddcd_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "core_teamme_team_id_31ddcd_idx" RENAME TO "core_teammem_team_id_930156_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='teammembership',
                    new_name='core_teamme_team_id_31ddcd_idx',
                    old_name='core_teammem_team_id_930156_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER INDEX IF EXISTS "core_teammem_team_id_3e0925_idx" RENAME TO "core_teamme_team_id_683f95_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "core_teamme_team_id_683f95_idx" RENAME TO "core_teammem_team_id_3e0925_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='teammembership',
                    new_name='core_teamme_team_id_683f95_idx',
                    old_name='core_teammem_team_id_3e0925_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER INDEX IF EXISTS "core_teammem_user_id_3c5672_idx" RENAME TO "core_teamme_user_id_18ce5c_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "core_teamme_user_id_18ce5c_idx" RENAME TO "core_teammem_user_id_3c5672_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='teammembership',
                    new_name='core_teamme_user_id_18ce5c_idx',
                    old_name='core_teammem_user_id_3c5672_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER INDEX IF EXISTS "core_teammem_team_id_fc0b5d_idx" RENAME TO "core_teamme_team_id_f5dd70_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "core_teamme_team_id_f5dd70_idx" RENAME TO "core_teammem_team_id_fc0b5d_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='teammessage',
                    new_name='core_teamme_team_id_f5dd70_idx',
                    old_name='core_teammem_team_id_fc0b5d_idx',
                ),
            ],
        ),
        migrations.AddField(
            model_name='followupreminder',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_reminders', to='core.candidateprofile'),
        ),
        migrations.AddField(
            model_name='followupreminder',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_reminders', to='core.jobentry'),
        ),
        migrations.AddField(
            model_name='scheduledsubmission',
            name='application_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_submissions', to='core.applicationpackage'),
        ),
        migrations.AddField(
            model_name='scheduledsubmission',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_submissions', to='core.candidateprofile'),
        ),
        migrations.AddField(
            model_name='scheduledsubmission',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_submissions', to='core.jobentry'),
        ),
        migrations.AddIndex(
            model_name='followupreminder',
            index=models.Index(fields=['candidate', 'status'], name='core_follow_candida_fb1693_idx'),
        ),
        migrations.AddIndex(
            model_name='followupreminder',
            index=models.Index(fields=['scheduled_datetime', 'status'], name='core_follow_schedul_532f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='followupreminder',
            index=models.Index(fields=['job', 'reminder_type'], name='core_follow_job_id_a11895_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledsubmission',
            index=models.Index(fields=['candidate', 'status'], name='core_schedu_candida_0e7889_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledsubmission',
            index=models.Index(fields=['scheduled_datetime', 'status'], name='core_schedu_schedul_3aabb0_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledsubmission',
            index=models.Index(fields=['job', 'status'], name='core_schedu_job_id_8656b8_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledsubmission',
            index=models.Index(fields=['candidate', 'day_of_week'], name='core_schedu_candida_5ee1f3_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledsubmission',
            index=models.Index(fields=['candidate', 'hour_of_day'], name='core_schedu_candida_0ca095_idx'),
        ),
    ]
