# Generated by Django 5.2.8 on 2025-12-12 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_merge_20251211_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('application_deadline', 'Application Deadline'), ('application_followup', 'Application Follow-up'), ('interview_followup', 'Interview Follow-up'), ('offer_response', 'Offer Response'), ('thank_you', 'Thank You Note'), ('status_inquiry', 'Status Inquiry')], max_length=30)),
                ('subject', models.CharField(help_text='Email subject or reminder title', max_length=200)),
                ('message_template', models.TextField(help_text='Template message with placeholders')),
                ('scheduled_datetime', models.DateTimeField(help_text='When to send the reminder')),
                ('interval_days', models.PositiveSmallIntegerField(blank=True, help_text='Days between reminders for recurring', null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('max_occurrences', models.PositiveSmallIntegerField(default=1, help_text='Maximum times to send')),
                ('occurrence_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('dismissed', 'Dismissed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('response_received', models.BooleanField(default=False)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField(help_text='When to submit the application')),
                ('timezone', models.CharField(default='UTC', help_text="User's timezone for scheduling", max_length=50)),
                ('submission_method', models.CharField(default='email', help_text='How to submit (email, portal, etc.)', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('submitted', 'Submitted'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='Submission priority (1=highest)')),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('submission_parameters', models.JSONField(default=dict, help_text='Parameters for submission')),
                ('submission_result', models.JSONField(default=dict, help_text='Result of submission attempt')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='Day of week when submitted (0=Monday, 6=Sunday)', null=True)),
                ('hour_of_day', models.PositiveSmallIntegerField(blank=True, help_text='Hour of day when submitted (0-23)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheduled_datetime', 'priority'],
            },
        ),
        migrations.AddField(
            model_name='followupreminder',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_reminders', to='core.candidateprofile'),
        ),
        migrations.AddField(
            model_name='followupreminder',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_reminders', to='core.jobentry'),
        ),
        migrations.AddField(
            model_name='scheduledsubmission',
            name='application_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_submissions', to='core.applicationpackage'),
        ),
        migrations.AddField(
            model_name='scheduledsubmission',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_submissions', to='core.candidateprofile'),
        ),
        migrations.AddField(
            model_name='scheduledsubmission',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_submissions', to='core.jobentry'),
        ),
        migrations.AddIndex(
            model_name='followupreminder',
            index=models.Index(fields=['candidate', 'status'], name='core_follow_candida_fb1693_idx'),
        ),
        migrations.AddIndex(
            model_name='followupreminder',
            index=models.Index(fields=['scheduled_datetime', 'status'], name='core_follow_schedul_532f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='followupreminder',
            index=models.Index(fields=['job', 'reminder_type'], name='core_follow_job_id_a11895_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledsubmission',
            index=models.Index(fields=['candidate', 'status'], name='core_schedu_candida_0e7889_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledsubmission',
            index=models.Index(fields=['scheduled_datetime', 'status'], name='core_schedu_schedul_3aabb0_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledsubmission',
            index=models.Index(fields=['job', 'status'], name='core_schedu_job_id_8656b8_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledsubmission',
            index=models.Index(fields=['candidate', 'day_of_week'], name='core_schedu_candida_5ee1f3_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledsubmission',
            index=models.Index(fields=['candidate', 'hour_of_day'], name='core_schedu_candida_0ca095_idx'),
        ),
    ]
