# Generated by Django 5.2.8 on 2025-12-12 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_followupreminder_scheduledsubmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledsubmission',
            name='application_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_submissions', to='core.applicationpackage'),
        ),
    ]
