# Generated by Django 5.2.8 on 2025-12-13 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_make_application_package_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerGrowthScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.CharField(help_text='User-defined name for this scenario', max_length=200)),
                ('scenario_type', models.CharField(choices=[('conservative', 'Conservative Growth'), ('expected', 'Expected Growth'), ('optimistic', 'Optimistic Growth')], default='expected', max_length=20)),
                ('starting_salary', models.DecimalField(decimal_places=2, help_text='Initial base salary', max_digits=12)),
                ('annual_bonus_percent', models.DecimalField(decimal_places=2, default=0, help_text='Annual bonus as % of salary', max_digits=5)),
                ('equity_value', models.DecimalField(decimal_places=2, default=0, help_text='Total equity value', max_digits=12)),
                ('equity_vesting_years', models.IntegerField(default=4, help_text='Years over which equity vests')),
                ('annual_raise_percent', models.DecimalField(decimal_places=2, help_text='Expected annual raise %', max_digits=5)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('milestones', models.JSONField(blank=True, default=list, help_text='List of career milestones: [{year, title, salary_increase_percent, promotion_bonus, notes}]')),
                ('projections_5_year', models.JSONField(blank=True, default=dict, help_text='Year-by-year breakdown for 5 years')),
                ('projections_10_year', models.JSONField(blank=True, default=dict, help_text='Year-by-year breakdown for 10 years')),
                ('total_comp_5_year', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_comp_10_year', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, help_text='General notes about this scenario')),
                ('career_goals_notes', models.TextField(blank=True, help_text='Notes about non-financial career goals')),
                ('work_life_balance_score', models.PositiveSmallIntegerField(blank=True, help_text='1-10 score', null=True)),
                ('growth_opportunity_score', models.PositiveSmallIntegerField(blank=True, help_text='1-10 score', null=True)),
                ('culture_fit_score', models.PositiveSmallIntegerField(blank=True, help_text='1-10 score', null=True)),
                ('market_salary_data', models.JSONField(blank=True, default=dict, help_text='External salary data from Glassdoor, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Active scenarios for comparison')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_scenarios', to='core.jobentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_career_user_id_acc928_idx'), models.Index(fields=['job'], name='core_career_job_id_142319_idx'), models.Index(fields=['is_active'], name='core_career_is_acti_3265b3_idx')],
            },
        ),
    ]
