# Generated by Django 5.2.8 on 2025-12-13 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_make_application_package_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewResponseLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('behavioral', 'Behavioral'), ('technical', 'Technical'), ('situational', 'Situational')], max_length=20)),
                ('current_response_text', models.TextField()),
                ('current_star_response', models.JSONField(blank=True, default=dict)),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of skills demonstrated')),
                ('experiences', models.JSONField(blank=True, default=list, help_text='List of experiences referenced')),
                ('companies_used_for', models.JSONField(blank=True, default=list, help_text='Companies this response was used for')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Custom tags for organization')),
                ('led_to_offer', models.BooleanField(default=False)),
                ('led_to_next_round', models.BooleanField(default=False)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0, help_text='Calculated success rate based on outcomes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('related_jobs', models.ManyToManyField(blank=True, related_name='linked_responses', to='core.jobentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_library', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('response_text', models.TextField()),
                ('star_response', models.JSONField(blank=True, default=dict)),
                ('change_notes', models.TextField(blank=True, help_text='Notes about what was improved')),
                ('coaching_score', models.FloatField(blank=True, help_text='AI coaching score if available', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coaching_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_versions', to='core.questionresponsecoaching')),
                ('response_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.interviewresponselibrary')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='interviewresponselibrary',
            index=models.Index(fields=['user', 'question_type'], name='core_interv_user_id_6fed39_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewresponselibrary',
            index=models.Index(fields=['user', '-updated_at'], name='core_interv_user_id_e2c8c1_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewresponselibrary',
            index=models.Index(fields=['user', 'led_to_offer'], name='core_interv_user_id_29ae18_idx'),
        ),
        migrations.AddIndex(
            model_name='responseversion',
            index=models.Index(fields=['response_library', '-version_number'], name='core_respon_respons_00da73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='responseversion',
            unique_together={('response_library', 'version_number')},
        ),
    ]
