# Generated by Django 5.2.8 on 2025-12-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_interviewresponselibrary_responseversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockinterviewsession',
            name='difficulty_level',
            field=models.CharField(default='mid', max_length=50),
        ),
    ]
