# Generated by Django 5.2.8 on 2025-12-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_add_career_growth_calculator'),
        ('core', '0110_increase_difficulty_level_length'),
    ]

    operations = [
    ]
