# Generated by Django 5.2.8 on 2025-12-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_alter_jobmaterialshistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('last_commute_eta_min', models.FloatField(blank=True, null=True)),
                ('last_commute_distance_km', models.FloatField(blank=True, null=True)),
                ('last_commute_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_locations', to='core.jobentry')),
            ],
        ),
        migrations.AddIndex(
            model_name='jobofficelocation',
            index=models.Index(fields=['job'], name='core_jol_job_idx'),
        ),
        migrations.AddIndex(
            model_name='jobofficelocation',
            index=models.Index(fields=['job', 'created_at'], name='core_jol_job_created_idx'),
        ),
    ]
