# Generated by Django 5.2.8 on 2025-12-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_add_certification_details'),
        ('core', '0112_job_offers'),
    ]

    operations = [
    ]
