# Generated by Django 5.2.8 on 2025-12-14 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_merge_20251213_1333'),
        ('core', '0114_update_careergrowthscenario_fields'),
    ]

    operations = [
    ]
