# Generated by Django 5.2.8 on 2025-12-15 01:00

from django.db import migrations, models


def _index_exists(cursor, index_name, vendor):
    """Check if an index exists."""
    if vendor == 'postgresql':
        cursor.execute("SELECT 1 FROM pg_class WHERE relname = %s", [index_name])
        return cursor.fetchone() is not None
    else:
        # SQLite: check sqlite_master
        cursor.execute("SELECT 1 FROM sqlite_master WHERE type='index' AND name=?", [index_name])
        return cursor.fetchone() is not None


def rename_indexes_forward(apps, schema_editor):
    """Rename indexes (PostgreSQL only - SQLite doesn't support ALTER INDEX)."""
    connection = schema_editor.connection
    vendor = connection.vendor
    
    if vendor != 'postgresql':
        # SQLite doesn't support ALTER INDEX; skip these operations
        return
    
    renames = [
        ('core_applic_candidat_39cc77_idx', 'core_applic_candida_3c42f0_idx'),
        ('core_applic_job_id_a5a6ba_idx', 'core_applic_job_id_1e5f25_idx'),
        ('core_applic_candidat_ba38a1_idx', 'core_applic_candida_e1666c_idx'),
        ('core_follow_job_id_stg_idx', 'core_follow_job_id_c3206f_idx'),
        ('core_joboff_candidat_4fbb41_idx', 'core_joboff_candida_135e4a_idx'),
        ('core_joboff_candidat_6055e4_idx', 'core_joboff_candida_a61f93_idx'),
        ('core_joboff_status_5450a9_idx', 'core_joboff_status_3beac8_idx'),
    ]
    
    with connection.cursor() as cursor:
        for old_name, new_name in renames:
            if _index_exists(cursor, old_name, vendor):
                cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')


def rename_indexes_reverse(apps, schema_editor):
    """Reverse rename indexes (PostgreSQL only)."""
    connection = schema_editor.connection
    vendor = connection.vendor
    
    if vendor != 'postgresql':
        return
    
    renames = [
        ('core_applic_candida_3c42f0_idx', 'core_applic_candidat_39cc77_idx'),
        ('core_applic_job_id_1e5f25_idx', 'core_applic_job_id_a5a6ba_idx'),
        ('core_applic_candida_e1666c_idx', 'core_applic_candidat_ba38a1_idx'),
        ('core_follow_job_id_c3206f_idx', 'core_follow_job_id_stg_idx'),
        ('core_joboff_candida_135e4a_idx', 'core_joboff_candidat_4fbb41_idx'),
        ('core_joboff_candida_a61f93_idx', 'core_joboff_candidat_6055e4_idx'),
        ('core_joboff_status_3beac8_idx', 'core_joboff_status_5450a9_idx'),
    ]
    
    with connection.cursor() as cursor:
        for old_name, new_name in renames:
            if _index_exists(cursor, old_name, vendor):
                cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_material_version_comparison'),
    ]

    operations = [
        # Database-agnostic index renames (PostgreSQL only, no-op for SQLite)
        migrations.RunPython(rename_indexes_forward, rename_indexes_reverse),
        # Removed RemoveField operations for auto_update_status and scan_frequency
        # as these columns don't exist in the database
        # Removed AddField for rate_limit_reset_at as it already exists in the database
        migrations.AlterField(
            model_name='applicationqualityreview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
