# Generated by Django 5.2.8 on 2025-12-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_material_version_comparison'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='applicationqualityreview',
            new_name='core_applic_candida_3c42f0_idx',
            old_name='core_applic_candidat_39cc77_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationqualityreview',
            new_name='core_applic_job_id_1e5f25_idx',
            old_name='core_applic_job_id_a5a6ba_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationqualityreview',
            new_name='core_applic_candida_e1666c_idx',
            old_name='core_applic_candidat_ba38a1_idx',
        ),
        migrations.RenameIndex(
            model_name='followupreminder',
            new_name='core_follow_job_id_c3206f_idx',
            old_name='core_follow_job_id_stg_idx',
        ),
        migrations.RenameIndex(
            model_name='joboffer',
            new_name='core_joboff_candida_135e4a_idx',
            old_name='core_joboff_candidat_4fbb41_idx',
        ),
        migrations.RenameIndex(
            model_name='joboffer',
            new_name='core_joboff_candida_a61f93_idx',
            old_name='core_joboff_candidat_6055e4_idx',
        ),
        migrations.RenameIndex(
            model_name='joboffer',
            new_name='core_joboff_status_3beac8_idx',
            old_name='core_joboff_status_5450a9_idx',
        ),
        # Removed RemoveField operations for auto_update_status and scan_frequency
        # as these columns don't exist in the database
        # Removed AddField for rate_limit_reset_at as it already exists in the database
        migrations.AlterField(
            model_name='applicationqualityreview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
