# Generated by Django 5.2.8 on 2025-12-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_jobofficelocation_commute_cache'),
    ]

    operations = [
        # Guard rename operations: some environments no longer have these indexes.
        migrations.RunSQL(
            sql="DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'core_jol_job_idx') THEN ALTER INDEX core_jol_job_idx RENAME TO core_joboff_job_id_c6afcb_idx; END IF; END $$;",
            reverse_sql="-- no reverse"
        ),
        migrations.RunSQL(
            sql="DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'core_jol_job_created_idx') THEN ALTER INDEX core_jol_job_created_idx RENAME TO core_joboff_job_id_30477c_idx; END IF; END $$;",
            reverse_sql="-- no reverse"
        ),
        migrations.RunSQL(
            sql='ALTER TABLE core_gmailintegration DROP COLUMN IF EXISTS auto_update_status',
            reverse_sql='-- no reverse'
        ),
        migrations.RunSQL(
            sql='ALTER TABLE core_gmailintegration DROP COLUMN IF EXISTS scan_frequency',
            reverse_sql='-- no reverse'
        ),
        migrations.RunSQL(
            sql="ALTER TABLE core_gmailintegration ADD COLUMN IF NOT EXISTS rate_limit_reset_at timestamp with time zone",
            reverse_sql="ALTER TABLE core_gmailintegration DROP COLUMN IF EXISTS rate_limit_reset_at",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE core_jobentry ADD COLUMN IF NOT EXISTS location_geo_precision varchar(20)",
            reverse_sql="ALTER TABLE core_jobentry DROP COLUMN IF EXISTS location_geo_precision",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE core_jobentry ADD COLUMN IF NOT EXISTS location_geo_updated_at timestamp with time zone",
            reverse_sql="ALTER TABLE core_jobentry DROP COLUMN IF EXISTS location_geo_updated_at",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE core_jobentry ADD COLUMN IF NOT EXISTS location_lat double precision",
            reverse_sql="ALTER TABLE core_jobentry DROP COLUMN IF EXISTS location_lat",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE core_jobentry ADD COLUMN IF NOT EXISTS location_lon double precision",
            reverse_sql="ALTER TABLE core_jobentry DROP COLUMN IF EXISTS location_lon",
        ),
        migrations.AlterField(
            model_name='jobofficelocation',
            name='address',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='jobofficelocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobofficelocation',
            name='label',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
