# Generated by Django 5.2.8 on 2025-12-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_rename_core_applic_candidat_39cc77_idx_core_applic_candida_3c42f0_idx_and_more'),
        ('core', '0119_rename_core_jol_job_idx_core_joboff_job_id_c6afcb_idx_and_more'),
    ]

    operations = [
    ]
