# Generated by Django 5.2.8 on 2025-12-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_merge_20251215_1119'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='applicationqualityreview',
            new_name='core_applic_candida_3c42f0_idx',
            old_name='core_applic_candidat_39cc77_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationqualityreview',
            new_name='core_applic_job_id_1e5f25_idx',
            old_name='core_applic_job_id_a5a6ba_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationqualityreview',
            new_name='core_applic_candida_e1666c_idx',
            old_name='core_applic_candidat_ba38a1_idx',
        ),
        migrations.RenameIndex(
            model_name='followupreminder',
            new_name='core_follow_job_id_c3206f_idx',
            old_name='core_follow_job_id_stg_idx',
        ),
        migrations.RenameIndex(
            model_name='joboffer',
            new_name='core_joboff_candida_135e4a_idx',
            old_name='core_joboff_candidat_4fbb41_idx',
        ),
        migrations.RenameIndex(
            model_name='joboffer',
            new_name='core_joboff_candida_a61f93_idx',
            old_name='core_joboff_candidat_6055e4_idx',
        ),
        migrations.RenameIndex(
            model_name='joboffer',
            new_name='core_joboff_status_3beac8_idx',
            old_name='core_joboff_status_5450a9_idx',
        ),
        migrations.RenameIndex(
            model_name='jobofficelocation',
            new_name='core_joboff_job_id_c6afcb_idx',
            old_name='core_jol_job_idx',
        ),
        migrations.RenameIndex(
            model_name='jobofficelocation',
            new_name='core_joboff_job_id_30477c_idx',
            old_name='core_jol_job_created_idx',
        ),
        migrations.RemoveField(
            model_name='gmailintegration',
            name='auto_update_status',
        ),
        migrations.RemoveField(
            model_name='gmailintegration',
            name='scan_frequency',
        ),
        migrations.AddField(
            model_name='gmailintegration',
            name='rate_limit_reset_at',
            field=models.DateTimeField(blank=True, help_text='When the rate limit resets', null=True),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='location_geo_precision',
            field=models.CharField(blank=True, default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='location_geo_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='location_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
