# Generated by Django 5.2.8 on 2025-12-15 22:49

from django.db import migrations, models


def safe_remove_fields(apps, schema_editor):
    """Safely remove fields only if they exist (for fresh databases they won't)."""
    from django.db import connection
    with connection.cursor() as cursor:
        # Check if columns exist before trying to remove them
        cursor.execute("""
            SELECT column_name FROM information_schema.columns
            WHERE table_name = 'core_gmailintegration'
            AND column_name IN ('auto_update_status', 'scan_frequency')
        """)
        existing_cols = [row[0] for row in cursor.fetchall()]
        
        if 'auto_update_status' in existing_cols:
            cursor.execute('ALTER TABLE core_gmailintegration DROP COLUMN auto_update_status')
        if 'scan_frequency' in existing_cols:
            cursor.execute('ALTER TABLE core_gmailintegration DROP COLUMN scan_frequency')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_merge_20251215_1119'),
    ]

    operations = [
        # Safely remove old fields only if they exist
        migrations.RunPython(safe_remove_fields, migrations.RunPython.noop),
        migrations.AddField(
            model_name='gmailintegration',
            name='rate_limit_reset_at',
            field=models.DateTimeField(blank=True, help_text='When the rate limit will reset', null=True),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='location_geo_precision',
            field=models.CharField(blank=True, choices=[('exact', 'Exact Address'), ('street', 'Street Level'), ('city', 'City Level'), ('region', 'Region/State'), ('country', 'Country')], help_text='Precision level of geocoded location', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='location_geo_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time coordinates were updated', null=True),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='location_lat',
            field=models.FloatField(blank=True, help_text='Latitude coordinate for job location', null=True),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='location_lon',
            field=models.FloatField(blank=True, help_text='Longitude coordinate for job location', null=True),
        ),
    ]
