# Generated by Django 5.2.8 on 2025-12-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_merge_20251215_1119'),
    ]

    operations = [
        # Only add new fields, skip index renames to avoid issues with fresh databases
        migrations.RemoveField(
            model_name='gmailintegration',
            name='auto_update_status',
        ),
        migrations.RemoveField(
            model_name='gmailintegration',
            name='scan_frequency',
        ),
        migrations.AddField(
            model_name='gmailintegration',
            name='rate_limit_reset_at',
            field=models.DateTimeField(blank=True, help_text='When the rate limit will reset', null=True),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='location_geo_precision',
            field=models.CharField(blank=True, choices=[('exact', 'Exact Address'), ('street', 'Street Level'), ('city', 'City Level'), ('region', 'Region/State'), ('country', 'Country')], help_text='Precision level of geocoded location', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='location_geo_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time coordinates were updated', null=True),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='location_lat',
            field=models.FloatField(blank=True, help_text='Latitude coordinate for job location', null=True),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='location_lon',
            field=models.FloatField(blank=True, help_text='Longitude coordinate for job location', null=True),
        ),
    ]
