# Generated by Django 5.2.8 on 2025-12-15 22:49

from django.db import migrations, models


def safe_schema_changes(apps, schema_editor):
    """
    Idempotent migration: safely add/remove columns only if needed.
    Handles both fresh databases and partially migrated ones.
    """
    from django.db import connection
    with connection.cursor() as cursor:
        # Get existing columns for gmailintegration
        cursor.execute("""
            SELECT column_name FROM information_schema.columns
            WHERE table_name = 'core_gmailintegration'
        """)
        gmail_cols = {row[0] for row in cursor.fetchall()}
        
        # Get existing columns for jobentry
        cursor.execute("""
            SELECT column_name FROM information_schema.columns
            WHERE table_name = 'core_jobentry'
        """)
        job_cols = {row[0] for row in cursor.fetchall()}
        
        # Remove old gmail fields if they exist
        if 'auto_update_status' in gmail_cols:
            cursor.execute('ALTER TABLE core_gmailintegration DROP COLUMN auto_update_status')
        if 'scan_frequency' in gmail_cols:
            cursor.execute('ALTER TABLE core_gmailintegration DROP COLUMN scan_frequency')
        
        # Add new gmail fields if they don't exist
        if 'rate_limit_reset_at' not in gmail_cols:
            cursor.execute('ALTER TABLE core_gmailintegration ADD COLUMN rate_limit_reset_at TIMESTAMP NULL')
        
        # Add jobentry location fields if they don't exist
        if 'location_lat' not in job_cols:
            cursor.execute('ALTER TABLE core_jobentry ADD COLUMN location_lat DOUBLE PRECISION NULL')
        if 'location_lon' not in job_cols:
            cursor.execute('ALTER TABLE core_jobentry ADD COLUMN location_lon DOUBLE PRECISION NULL')
        if 'location_geo_precision' not in job_cols:
            cursor.execute('ALTER TABLE core_jobentry ADD COLUMN location_geo_precision VARCHAR(20) NULL')
        if 'location_geo_updated_at' not in job_cols:
            cursor.execute('ALTER TABLE core_jobentry ADD COLUMN location_geo_updated_at TIMESTAMP NULL')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_merge_20251215_1119'),
    ]

    operations = [
        # Single RunPython that handles all changes idempotently
        migrations.RunPython(safe_schema_changes, migrations.RunPython.noop),
    ]
