# Generated by Django 5.2.8 on 2025-12-16 04:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_add_jobentry_location_and_gmail_rate_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('staging', 'Staging'), ('production', 'Production')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('commit_sha', models.CharField(db_index=True, max_length=40)),
                ('commit_message', models.TextField(blank=True)),
                ('branch', models.CharField(default='main', max_length=255)),
                ('deployed_by', models.CharField(blank=True, help_text='GitHub username or system', max_length=100)),
                ('workflow_run_id', models.CharField(blank=True, help_text='GitHub Actions run ID', max_length=50)),
                ('frontend_url', models.URLField(blank=True)),
                ('backend_url', models.URLField(blank=True)),
                ('backend_deployment_id', models.CharField(blank=True, max_length=100)),
                ('frontend_deployment_id', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_rollback', models.BooleanField(default=False)),
                ('rollback_from_sha', models.CharField(blank=True, max_length=40)),
                ('rollback_reason', models.TextField(blank=True)),
                ('backend_tests_passed', models.BooleanField(blank=True, null=True)),
                ('frontend_tests_passed', models.BooleanField(blank=True, null=True)),
                ('test_coverage_backend', models.FloatField(blank=True, help_text='Backend test coverage percentage', null=True)),
                ('test_coverage_frontend', models.FloatField(blank=True, help_text='Frontend test coverage percentage', null=True)),
                ('health_check_passed', models.BooleanField(blank=True, null=True)),
                ('health_check_attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('step', models.CharField(blank=True, help_text='Deployment step name', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.RenameIndex(
            model_name='applicationqualityreview',
            new_name='core_applic_candida_3c42f0_idx',
            old_name='core_applic_candidat_39cc77_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationqualityreview',
            new_name='core_applic_job_id_1e5f25_idx',
            old_name='core_applic_job_id_a5a6ba_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationqualityreview',
            new_name='core_applic_candida_e1666c_idx',
            old_name='core_applic_candidat_ba38a1_idx',
        ),
        migrations.RenameIndex(
            model_name='followupreminder',
            new_name='core_follow_job_id_c3206f_idx',
            old_name='core_follow_job_id_stg_idx',
        ),
        migrations.RenameIndex(
            model_name='joboffer',
            new_name='core_joboff_candida_135e4a_idx',
            old_name='core_joboff_candidat_4fbb41_idx',
        ),
        migrations.RenameIndex(
            model_name='joboffer',
            new_name='core_joboff_candida_a61f93_idx',
            old_name='core_joboff_candidat_6055e4_idx',
        ),
        migrations.RenameIndex(
            model_name='joboffer',
            new_name='core_joboff_status_3beac8_idx',
            old_name='core_joboff_status_5450a9_idx',
        ),
        migrations.RenameIndex(
            model_name='jobofficelocation',
            new_name='core_joboff_job_id_c6afcb_idx',
            old_name='core_jol_job_idx',
        ),
        migrations.RenameIndex(
            model_name='jobofficelocation',
            new_name='core_joboff_job_id_30477c_idx',
            old_name='core_jol_job_created_idx',
        ),
        migrations.RemoveField(
            model_name='gmailintegration',
            name='auto_update_status',
        ),
        migrations.RemoveField(
            model_name='gmailintegration',
            name='scan_frequency',
        ),
        migrations.AddField(
            model_name='gmailintegration',
            name='rate_limit_reset_at',
            field=models.DateTimeField(blank=True, help_text='When the rate limit resets', null=True),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='location_geo_precision',
            field=models.CharField(blank=True, default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='location_geo_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='location_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='rolled_back_by',
            field=models.ForeignKey(blank=True, help_text='The deployment that rolled back this deployment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollback_target', to='core.deployment'),
        ),
        migrations.AddField(
            model_name='deploymentlog',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.deployment'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['environment', '-started_at'], name='core_deploy_environ_b94331_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['status', '-started_at'], name='core_deploy_status_d92a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['commit_sha'], name='core_deploy_commit__4e3c23_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['-created_at'], name='core_deploy_created_f1c915_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentlog',
            index=models.Index(fields=['deployment', 'timestamp'], name='core_deploy_deploym_90834e_idx'),
        ),
    ]
