# Generated by Django 5.2.8 on 2025-12-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_deployment_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthStateToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=64, unique=True)),
                ('provider', models.CharField(default='github', max_length=32)),
                ('user_id', models.CharField(blank=True, max_length=255)),
                ('profile_id', models.CharField(blank=True, max_length=255)),
                ('include_private', models.BooleanField(default=False)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name='oauthstatetoken',
            index=models.Index(fields=['state'], name='core_oauths_state_baea04_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthstatetoken',
            index=models.Index(fields=['expires_at'], name='core_oauths_expires_8d51fc_idx'),
        ),
    ]
