# Generated by Django 5.2.8 on 2025-12-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_jobentry_indexes'),
        ('core', '0123_jobentry_filter_indexes'),
    ]

    operations = [
    ]
